function namespace(a){a=a.split(".");for(var b=window,c=0;c<a.length;c++){if(typeof b[a[c]]=="undefined")b[a[c]]={};b=b[a[c]]}}namespace("rhizo");rhizo.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};namespace("rhizo.util");rhizo.util.LOG_E_10=Math.log(10);rhizo.util.log10_=function(a){return Math.log(a)/rhizo.util.LOG_E_10};
rhizo.util.orderOfMagnitude=function(a){if(a==0)return Number.NaN;return Math.floor(Math.round(rhizo.util.log10_(Math.abs(a))*100)/100)};namespace("rhizo.jquery");rhizo.jquery.init=function(a,b){rhizo.jquery.initAnimations_(a,b);rhizo.jquery.initMouseWheel_()};
rhizo.jquery.initAnimations_=function(a,b){jQuery().greyOut||function(c){b?c.fn.extend({move:function(d,e,f){c(this).css(jQuery.extend({top:d,left:e},f))},fadeIn:function(){c(this).css({visibility:"visible",opacity:1})},fadeOut:function(){c(this).css({visibility:"hidden",opacity:0})},greyOut:function(){c(this).css("opacity",0.2)}}):c.fn.extend({move:function(d,e,f){a.noFx?c(this).css(jQuery.extend({top:d,left:e},f)):c(this).animate(jQuery.extend({top:d,left:e},f),{duration:400,queue:false})},fadeIn:function(){a.noFx?
c(this).css({visibility:"visible",opacity:1}):c(this).css("visibility","visible").animate({opacity:1},400)},fadeOut:function(){a.noFx?c(this).css({visibility:"hidden",opacity:0}):c(this).animate({opacity:0},{duration:400,complete:function(){c(this).css("visibility","hidden")}})},greyOut:function(){a.noFx?c(this).css("opacity",0.2):c(this).animate({opacity:0.2},400)}});c.fn.fadeTo=function(d){if(d==rhizo.ui.Visibility.HIDDEN)this.fadeOut();else d==rhizo.ui.Visibility.VISIBLE?this.fadeIn():this.greyOut()}}(jQuery)};
rhizo.jquery.initMouseWheel_=function(){jQuery().mouseWheel||function(a){function b(f){var g=f||window.event,h=[].slice.call(arguments,1),i=g.timeStamp||(new Date).getTime();if(i-d<e)return false;d=i;var j=i=0;if(a.browser.webkit){i=g.wheelDeltaX;j=g.wheelDeltaY}else if(a.browser.mozilla)if(g.axis!==undefined&&g.axis===g.HORIZONTAL_AXIS)i=-g.detail;else j=-g.detail;else j=g.wheelDelta;i=i>0?1:i<0?-1:0;j=j>0?1:j<0?-1:0;f=a.event.fix(g);f.type="mousewheel";h.unshift(f,i,j);return a.event.handle.apply(this,
h)}var c=["DOMMouseScroll","mousewheel"],d=0,e=30;a.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var f=c.length;f;)this.addEventListener(c[--f],b,false);else this.onmousewheel=b},teardown:function(){if(this.removeEventListener)for(var f=c.length;f;)this.removeEventListener(c[--f],b,false);else this.onmousewheel=null}};a.fn.extend({mousewheel:function(f){return f?this.bind("mousewheel",f):this.trigger("mousewheel")},unmousewheel:function(f){return this.unbind("mousewheel",
f)}})}(jQuery)};namespace("rhizo.ui");rhizo.ui.Visibility={HIDDEN:0,GREY:1,VISIBLE:2};rhizo.ui.toHumanLabel=function(a){if(typeof a=="number"&&a!=0){var b=rhizo.util.orderOfMagnitude(a);if(b<0)return a.toFixed(-b);else if(b<3)return a;b=parseInt(b/3,10);var c=["","K","M","G","T","P","E","Z","Y"][b]||"";return(a/Math.pow(10,b*3)).toPrecision(3)+c}else return a};
rhizo.ui.canCacheDimensions=function(a,b){var c=false;if(a.cacheDimensions)c=a.cacheDimensions;if(b&&b.cacheDimensions)c=b.cacheDimensions;return c};rhizo.ui.render=function(a,b,c,d){a=b.render(a.unwrap(),a.expanded,d);if(typeof a=="string"){c.push('<div class="rhizo-model">');c.push(a);c.push("</div>")}else{b=$('<div class="rhizo-model"></div>');b.append(a);c.push(b)}};
rhizo.ui.reRender=function(a,b,c){b=$(b.render(a.unwrap(),a.expanded,c));a.naked_render=b;a.rendering.toggleClass("rhizo-model-expanded",a.expanded).css({width:"",height:""});a.rendering.children(":not(.rhizo-expand-model)").remove();a.rendering.append(b);a.refreshCachedDimensions()};
rhizo.ui.decorateRendering=function(a,b,c,d,e){var f,g=rhizo.ui.expandable(d,e);if(g)f=$("<div />",{"class":"rhizo-expand-model rhizo-maximize-icon"});a.each(function(h){$(this).data("id",b[h].id);b[h].expanded&&$(this).addClass("rhizo-model-expanded");if(g){var i=f.clone();i.data("id",b[h].id);$(this).append(i)}});g&&rhizo.ui.initExpandable(c,d,e);a.click(function(){if($(this).data("dragging"))$(this).removeData("dragging");else c.isSelected($(this).data("id"))?c.unselect($(this).data("id")):c.select($(this).data("id"))});
window.setTimeout(function(){rhizo.ui.initDraggable(a,c)},100)};rhizo.ui.expandable=function(a,b){return typeof a.expandable=="boolean"?a.expandable:typeof a.expandable=="function"?a.expandable(b):false};
rhizo.ui.initExpandable=function(a,b,c){if(rhizo.ui.expandable(b,c)){$(".rhizo-model").hover(function(){$(this).children(".rhizo-expand-model").css("visibility","visible")},function(){$(this).children(".rhizo-expand-model").css("visibility","hidden")});$(".rhizo-expand-model").click(function(d){d.stopPropagation();d=$(this).data("id");d=a.model(d);d.expanded=!d.expanded;rhizo.ui.reRender(d,b,c)})}};
rhizo.ui.initDraggable=function(a,b){a.draggable({opacity:0.7,cursor:"pointer",zIndex:1E4,distance:3,addClasses:false,start:function(c,d){d.helper.data("dragging",true);d.helper.data("dropTop0",parseInt(d.helper.css("top"),10));d.helper.data("dropLeft0",parseInt(d.helper.css("left"),10));if(b.isSelected(d.helper.data("id"))){var e=b.allSelected();for(var f in e){var g=e[f].rendering;g.data("top0",parseInt(g.css("top"),10)-parseInt(d.helper.css("top"),10));g.data("left0",parseInt(g.css("left"),10)-
parseInt(d.helper.css("left"),10));g.data("dropTop0",parseInt(g.css("top"),10));g.data("dropLeft0",parseInt(g.css("left"),10))}}},drag:function(c,d){var e=d.helper.data("id");if(b.isSelected(e)){var f=b.allSelected();for(var g in f)if(g!=e){f[g].rendering.css("top",f[g].rendering.data("top0")+d.position.top);f[g].rendering.css("left",f[g].rendering.data("left0")+d.position.left)}}},stop:function(c,d){if(b.isSelected(d.helper.data("id"))){var e=b.allSelected();for(var f in e){e[f].rendering.removeData("top0");
e[f].rendering.removeData("left0")}}},refreshPositions:false})};namespace("rhizo.keyboard");rhizo.keyboard.Style={PADDING:5,KEY_HEIGHT:40,KEY_WIDTH:40,KEY_RADIUS:5,KEY_COLORS:{pressed:{fg:"#7aa5d6",text:"#7aa5d6",bg:"#e5ecf9"},hover:{fg:"#7aa5d6",text:"#7aa5d6",bg:"#fff"},base:{fg:"#555",text:"#555",bg:"#fff"}},KEY_FONT:"normal normal normal 22px sans-serif"};
rhizo.keyboard.Keyboard=function(a){this.container_=a;this.keys_=[];this.canvas_=$("<canvas />",{"class":"rhizo-keyboard"}).appendTo(a);this.canvas_.get(0).width=this.canvas_.width();this.canvas_.get(0).height=this.canvas_.height();this.ctx_=this.canvas_.get(0).getContext("2d");this.canvas_.css({left:($(window).width()-this.canvas_.width())/2,top:($(window).height()-this.canvas_.height())/2});this.canvas_.draggable();this.focusTarget_=null;this.ignoreBlur_=false;this.initEvents_();this.initKeys_()};
rhizo.keyboard.Keyboard.prototype.paint=function(){this.ctx_.clearRect(0,0,this.canvas_.get(0).width,this.canvas_.get(0).height);for(var a=0;a<this.keys_.length;a++)this.keys_[a].paint(this.ctx_)};rhizo.keyboard.Keyboard.prototype.getKeys=function(){return this.keys_};rhizo.keyboard.Keyboard.prototype.getFocusTarget=function(){return this.focusTarget_};
rhizo.keyboard.Keyboard.prototype.initEvents_=function(){$("input, textarea",this.container_).focus(jQuery.proxy(function(a){this.focusTarget_=a.target;this.canvas_.show();this.paint()},this)).blur(jQuery.proxy(function(){this.ignoreBlur_||this.canvas_.hide()},this));this.canvas_.mousemove(jQuery.proxy(function(a){for(var b=false,c=0;c<this.keys_.length;c++){var d=this.keys_[c].isInside(a.offsetX||a.layerX,a.offsetY||a.layerY);b=b||d;this.keys_[c].setHover(d)}this.canvas_.css("cursor",b?"pointer":
"move").draggable(b?"disable":"enable");this.paint()},this));this.canvas_.mousedown(jQuery.proxy(this.mousedown_,this));this.canvas_.mouseup(jQuery.proxy(function(){this.ignoreBlur_=false;for(var a=0;a<this.keys_.length;a++)this.keys_[a].isToggle()||this.keys_[a].setPressed(false);this.paint();$(this.focusTarget_).focus()},this))};
rhizo.keyboard.Keyboard.prototype.mousedown_=function(a){this.ignoreBlur_=true;for(var b=0;b<this.keys_.length;b++){var c=this.keys_[b].isInside(a.offsetX||a.layerX,a.offsetY||a.layerY);if(this.keys_[b].isToggle())if(c)this.keys_[b].setPressed(!this.keys_[b].isPressed());else this.keys_[b].isToggleReleasedByOtherKeys()&&this.keys_[b].isPressed()&&this.keys_[b].setPressed(false);else this.keys_[b].setPressed(c)}this.paint()};
rhizo.keyboard.Keyboard.prototype.initKeys_=function(){var a={enter:rhizo.keyboard.EnterKey,"delete":rhizo.keyboard.DeleteKey,tab:rhizo.keyboard.TabKey,caps:rhizo.keyboard.CapsKey,shift:rhizo.keyboard.ShiftKey,reset:rhizo.keyboard.ResetKey,space:rhizo.keyboard.SpaceKey},b=[];b.push(["`","1","2","3","4","5","6","7","8","9","0","-","=","delete"]);b.push(["tab","q","w","e","r","t","y","u","i","o","p","[","]","\\"]);b.push(["caps","a","s","d","f","g","h","j","k","l",";","'","enter"]);b.push(["shift",
"z","x","c","v","b","n","m",",",".","/","reset"]);b.push(["space"]);for(var c=rhizo.keyboard.Style.PADDING,d=c,e=0;e<b.length;e++){for(var f=c,g=0;g<b[e].length;g++){var h=b[e][g];h=new (h in a?a[h]:rhizo.keyboard.Key)(b[e][g],f,d,this);this.keys_.push(h);f+=h.width()+c}d+=c+rhizo.keyboard.Style.KEY_HEIGHT}};
rhizo.keyboard.Key=function(a,b,c,d){this.key_=this.label_=a;this.kx_=b;this.ky_=c;this.keyboard_=d;this.radius_=rhizo.keyboard.Style.KEY_RADIUS;this.height_=rhizo.keyboard.Style.KEY_HEIGHT;this.width_=rhizo.keyboard.Style.KEY_WIDTH;this.hover_=this.pressed_=false;this.canAutofire_=true;this.autofireIntervalId_=null;this.colors_={}};rhizo.keyboard.Key.prototype.width=function(){return this.width_};rhizo.keyboard.Key.prototype.isToggle=function(){return false};
rhizo.keyboard.Key.prototype.paint=function(a){this.setStyles_(a);this.paintRoundedRect_(a);this.paintKey_(a)};rhizo.keyboard.Key.prototype.setStyles_=function(){this.colors_=this.pressed_?rhizo.keyboard.Style.KEY_COLORS.pressed:this.hover_?rhizo.keyboard.Style.KEY_COLORS.hover:rhizo.keyboard.Style.KEY_COLORS.base};
rhizo.keyboard.Key.prototype.paintRoundedRect_=function(a){a.beginPath();a.moveTo(this.kx_,this.ky_+this.radius_);a.lineTo(this.kx_,this.ky_+this.height_-this.radius_);a.quadraticCurveTo(this.kx_,this.ky_+this.height_,this.kx_+this.radius_,this.ky_+this.height_);a.lineTo(this.kx_+this.width()-this.radius_,this.ky_+this.height_);a.quadraticCurveTo(this.kx_+this.width(),this.ky_+this.height_,this.kx_+this.width(),this.ky_+this.height_-this.radius_);a.lineTo(this.kx_+this.width(),this.ky_+this.radius_);
a.quadraticCurveTo(this.kx_+this.width(),this.ky_,this.kx_+this.width()-this.radius_,this.ky_);a.lineTo(this.kx_+this.radius_,this.ky_);a.quadraticCurveTo(this.kx_,this.ky_,this.kx_,this.ky_+this.radius_);a.strokeStyle=this.colors_.fg;a.fillStyle=this.colors_.bg;a.fill();a.stroke()};
rhizo.keyboard.Key.prototype.paintKey_=function(a){a.fillStyle=this.colors_.text;a.font=rhizo.keyboard.Style.KEY_FONT;a.textBaseline="middle";a.textAlign="center";a.fillText(this.label_,this.kx_+this.width()/2,this.ky_+this.height_/2)};rhizo.keyboard.Key.prototype.isInside=function(a,b){return this.kx_<a&&this.kx_+this.width()>a&&this.ky_<b&&this.ky_+this.height_>b};rhizo.keyboard.Key.prototype.setHover=function(a){this.hover_=a};
rhizo.keyboard.Key.prototype.setPressed=function(a){(this.pressed_=a)&&this.modifyTarget_(this.keyboard_.getFocusTarget());if(this.canAutofire_)if(this.pressed_){if(this.autofireIntervalId_==null)this.autofireIntervalId_=window.setInterval(jQuery.proxy(this.setPressed,this),100,true)}else{window.clearInterval(this.autofireIntervalId_);this.autofireIntervalId_=null}};rhizo.keyboard.Key.prototype.isPressed=function(){return this.pressed_};
rhizo.keyboard.Key.prototype.setCaps=function(a){var b="abcdefghijklmnopqrstuvwxyz".toUpperCase(),c=a?"abcdefghijklmnopqrstuvwxyz`1234567890-=[]\\;',./":b+'~!@#$%^&*()_+{}|:"<>?';a=a?b+'~!@#$%^&*()_+{}|:"<>?':"abcdefghijklmnopqrstuvwxyz`1234567890-=[]\\;',./";for(b=0;b<c.length;b++)if(c[b]==this.label_){this.label_=a[b];this.key_=a[b];break}};
rhizo.keyboard.Key.prototype.modifyTarget_=function(a){var b=a.selectionStart,c=a.selectionEnd,d=$(a).val(),e="";if(c-b>0){e=d.substr(c);d=d.substr(0,b)}$(a).val(d+this.key_+e)};rhizo.keyboard.EnterKey=function(a,b,c,d){rhizo.keyboard.Key.call(this,a,b,c,d);this.width_=77;this.canAutofire_=false};rhizo.inherits(rhizo.keyboard.EnterKey,rhizo.keyboard.Key);rhizo.keyboard.EnterKey.prototype.modifyTarget_=function(a){$(a).change()};
rhizo.keyboard.TabKey=function(a,b,c,d){rhizo.keyboard.Key.call(this,a,b,c,d);this.width_=70;this.key_="\t"};rhizo.inherits(rhizo.keyboard.TabKey,rhizo.keyboard.Key);rhizo.keyboard.DeleteKey=function(a,b,c,d){rhizo.keyboard.Key.call(this,a,b,c,d);this.width_=70};rhizo.inherits(rhizo.keyboard.DeleteKey,rhizo.keyboard.Key);
rhizo.keyboard.DeleteKey.prototype.modifyTarget_=function(a){var b=a.selectionStart,c=a.selectionEnd,d=$(a).val();if(c-b>0)$(a).val(d.substr(0,b)+d.substr(c));else d.length>0&&$(a).val(d.substr(0,d.length-1))};rhizo.keyboard.CapsKey=function(a,b,c,d){rhizo.keyboard.Key.call(this,a,b,c,d);this.width_=80;this.canAutofire_=false};rhizo.inherits(rhizo.keyboard.CapsKey,rhizo.keyboard.Key);rhizo.keyboard.CapsKey.prototype.setPressed=function(a){this.pressed_=a;a=this.keyboard_.getKeys();for(var b=0;b<a.length;b++)a[b].setCaps(this.pressed_)};
rhizo.keyboard.CapsKey.prototype.isToggle=function(){return true};rhizo.keyboard.CapsKey.prototype.isToggleReleasedByOtherKeys=function(){return false};rhizo.keyboard.ShiftKey=function(a,b,c,d){rhizo.keyboard.CapsKey.call(this,a,b,c,d);this.width_=97};rhizo.inherits(rhizo.keyboard.ShiftKey,rhizo.keyboard.CapsKey);rhizo.keyboard.ShiftKey.prototype.isToggleReleasedByOtherKeys=function(){return true};
rhizo.keyboard.ResetKey=function(a,b,c,d){rhizo.keyboard.Key.call(this,a,b,c,d);this.width_=105;this.canAutofire_=false};rhizo.inherits(rhizo.keyboard.ResetKey,rhizo.keyboard.Key);rhizo.keyboard.ResetKey.prototype.modifyTarget_=function(a){$(a).val("").change()};rhizo.keyboard.SpaceKey=function(a,b,c,d){rhizo.keyboard.Key.call(this,a,b,c,d);this.width_=660;this.key_=" "};rhizo.inherits(rhizo.keyboard.SpaceKey,rhizo.keyboard.Key);namespace("rhizo.meta");rhizo.meta.StringKind=function(){};
rhizo.meta.StringKind.prototype.renderFilter=function(a,b,c){var d=$("<input type='text' />");$(d).change(function(){a.filter(c,$(this).val())});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d))};rhizo.meta.StringKind.prototype.survivesFilter=function(a,b){return a!=""&&b.toLowerCase().indexOf(a.toLowerCase())!=-1};rhizo.meta.StringKind.prototype.cluster=function(a){return{key:a.toUpperCase().charAt(0),label:a.toUpperCase().charAt(0)}};
rhizo.meta.StringKind.prototype.isNumeric=function(){return false};rhizo.meta.NumberKind=function(){};rhizo.meta.NumberKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.NumberKind.prototype.survivesFilter=function(a,b){var c=parseInt(a,10);return isNaN(c)?true:c==b};rhizo.meta.NumberKind.prototype.compare=function(a,b){return parseInt(a,10)-parseInt(b,10)};
rhizo.meta.NumberKind.prototype.cluster=function(a){var b=parseInt(a,10);if(parseFloat(a)<=10)return{key:b,label:b.toString()};for(var c=0;b>=10;){b=parseInt(b/10);c++}c=Math.pow(10,c);b=parseInt(a/c,10)*c;a=parseInt(a/c+1,10)*c;return{key:b,label:b.toString()+" - "+a.toString()}};rhizo.meta.NumberKind.prototype.isNumeric=function(){return true};
rhizo.meta.DateKind=function(a){this.monthMap_=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];this.clusterby_=a||"y";if(this.clusterby_!="y"&&this.clusterby_!="m"&&this.clusterby_!="d")this.clusterby_="y"};
rhizo.meta.DateKind.prototype.renderFilter=function(a,b,c){var d=$("<select style='vertical-align:top' />");d.append("<option value='yyyy'>yyyy</option>");for(var e=b.minYear;e<=b.maxYear;e++)d.append("<option value='"+e+"'>"+e+"</option>");var f=$("<select style='vertical-align:top' />");f.append("<option value='mm'>mm</option>");for(e=0;e<this.monthMap_.length;e++)f.append("<option value='"+e+"'>"+this.monthMap_[e]+"</option>");var g=$("<select style='vertical-align:top' />");g.append("<option value='dd'>dd</option>");
for(e=1;e<=31;e++)g.append("<option value='"+e+"'>"+e+"</option>");$(d).add($(f)).add($(g)).change(function(){a.filter(c,[$(d).val(),$(f).val(),$(g).val()])});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d)).append(" - ").append($(f)).append(" - ").append($(g))};
rhizo.meta.DateKind.prototype.survivesFilter=function(a,b){var c=parseInt(a[0],10),d=parseInt(a[1],10),e=parseInt(a[2],10);return(isNaN(c)||b.getFullYear()==c)&&(isNaN(d)||b.getMonth()==d)&&(isNaN(e)||b.getDate()==e)};
rhizo.meta.DateKind.prototype.cluster=function(a){return this.clusterby_=="y"?{key:a.getFullYear()+"-00-01",label:a.getFullYear()}:this.clusterby_=="m"?{key:a.getFullYear()+"-"+this.addZero_(a.getMonth())+"-01",label:a.getFullYear()+"-"+this.monthMap_[a.getMonth()]}:{key:a.getFullYear()+"-"+this.addZero_(a.getMonth())+"-"+this.addZero_(a.getDate()),label:a.getFullYear()+"-"+this.monthMap_[a.getMonth()]+"-"+a.getDate()}};rhizo.meta.DateKind.prototype.isNumeric=function(){return false};
rhizo.meta.DateKind.prototype.addZero_=function(a){a=a.toString();if(a.length==1)a="0"+a;return a};rhizo.meta.RangeKind=function(){};
rhizo.meta.RangeKind.prototype.renderFilter=function(a,b,c){var d=$("<div class='rhizo-slider' />"),e=$("<strong>"+this.toHumanLabel_(b.min)+"</strong>"),f=$("<strong>"+this.toHumanLabel_(b.max)+"</strong>"),g=this.toFilterScale_(b.min),h=this.toFilterScale_(b.max),i;if(b.stepping)i=this.toFilterScale_(b.stepping);var j=jQuery.proxy(function(m,l){if(l.values[0]!=g){e.text(this.toHumanLabel_(this.toModelScale_(l.values[0]))).addClass("rhizo-slider-moving");f.removeClass("rhizo-slider-moving")}if(l.values[1]!=
h){f.text(this.toHumanLabel_(this.toModelScale_(l.values[1]))).addClass("rhizo-slider-moving");e.removeClass("rhizo-slider-moving")}},this),o=jQuery.proxy(function(m,l){var k=Math.max(this.toModelScale_(l.values[0]),b.min),n=Math.min(this.toModelScale_(l.values[1]),b.max);e.text(this.toHumanLabel_(k)).removeClass("rhizo-slider-moving");f.text(this.toHumanLabel_(n)).removeClass("rhizo-slider-moving");a.filter(c,{min:k,max:n})},this);$(d).slider({stepping:i,steps:b.steps,range:true,min:g,max:h,slide:j,
stop:o,orientation:"horizontal",values:[g,h]});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(e)).append(" to ").append($(f)).append($(d))};rhizo.meta.RangeKind.prototype.survivesFilter=function(a,b){return b>=a.min&&b<=a.max};rhizo.meta.RangeKind.prototype.compare=rhizo.meta.NumberKind.prototype.compare;rhizo.meta.RangeKind.prototype.cluster=rhizo.meta.NumberKind.prototype.cluster;rhizo.meta.RangeKind.prototype.isNumeric=rhizo.meta.NumberKind.prototype.isNumeric;
rhizo.meta.RangeKind.prototype.toModelScale_=function(a){return a};rhizo.meta.RangeKind.prototype.toFilterScale_=function(a){return a};rhizo.meta.RangeKind.prototype.toHumanLabel_=function(a){return a};rhizo.meta.BooleanKind=function(){};
rhizo.meta.BooleanKind.prototype.renderFilter=function(a,b,c){var d=$("<select />");d.append("<option value=''>-</option>");d.append("<option value='true'>Yes</option>");d.append("<option value='false'>No</option>");$(d).change(function(){a.filter(c,$(this).val())});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d))};rhizo.meta.BooleanKind.prototype.survivesFilter=function(a,b){return a=="true"==b};
rhizo.meta.BooleanKind.prototype.compare=function(a,b){return a?b?0:-1:b?1:0};rhizo.meta.BooleanKind.prototype.isNumeric=function(){return false};rhizo.meta.CategoryKind=function(){};
rhizo.meta.CategoryKind.prototype.renderFilter=function(a,b,c){var d=$("<select "+(b.multiple?'multiple size="4" ':"")+" style='vertical-align:top' />");d.append("<option value=''>-</option>");for(var e=0;e<b.categories.length;e++)d.append("<option value='"+b.categories[e]+"'>"+b.categories[e]+"</option>");$(d).change(function(){var f=[$(this).val()];if(b.multiple)f=$.grep($(this).val(),function(g){return g!=""});a.filter(c,f)});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d))};
rhizo.meta.CategoryKind.prototype.survivesFilter=function(a,b){for(var c=false,d=0;d<a.length;d++)if(b.indexOf(a[d])!=-1){c=true;break}return c};rhizo.meta.CategoryKind.prototype.cluster=function(a){return{key:a.length==0?"Nothing":a,label:a.length==0?"Nothing":a}};rhizo.meta.CategoryKind.prototype.compare=function(a,b){return a.length-b.length};rhizo.meta.CategoryKind.prototype.isNumeric=function(){return false};
rhizo.meta.sortBy=function(a,b,c){return function(d,e){var f=d.unwrap(),g=e.unwrap(),h=c?-1:1;return b.compare?b.compare(f[a],g[a])*h:(f[a]<g[a]?-1:f[a]>g[a]?1:0)*h}};rhizo.meta.sortByKind=function(a,b){return function(c,d){var e=b?-1:1;return a.compare?a.compare(c,d)*e:(c<d?-1:c>d?1:0)*e}};rhizo.meta.Kind={STRING:new rhizo.meta.StringKind,NUMBER:new rhizo.meta.NumberKind,DATE:new rhizo.meta.DateKind,RANGE:new rhizo.meta.RangeKind,BOOLEAN:new rhizo.meta.BooleanKind,CATEGORY:new rhizo.meta.CategoryKind};
namespace("rhizo");rhizo.nativeConsoleExists=function(){return typeof console!=="undefined"&&console!=null};rhizo.NoOpLogger=function(){};rhizo.NoOpLogger.prototype.info=function(){};rhizo.NoOpLogger.prototype.error=function(){};rhizo.NoOpLogger.prototype.warn=function(){};rhizo.NativeLogger=function(){};rhizo.NativeLogger.prototype.info=function(a){console.info(a)};rhizo.NativeLogger.prototype.error=function(a){console.error(a)};rhizo.NativeLogger.prototype.warn=function(a){console.warn(a)};
rhizo.Logger=function(a){this.console_=a.getComponent("rhizo.ui.component.Console");this.rightBar_=a.getComponent("rhizo.ui.component.RightBar")};
rhizo.Logger.prototype.log_=function(a,b){var c=b||"info",d="#888";switch(c){case "error":d="#ff0000";break;case "warn":d="#ffff00";break}var e=new Date;e=e.getHours()+":"+e.getMinutes()+":"+e.getSeconds()+" ";c=$("<p class='rhizo-log-"+c+"'>"+e+a+"</p>");this.console_.getContents().prepend(c);b&&c.effect("highlight",{color:d},1E3);if(!this.console_.getContents().is(":visible")&&b)this.rightBar_&&!this.rightBar_.getPanel().is(":visible")?this.rightBar_.getToggle().effect("highlight",{color:d},1E3):
this.console_.getHeader().effect("highlight",{color:d},1E3)};rhizo.Logger.prototype.info=function(a){this.log_(a)};rhizo.Logger.prototype.error=function(a){this.log_(a,"error")};rhizo.Logger.prototype.warn=function(a){this.log_(a,"warn")};rhizo.meta.DecimalKind=function(a){this.precision_=a||2};rhizo.meta.DecimalKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;
rhizo.meta.DecimalKind.prototype.survivesFilter=function(a,b){var c=parseFloat(a);return isNaN(c)?true:c.toFixed(this.precision_)==b.toFixed(this.precision_)};rhizo.meta.DecimalKind.prototype.compare=function(a,b){return parseFloat(a)-parseFloat(b)};
rhizo.meta.DecimalKind.prototype.cluster=function(a){a=parseFloat(a.toFixed(this.precision_),10);var b=rhizo.util.orderOfMagnitude(a);if(isNaN(b))return{key:0,label:(new Number(0)).toFixed(this.precision_)};a=Math.pow(10,b);b=Math.pow(10,b+1);return{key:a,label:rhizo.ui.toHumanLabel(a)+" - "+rhizo.ui.toHumanLabel(b)}};rhizo.meta.DecimalKind.prototype.isNumeric=function(){return true};rhizo.meta.DecimalRangeKind=function(a){this.precision_=a||2;this.scale_=Math.pow(10,this.precision_)};
rhizo.meta.DecimalRangeKind.prototype.renderFilter=rhizo.meta.RangeKind.prototype.renderFilter;rhizo.meta.DecimalRangeKind.prototype.survivesFilter=rhizo.meta.RangeKind.prototype.survivesFilter;rhizo.meta.DecimalRangeKind.prototype.compare=rhizo.meta.DecimalKind.prototype.compare;rhizo.meta.DecimalRangeKind.prototype.cluster=rhizo.meta.DecimalKind.prototype.cluster;rhizo.meta.DecimalRangeKind.prototype.isNumeric=rhizo.meta.DecimalKind.prototype.isNumeric;
rhizo.meta.DecimalRangeKind.prototype.toModelScale_=function(a){return parseFloat((a/this.scale_).toFixed(this.precision_))};rhizo.meta.DecimalRangeKind.prototype.toFilterScale_=function(a){return Math.round(a*this.scale_)};rhizo.meta.DecimalRangeKind.prototype.toHumanLabel_=rhizo.meta.RangeKind.prototype.toHumanLabel_;rhizo.meta.LogarithmRangeKind=function(a,b){this.precision_=a||2;this.scale_=Math.pow(10,this.precision_);this.oneplus_=!!b};rhizo.meta.LogarithmRangeKind.prototype.renderFilter=rhizo.meta.DecimalRangeKind.prototype.renderFilter;
rhizo.meta.LogarithmRangeKind.prototype.survivesFilter=rhizo.meta.DecimalRangeKind.prototype.survivesFilter;rhizo.meta.LogarithmRangeKind.prototype.compare=rhizo.meta.DecimalRangeKind.prototype.compare;rhizo.meta.LogarithmRangeKind.prototype.cluster=rhizo.meta.DecimalRangeKind.prototype.cluster;rhizo.meta.LogarithmRangeKind.prototype.isNumeric=rhizo.meta.DecimalRangeKind.prototype.isNumeric;
rhizo.meta.LogarithmRangeKind.prototype.toModelScale_=function(a){var b=this.oneplus_?-1:0;return parseFloat(Math.pow(10,a/this.scale_).toFixed(this.precision_))+b};rhizo.meta.LogarithmRangeKind.prototype.toFilterScale_=function(a){a=this.oneplus_?a+1:a;return Math.round(rhizo.util.log10_(a)*this.scale_)};rhizo.meta.LogarithmRangeKind.prototype.toHumanLabel_=rhizo.meta.DecimalRangeKind.prototype.toHumanLabel_;rhizo.meta.StringArrayKind=function(){};
rhizo.meta.StringArrayKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.StringArrayKind.prototype.survivesFilter=function(a,b){if(a!="")for(var c=0;c<b.length;c++)if(b[c].toLowerCase().indexOf(a.toLowerCase())!=-1)return true;return false};rhizo.meta.StringArrayKind.prototype.cluster=function(){return{key:"undefined",label:"Clustering unsupported for this datatype."}};rhizo.meta.StringArrayKind.prototype.isNumeric=function(){return false};
rhizo.meta.Kind.DECIMAL=new rhizo.meta.DecimalKind;rhizo.meta.Kind.DECIMALRANGE=new rhizo.meta.DecimalRangeKind;rhizo.meta.Kind.LOGARITHMRANGE=new rhizo.meta.LogarithmRangeKind;rhizo.meta.Kind.STRINGARRAY=new rhizo.meta.StringArrayKind;namespace("rhizo.layout");rhizo.layout.metaModelKeySelector=function(a,b,c){b=$("<select class='"+b+"' />");if(a&&a.metaModel())for(var d in a.metaModel())if(!c||c(d,a.metaModel()[d]))b.append("<option value='"+d+"'>"+a.metaModel()[d].label+"</option>");return b};
rhizo.layout.Treeifier=function(a){this.parentKey_=a};
rhizo.layout.Treeifier.prototype.buildTree=function(a,b,c){c=c||{};for(var d=0,e=a.length;d<e;d++)c[a[d].id]=new rhizo.layout.TreeNode(a[d]);var f=new rhizo.layout.TreeNode;d=0;for(e=a.length;d<e;d++)if(!c[a[d].unwrap().id].traversed_)for(var g={},h=a[d].unwrap();;){if(g[h.id])throw new rhizo.layout.TreeCycleException("Tree is invalid: cycle detected");g[h.id]=true;c[h.id].traversed_=true;var i=this.findFirstVisibleParent_(b,b[h[this.parentKey_]]);if(i){var j=i.unwrap();c[j.id].addChild(c[h.id]);
h=i.unwrap()}else{f.addChild(c[h.id]);break}}return f};rhizo.layout.Treeifier.prototype.findFirstVisibleParent_=function(a,b){if(!b)return null;for(var c={};b.isFiltered();){if(c[b.id])throw new rhizo.layout.TreeCycleException("Tree is invalid: hidden cycle detected");c[b.id]=true;b=a[b.unwrap()[this.parentKey_]];if(!b)return null}return b};
rhizo.layout.TreeNode=function(a){this.superModel=a;this.id=null;if(a)this.id=a.id;this.childs={};this.traversed_=false;this.numChilds=0;this.is_root=this.id==null};rhizo.layout.TreeNode.prototype.addChild=function(a){if(!this.childs[a.id]){this.childs[a.id]=a;this.numChilds++}};rhizo.layout.TreeNode.prototype.childsAsArray=function(){var a=[];for(var b in this.childs)a.push(this.childs[b]);return a};
rhizo.layout.TreeNode.prototype.deepChildsAsArray=function(a){for(var b in this.childs){a.push(this.childs[b]);this.childs[b].deepChildsAsArray(a)}};rhizo.layout.TreeCycleException=function(a){this.message=a;this.name="TreeCycleException"};rhizo.layout.TreeCycleException.prototype.toString=function(){return this.name+": "+this.message};namespace("rhizo.model");
rhizo.model.SuperModel=function(a,b){this.model=a;this.id=a.id;this.selected=false;this.filters_={};this.naked_render=this.rendering=null;this.expanded=false;this.visibility=rhizo.ui.Visibility.HIDDEN;this.cacheDimensions_=false;this.cachedDimensions_={};this.setRendererHelpers_(b);this.rendererStyleChanger_=this.rendererRescaler_=null};
rhizo.model.SuperModel.prototype.setRendererHelpers_=function(a){if(typeof a.rescale=="function")this.rendererRescaler_=a.rescale;if(typeof a.changeStyle=="function")this.rendererStyleChanger_=a.changeStyle};rhizo.model.SuperModel.prototype.setDimensionCaching=function(a){this.cacheDimensions_=a};rhizo.model.SuperModel.prototype.unwrap=function(){return this.model};rhizo.model.SuperModel.prototype.toString=function(){return this.model.toString()};
rhizo.model.SuperModel.prototype.isFiltered=function(a){if(a)return this.filters_[a]||false;else{a=0;for(key in this.filters_)a++;return a!=0}};rhizo.model.SuperModel.prototype.filter=function(a){this.filters_[a]=true};rhizo.model.SuperModel.prototype.resetFilter=function(a){delete this.filters_[a]};
rhizo.model.SuperModel.prototype.rescaleRendering=function(a,b,c){if(a<=2||b<=2){c&&c();return false}this.cachedDimensions_={width:a,height:b};this.rendering.width(a-2).height(b-2);this.rendererRescaler_&&this.rendererRescaler_(a-2,b-2);return true};rhizo.model.SuperModel.prototype.setNakedCss=function(a){if(typeof a!="object")throw"setNakedCss() expects a map of properties.";this.rendererStyleChanger_?this.rendererStyleChanger_(a):this.naked_render.css(a)};
rhizo.model.SuperModel.prototype.nakedCss=function(a){if(typeof a!="string")throw"nakedCss() expects a string of the property to access.";return this.naked_render.css(a)};rhizo.model.SuperModel.prototype.refreshCachedDimensions=function(){if(this.rendering)this.cachedDimensions_={width:this.rendering.get(0).offsetWidth,height:this.rendering.get(0).offsetHeight}};
rhizo.model.SuperModel.prototype.getDimensions=function(){return this.cacheDimensions_?this.cachedDimensions_:{width:this.rendering.get(0).offsetWidth,height:this.rendering.get(0).offsetHeight}};namespace("rhizo.autorender");
rhizo.autorender.AR=function(a,b,c,d){this.metamodel_=a;this.metamodelFields_=0;for(var e in this.metamodel_)this.metamodelFields_++;this.fallbackToDefaults_=typeof c=="undefined"?true:c;this.locateFields_();a=0;if(this.sizeField_){this.sizeRange_=this.locateMinMax_(b,this.sizeField_);a++}if(this.colorField_){this.colorRange_=this.locateMinMax_(b,this.colorField_);a++}this.numfields_=typeof d=="undefined"?5:Math.max(d,a);this.cacheDimensions=true};rhizo.autorender.AR.prototype.getSizeRange=function(){return this.sizeRange_};
rhizo.autorender.AR.prototype.getColorRange=function(){return this.colorRange_};rhizo.autorender.AR.prototype.locateFields_=function(){for(key in this.metamodel_){this.masterField_=this.masterField_||this.getArField_(key,"master","true");this.sizeField_=this.sizeField_||this.getArField_(key,"bind","size");this.colorField_=this.colorField_||this.getArField_(key,"bind","color")}this.locateDefaultFields_()};
rhizo.autorender.AR.prototype.getArField_=function(a,b,c){if(this.metamodel_[a].ar)if((b=this.metamodel_[a].ar[b])&&b.toString().indexOf(c)!=-1)return a;return null};
rhizo.autorender.AR.prototype.locateDefaultFields_=function(){for(key in this.metamodel_){if(!this.masterField_)this.masterField_=key;if(!this.fallbackToDefaults_)break;if(!this.sizeField_&&(this.metamodel_[key].kind==rhizo.meta.Kind.NUMBER||this.metamodel_[key].kind==rhizo.meta.Kind.RANGE))this.sizeField_=key;else if(this.sizeField_)if(!this.colorField_&&(this.metamodel_[key].kind==rhizo.meta.Kind.NUMBER||this.metamodel_[key].kind==rhizo.meta.Kind.RANGE))this.colorField_=key}};
rhizo.autorender.AR.prototype.locateMinMax_=function(a,b){if(this.metamodel_[b].kind==rhizo.meta.Kind.RANGE)return{min:this.metamodel_[b].min,max:this.metamodel_[b].max,label:this.metamodel_[b].label};else{var c=Number.POSITIVE_INFINITY,d=Number.NEGATIVE_INFINITY;$.each(a,function(e,f){c=Math.min(c,f[b]);d=Math.max(d,f[b])});return{min:c,max:d,label:this.metamodel_[b].label}}};
rhizo.autorender.AR.prototype.getClass_=function(a,b,c,d){a=parseInt((a-b.min)/(b.max-b.min)*5,10);return"ar-"+d+"-"+a.toString()+(c.small?"m":"")};rhizo.autorender.AR.prototype.getFontClass_=function(a,b,c){return this.getClass_(a,b,c,"fon")};rhizo.autorender.AR.prototype.getColorClass_=function(a,b,c){return this.getClass_(a,b,c,"col")};
rhizo.autorender.AR.prototype.renderSingleModelKey_=function(a,b){var c=[];c.push('<p><span class="rhizo-autorender-label">');c.push(this.metamodel_[a].label);c.push("</span>: ");c.push(b);c.push("</p>");return c.join("")};rhizo.autorender.AR.prototype.expandable=function(a){return this.metamodelFields_>(a.small?1:this.numfields_+1)};
rhizo.autorender.AR.prototype.render=function(a,b,c){var d="ar-col-0"+(c.small?"m":"");if(this.colorField_)d=this.getColorClass_(a[this.colorField_],this.colorRange_,c);var e="ar-fon-0"+(c.small?"m":"");if(this.sizeField_)e=this.getFontClass_(a[this.sizeField_],this.sizeRange_,c);if(c.small&&!b)return $("<div class='rhizo-autorender "+d+"'><span class='"+e+"'>"+a[this.masterField_]+"</span></div>");else{html=[];html.push("<div class='rhizo-autorender "+d+"'>");html.push("<span class='"+e+"'>"+a[this.masterField_]+
"</span>");c=0;if(this.sizeField_){html.push(this.renderSingleModelKey_(this.sizeField_,a[this.sizeField_]));c++}if(this.colorField_&&this.colorField_!=this.sizeField_){html.push(this.renderSingleModelKey_(this.colorField_,a[this.colorField_]));c++}for(key in this.metamodel_){if(c>=this.numfields_&&!b)break;if(key!=this.sizeField_&&key!=this.colorField_&&key!=this.masterField_){c++;html.push(this.renderSingleModelKey_(key,a[key]))}}html.push("</div>");return $(html.join(""))}};namespace("rhizo.gviz");
rhizo.gviz.Initializer=function(a,b,c,d){this.dt_=a;this.logger_=b;this.options_=c||{};this.customRenderer_=d;this.init_()};rhizo.gviz.Initializer.prototype.init_=function(){this.metamodel=this.buildMetaModel_();this.models=this.loadModels_(this.metamodel);this.renderer=this.customRenderer_?this.customRenderer_:this.createDefaultRenderer_(this.metamodel,this.models)};
rhizo.gviz.Initializer.prototype.buildMetaModel_=function(){for(var a={},b=0,c=this.dt_.getNumberOfColumns();b<c;b++){var d=this.dt_.getColumnId(b);a[d]={};a[d].label=this.dt_.getColumnLabel(b);if(a[d].label=="")a[d].label="Column "+d;var e=this.dt_.getColumnType(b);if(e=="number"){e=this.dt_.getColumnRange(b).min;var f=this.dt_.getColumnRange(b).max;if(e==f)a[d].kind=rhizo.meta.Kind.NUMBER;else{a[d].kind=rhizo.meta.Kind.RANGE;a[d].min=e;a[d].max=f}}else if(e=="boolean")a[d].kind=rhizo.meta.Kind.BOOLEAN;
else{e!="string"&&this.logger_.warn("Column "+a[d].label+" will be treated as String. Unsupported type: "+e);if(a[d].label.indexOf("CAT")!=-1){a[d].kind=rhizo.meta.Kind.CATEGORY;a[d].label=a[d].label.replace("CAT","").replace(/^\s+|\s+$/g,"");a[d].categories=this.parseCategories_(b);if(a[d].label.indexOf("MUL")!=-1){a[d].label=a[d].label.replace("MUL","").replace(/^\s+|\s+$/g,"");a[d].multiple=true}}else a[d].kind=rhizo.meta.Kind.STRING}this.buildAutoRenderInfo_(a[d],d)}return a};
rhizo.gviz.Initializer.prototype.parseSingleCategory_=function(a){var b={};a=a.split(",");a=$.grep(a,function(d){return d!=""});for(var c=0;c<a.length;c++)b[a[c].replace(/^\s+|\s+$/g,"")]=true;a=[];for(category in b)a.push(category);return a};rhizo.gviz.Initializer.prototype.parseCategories_=function(a){for(var b={},c=0,d=this.dt_.getNumberOfRows();c<d;c++)for(var e=this.parseSingleCategory_(this.dt_.getValue(c,a)),f=0;f<e.length;f++)b[e[f]]=true;a=[];for(category in b)a.push(category);return a.sort()};
rhizo.gviz.Initializer.prototype.buildAutoRenderInfo_=function(a,b){var c={},d=false;if(this.options_.arMaster&&this.matchAutoRenderOption_(this.options_.arMaster,a.label,b))d=c.master=true;if(this.options_.arSize&&this.matchAutoRenderOption_(this.options_.arSize,a.label,b)){c.bind=(c.bind?c.bind:"")+"size ";d=true}if(this.options_.arColor&&this.matchAutoRenderOption_(this.options_.arColor,a.label,b)){c.bind=(c.bind?c.bind:"")+"color ";d=true}if(d)a.ar=c};
rhizo.gviz.Initializer.prototype.matchAutoRenderOption_=function(a,b,c){return/^[a-zA-Z]$/.test(a)?a.toLowerCase()==(new String(c)).toLowerCase():b.toLowerCase()==a.toLowerCase()?true:b.replace("CAT","").replace("MUL","").toLowerCase()==a.toLowerCase()};
rhizo.gviz.Initializer.prototype.loadModels_=function(a){for(var b=[],c=0,d=this.dt_.getNumberOfRows();c<d;c++){for(var e={},f=0,g=this.dt_.getNumberOfColumns();f<g;f++){e.id="gviz-"+c;var h=this.dt_.getValue(c,f);if(a[this.dt_.getColumnId(f)].kind==rhizo.meta.Kind.CATEGORY)e[this.dt_.getColumnId(f)]=this.parseSingleCategory_(h);else e[this.dt_.getColumnId(f)]=h}b.push(e)}return b};
rhizo.gviz.Initializer.prototype.createDefaultRenderer_=function(a,b){return new rhizo.autorender.AR(a,b,this.options_.arDefaults,this.options_.arNumFields)};rhizo.gviz.DebugRenderer=function(a){this.dt_=a};rhizo.gviz.DebugRenderer.prototype.render=function(a){for(var b=$("<div />"),c=0,d=this.dt_.getNumberOfColumns();c<d;c++)b.append("<p>"+a[this.dt_.getColumnId(c)]+"</p>");return b};namespace("rhizo.layout");rhizo.layout.NoLayout=function(){};rhizo.layout.NoLayout.prototype.layout=function(){return false};
rhizo.layout.NoLayout.prototype.toString=function(){return"-"};rhizo.layout.FlowLayout=function(a,b,c){this.project_=a;this.top=b||5;this.left=c||5;this.reverseCheckbox_=this.orderSelector_=null};
rhizo.layout.FlowLayout.prototype.layout=function(a,b,c,d){a=a.width();c=0;var e=this.orderSelector_.val(),f=this.reverseCheckbox_.is(":checked");if(e){this.project_.logger().info("Sorting by "+e);b.sort(rhizo.meta.sortBy(e,d[e].kind,f))}d=0;for(e=b.length;d<e;d++){f=b[d].getDimensions();c=Math.max(c,f.height);if(this.left+f.width>a){this.left=5;this.top+=c+5;c=f.height}b[d].rendering.move(this.top,this.left);this.left+=f.width+5}this.top+=c;return false};
rhizo.layout.FlowLayout.prototype.overrideDetailControls=function(a,b){this.orderSelector_=a;this.reverseCheckbox_=b};rhizo.layout.FlowLayout.prototype.cleanup=function(){this.top=this.left=5;return false};rhizo.layout.FlowLayout.prototype.details=function(){this.orderSelector_=rhizo.layout.metaModelKeySelector(this.project_,"rhizo-flowlayout-order");this.reverseCheckbox_=$('<input type="checkbox" class="rhizo-flowlayout-desc" />');return $("<div />").append("Ordered by: ").append(this.orderSelector_).append(" desc?").append(this.reverseCheckbox_)};
rhizo.layout.FlowLayout.prototype.toString=function(){return"List"};rhizo.layout.ScrambleLayout=function(){};rhizo.layout.ScrambleLayout.prototype.layout=function(a,b,c,d,e){if(e.filter)return false;c=a.width();a=a.height();d=Math.round(c*0.3);e=Math.round(a*0.3);for(var f=0,g=b.length;f<g;f++)$(b[f].rendering).move(Math.round(a/3+Math.random()*e*2-e),Math.round(c/3+Math.random()*d*2-d));return false};rhizo.layout.ScrambleLayout.prototype.toString=function(){return"Random"};
rhizo.layout.BucketLayout=function(a){this.project_=a;this.internalFlowLayout_=new rhizo.layout.FlowLayout(a);this.bucketHeaders_=[];this.reverseCheckbox_=this.bucketSelector_=null};
rhizo.layout.BucketLayout.prototype.layout=function(a,b,c,d,e){var f=this.reverseCheckbox_.is(":checked"),g=this.bucketSelector_.val();if(!d[g]){this.project_.logger().error("layoutBy attribute does not match any property");return false}this.project_.logger().info("Bucketing by "+g);this.internalFlowLayout_.overrideDetailControls(this.bucketSelector_,this.reverseCheckbox_);var h,i;if(d[g].cluster){h=d[g].cluster;i=d[g]}else{h=d[g].kind.cluster;i=d[g].kind}for(var j={},o={},m=0,l=b.length;m<l;m++){var k=
b[m].unwrap()[g],n=k;if(h){n=h.call(i,k);k=n.key;n=n.label}if(!j[k]){j[k]=[];o[k]=n}j[k].push(b[m])}b=[];for(k in j)b.push(k);b.sort(rhizo.meta.sortByKind(d[g].kind,f));f=false;for(m=0;m<b.length;m++){k=b[m];this.renderBucketHeader_(a,o[k]);f=this.internalFlowLayout_.layout(a,j[k],c,d,e)||f;this.internalFlowLayout_.top+=10;this.internalFlowLayout_.left=5}return f};
rhizo.layout.BucketLayout.prototype.renderBucketHeader_=function(a,b){var c=$("<div class='rhizo-bucket-header'>"+b+"</div>");c.css("position","absolute").css("left",5).css("top",this.internalFlowLayout_.top);this.bucketHeaders_.push(c);a.append(c);this.internalFlowLayout_.top+=c.height()+5};
rhizo.layout.BucketLayout.prototype.details=function(){this.bucketSelector_=rhizo.layout.metaModelKeySelector(this.project_,"rhizo-bucketlayout-bucket");this.reverseCheckbox_=$('<input type="checkbox" class="rhizo-bucketlayout-desc" />');return $("<div />").append("Group by: ").append(this.bucketSelector_).append(" desc?").append(this.reverseCheckbox_)};
rhizo.layout.BucketLayout.prototype.cleanup=function(a,b){this.internalFlowLayout_.cleanup(a,b);$.each(this.bucketHeaders_,function(){this.remove()});this.bucketHeaders_=[];return false};rhizo.layout.BucketLayout.prototype.toString=function(){return"Buckets"};rhizo.layout.layouts={no:rhizo.layout.NoLayout,flow:rhizo.layout.FlowLayout,scramble:rhizo.layout.ScrambleLayout,bucket:rhizo.layout.BucketLayout};namespace("rhizo");
rhizo.Project=function(a,b){this.models_=[];this.modelsMap_={};this.selectionMap_={};this.options_=b||{};this.gui_=a;this.filterAutocommit_=true;this.logger_=rhizo.nativeConsoleExists()?new rhizo.NativeLogger:new rhizo.NoOpLogger};rhizo.Project.prototype.chromeReady=function(){if(this.gui_.getComponent("rhizo.ui.component.Console"))this.logger_=new rhizo.Logger(this.gui_)};rhizo.Project.prototype.metaReady=function(){this.initializeLayoutEngines_()};
rhizo.Project.prototype.initializeLayoutEngines_=function(){this.curLayoutName_="flow";this.layoutEngines_={};for(var a in rhizo.layout.layouts){var b=new rhizo.layout.layouts[a](this),c=true;if(b.verifyMetaModel&&!b.verifyMetaModel(this.metaModel_))c=false;if(c)this.layoutEngines_[a]=b}};rhizo.Project.prototype.deploy=function(a){a&&this.addModels_(a)&&this.finalizeUI_();this.logger_.info("*** Ready!")};
rhizo.Project.prototype.addModels_=function(a){for(var b=0;b<a.length;b++)this.models_[b]=new rhizo.model.SuperModel(a[b],this.renderer_);if(!this.checkModels_())return false;this.buildModelsMap_();return true};
rhizo.Project.prototype.finalizeUI_=function(){if(this.initializeRenderings_()){var a=rhizo.ui.canCacheDimensions(this.renderer_,this.options_);if(a)for(var b=this.models_.length-1;b>=0;b--){this.models_[b].setDimensionCaching(a);this.models_[b].refreshCachedDimensions()}this.gui_.disableFx(true);this.layout(this.curLayoutName_,{forcealign:true});this.alignFx()}};rhizo.Project.prototype.model=function(a){return this.modelsMap_[a]};rhizo.Project.prototype.metaModel=function(){return this.metaModel_};
rhizo.Project.prototype.setMetaModel=function(a){this.metaModel_=a};rhizo.Project.prototype.renderer=function(){return this.renderer_};rhizo.Project.prototype.setRenderer=function(a){this.renderer_=a};rhizo.Project.prototype.gui=function(){return this.gui_};rhizo.Project.prototype.logger=function(){return this.logger_};rhizo.Project.prototype.layoutEngines=function(){return this.layoutEngines_};rhizo.Project.prototype.currentLayoutEngineName=function(){return this.curLayoutName_};
rhizo.Project.prototype.resetAllFilter=function(a){for(var b=this.models_.length-1;b>=0;b--)this.models_[b].resetFilter(a)};rhizo.Project.prototype.enableFilterAutocommit=function(a){if(this.filterAutocommit_=a)for(a=this.models_.length-1;a>=0;a--)if(this.models_[a].visibility==rhizo.ui.Visibility.GREY){this.commitFilter();break}};rhizo.Project.prototype.isFilterAutocommit=function(){return this.filterAutocommit_};
rhizo.Project.prototype.select=function(a){a=this.extendSelection_(a);for(var b=a.length-1;b>=0;b--){var c=this.model(a[b]);this.selectionMap_[a[b]]=c;c.selected=true;c.rendering.addClass("ui-selected")}};rhizo.Project.prototype.unselect=function(a){a=this.extendSelection_(a);for(var b=a.length-1;b>=0;b--)this.unselectInternal_(a[b])};rhizo.Project.prototype.unselectAll=function(){for(id in this.selectionMap_)this.unselectInternal_(id)};
rhizo.Project.prototype.unselectInternal_=function(a){var b=this.model(a);this.selectionMap_[a]=null;delete this.selectionMap_[a];b.selected=false;b.rendering.removeClass("ui-selected")};rhizo.Project.prototype.isSelected=function(a){return this.selectionMap_[a]};rhizo.Project.prototype.allSelected=function(){return this.selectionMap_};rhizo.Project.prototype.allUnselected=function(){var a=this.selectionMap_;return $.grep(this.models_,function(b){return!a[b.id]})};
rhizo.Project.prototype.extendSelection_=function(a){var b=this.layoutEngines_[this.curLayoutName_];if(b.dependentModels){b=b.dependentModels(a);b.push(a);return b}return[a]};rhizo.Project.prototype.checkModels_=function(){this.logger_.info("Checking models...");for(var a=true,b=this.models_.length-1;b>=0;b--)if(!this.models_[b].id){a=false;this.logger_.error("Verify your models: missing ids.")}return a};
rhizo.Project.prototype.buildModelsMap_=function(){this.logger_.info("Building models map...");for(var a=this.models_.length-1;a>=0;a--){var b=this.models_[a];this.modelsMap_[b.id]=b}};
rhizo.Project.prototype.initializeRenderings_=function(){for(var a=[],b=0;b<this.models_.length;b++)rhizo.ui.render(this.models_[b],this.renderer_,a,this.gui_.allRenderingHints());if(a.length==0){this.logger_.error("No renderings.");return false}if(typeof a[0]=="string"){this.gui_.universe.append(a.join(""));this.gui_.universe.find(".rhizo-model").each(jQuery.proxy(function(c,d){var e=this.models_[c];e.rendering=$(d);e.naked_render=e.rendering.children()},this))}else for(b=0;b<this.models_.length;b++){this.models_[b].rendering=
a[b];this.models_[b].naked_render=this.models_[b].rendering.children();a[b].appendTo(this.gui_.universe)}a=this.gui_.universe.find(".rhizo-model");if(a.length!=this.models_.length){this.logger_.error("The number of renderings and models differ: "+a.length+" vs "+this.models_.length);return false}rhizo.ui.decorateRendering(a,this.models_,this,this.renderer_,this.gui_.allRenderingHints());return true};
rhizo.Project.prototype.layout=function(a,b){var c=this.layoutEngines_[this.curLayoutName_],d=$.extend({},b,this.options_);if(a)this.curLayoutName_=a;var e=this.layoutEngines_[this.curLayoutName_];if(e){var f=false;if(c&&c.cleanup)f=c.cleanup(c==e,d)||f;this.logger_.info("laying out...");this.gui_.universe.move(0,0,{bottom:0,right:0});c=jQuery.grep(this.models_,function(g){return!g.isFiltered()});if((f=e.layout(this.gui_.universe,c,this.modelsMap_,this.metaModel_,d)||f)||d.forcealign)this.alignVisibility_()}else this.logger_.error("Invalid layout engine:"+
this.curLayoutName_)};
rhizo.Project.prototype.filter=function(a,b){this.metaModel_[a]||this.logger_.error("Invalid filtering key: "+a);if(b!="")for(var c=this.models_.length-1;c>=0;c--){var d=this.models_[c];this.metaModel_[a].kind.survivesFilter(b,d.unwrap()[a])?d.resetFilter(a):d.filter(a)}else this.resetAllFilter(a);this.alignFx();if(this.filterAutocommit_)this.commitFilter();else{d=false;for(c=this.models_.length-1;c>=0;c--)if(!this.models_[c].isFiltered()&&this.models_[c].visibility==rhizo.ui.Visibility.HIDDEN){d=true;
break}d?this.commitFilter():this.alignVisibility_(rhizo.ui.Visibility.GREY)}};rhizo.Project.prototype.commitFilter=function(){this.layout(null,{filter:true,forcealign:true})};rhizo.Project.prototype.alignFx=function(){for(var a=0,b=0,c=this.models_.length-1;c>=0;c--){this.models_[c].isFiltered()||a++;this.models_[c].visibility>=rhizo.ui.Visibility.GREY&&b++}this.gui_.disableFx(this.options_.noAnims||a>200||b>200)};
rhizo.Project.prototype.alignVisibility_=function(a){var b=rhizo.ui.Visibility;a=a||b.HIDDEN;for(var c=false,d=[],e=[],f=this.models_.length-1;f>=0;f--)if(this.models_[f].isFiltered()){if(this.models_[f].visibility>a){d.push(this.models_[f].rendering.get(0));this.models_[f].visibility=a}}else if(this.models_[f].visibility<=a){c=c||this.models_[f].visibility==b.HIDDEN;e.push(this.models_[f].rendering.get(0));this.models_[f].visibility=b.VISIBLE}$(d).fadeTo(a);$(e).fadeTo(b.VISIBLE);return c};
rhizo.layout.TreeLayout=function(a){this.project_=a;this.metaModelKeySelector_=this.directionSelector_=null;this.parentKeys_=[];this.globalNodesMap_=null};rhizo.layout.TreeLayout.prototype.verifyMetaModel=function(a){for(var b in a)a[b].isParent&&this.parentKeys_.push(b);return this.parentKeys_.length>0};
rhizo.layout.TreeLayout.prototype.layout=function(a,b,c){var d;if(this.parentKeys_.length==0){this.project_.logger().error("Unable to identify parent-child relationships");return false}else d=this.parentKeys_.length==1?this.parentKeys_[0]:this.metaModelKeySelector_.val();this.project_.logger().info("Creating tree by "+d);var e=this.directionSelector_.val()=="ver";this.treePainter_=new rhizo.layout.TreePainter(e);try{this.globalNodesMap_={};var f=(new rhizo.layout.Treeifier(d)).buildTree(b,c,this.globalNodesMap_).childs;
b={left:0,top:0};c=0;for(var g in f){var h=this.treePainter_.toAbsoluteCoords_(this.treePainter_.calculateBoundingRect_(f[g]));if(b.left+h.w>a.width()){b.left=0;b.top+=c+(c>0?5:0)}this.treePainter_.draw_(a,f[g],this.treePainter_.toRelativeCoords_(b));b.left+=h.w;c=Math.max(c,h.h)}}catch(i){if(i.name=="TreeCycleException")this.project_.logger().error(i);else throw i;}return false};
rhizo.layout.TreeLayout.prototype.details=function(){var a=$("<div />");if(this.parentKeys_.length==0){a.append("No parent-child relationships exist");return a}a.append(" arrange ");this.directionSelector_=$("<select class='rhizo-treelayout-direction' />");this.directionSelector_.append("<option value='hor'>Horizontally</option>");this.directionSelector_.append("<option value='ver'>Vertically</option>");a.append(this.directionSelector_);if(this.parentKeys_.length>1){this.metaModelKeySelector_=rhizo.layout.metaModelKeySelector(this.project_,
"rhizo-treelayout-parentKey",function(b,c){return!!c.isParent});a.append(" by ").append(this.metaModelKeySelector_)}return a};rhizo.layout.TreeLayout.prototype.toString=function(){return"Tree"};rhizo.layout.TreeLayout.prototype.cleanup=function(){this.treePainter_&&this.treePainter_.cleanup_();return false};rhizo.layout.TreeLayout.prototype.dependentModels=function(a){var b=[];if(a=this.globalNodesMap_[a]){a.deepChildsAsArray(b);for(a=b.length-1;a>=0;a--)b[a]=b[a].id}return b};
rhizo.layout.TreePainter=function(a){this.connectors_=[];if(this.vertical_=a){this.gdName_="top";this.odName_="left";this.gdLength_="height";this.odLength_="width"}else{this.gdName_="left";this.odName_="top";this.gdLength_="width";this.odLength_="height"}};rhizo.layout.TreePainter.prototype.gd_=function(a){return this.vertical_?a.height:a.width};rhizo.layout.TreePainter.prototype.od_=function(a){return this.vertical_?a.width:a.height};
rhizo.layout.TreePainter.prototype.toAbsoluteCoords_=function(a){return this.vertical_?{w:a.od,h:a.gd}:{w:a.gd,h:a.od}};rhizo.layout.TreePainter.prototype.toRelativeCoords_=function(a){return this.vertical_?{gd:a.top,od:a.left}:{gd:a.left,od:a.top}};rhizo.layout.TreePainter.prototype.packedCenter_=function(a,b){return{gd:a.gd+5+this.gd_(b)/2,od:a.od+this.od_(b)/2}};rhizo.layout.TreePainter.prototype.evenCenter_=function(a,b,c){return{gd:a.gd+c.gd/2,od:a.od+5+this.od_(b)/2}};
rhizo.layout.TreePainter.prototype.calculateBoundingRect_=function(a){var b={gd:0,od:0};for(var c in a.childs){var d=this.calculateBoundingRect_(a.childs[c]);b.gd+=d.gd+5;b.od=Math.max(b.od,d.od)}c=a.superModel.getDimensions();a.boundingRect={od:this.od_(c)+b.od+25,gd:Math.max(this.gd_(c),b.gd)+5};return a.boundingRect};
rhizo.layout.TreePainter.prototype.draw_=function(a,b,c,d,e){var f=b.superModel.rendering,g=b.superModel.getDimensions();if(this.vertical_){f.move(c.gd+5,c.od);d!=null&&this.drawConnector_(a,this.packedCenter_(c,g),this.packedCenter_(d,e.superModel.getDimensions()))}else{f.move(c.od+5,c.gd+(b.boundingRect.gd-this.gd_(g))/2);d!=null&&this.drawConnector_(a,this.evenCenter_(c,g,b.boundingRect),this.evenCenter_(d,e.superModel.getDimensions(),e.boundingRect))}d=c.gd;for(var h in b.childs){e=b.childs[h];
f={od:c.od+this.od_(g)+20,gd:d};this.draw_(a,e,f,c,b);d+=e.boundingRect.gd+5}};
rhizo.layout.TreePainter.prototype.drawConnector_=function(a,b,c){var d={position:"absolute"};d[this.gdName_]=Math.min(b.gd,c.gd);d[this.odName_]=c.od;d[this.odLength_]=2;d[this.gdLength_]=Math.abs(c.gd-b.gd);d=$("<div />",{"class":"rhizo-tree-connector",css:d});var e={position:"absolute"};e[this.gdName_]=b.gd;e[this.odName_]=c.od;e[this.gdLength_]=2;e[this.odLength_]=Math.abs(c.od-b.od);b=$("<div />",{"class":"rhizo-tree-connector",css:e});this.connectors_.push(d);this.connectors_.push(b);a.append(d);
a.append(b)};rhizo.layout.TreePainter.prototype.cleanup_=function(){$.each(this.connectors_,function(){this.remove()});this.connectors_=[]};rhizo.layout.layouts.tree=rhizo.layout.TreeLayout;namespace("rhizo.ui.component");rhizo.ui.component.Progress=function(a){this.pbarPanel_=$("<div/>",{"class":"rhizo-progressbar-panel"}).appendTo(a);this.pbar_=$("<div/>",{"class":"rhizo-progressbar"}).appendTo(this.pbarPanel_).progressbar({value:1});this.pbarText_=$("<div/>",{"class":"rhizo-progressbar-text"}).text("Loading...").appendTo(this.pbarPanel_)};
rhizo.ui.component.Progress.prototype.update=function(a,b){this.pbar_.progressbar("value",a);b&&this.pbarText_.text(b);a>=100&&this.destroy_()};rhizo.ui.component.Progress.prototype.destroy_=function(){this.pbarPanel_.is(":visible")?setTimeout(jQuery.proxy(function(){this.pbarPanel_.fadeOut(500,function(){$(this).remove()})},this),1E3):this.pbarPanel_.remove()};rhizo.ui.component.Logo=function(a){this.floating_=a};rhizo.ui.component.Logo.prototype.getPanel=function(){return this.logoPanel_};
rhizo.ui.component.Logo.prototype.render=function(a,b){b.addComponent("rhizo.ui.component.Logo",this);this.logoPanel_=$("<div />",{"class":"rhizo-logo"}).html('<h1>Rhizosphere</h1><p>by <a href="mailto:battlehorse@gmail.com">Riccardo Govoni</a> (c) 2010<br /><a href="http://sites.google.com/site/rhizosphereui/" target="_blank">Project info</a>&nbsp;<a href="http://sites.google.com/site/rhizosphereui/Home/documentation" target="_blank" style="font-weight:bold; text-decoration: underline">I Need Help!</a></p>').appendTo(a);
this.floating_&&this.logoPanel_.addClass("rhizo-floating-panel").css("display","none")};rhizo.ui.component.Viewport=function(){};rhizo.ui.component.Viewport.prototype.render=function(a,b){this.viewport_=$("<div/>",{"class":"rhizo-viewport"}).appendTo(a);this.universe_=$("<div/>",{"class":"rhizo-universe"}).appendTo(this.viewport_);b.setViewport(this.viewport_);b.setUniverse(this.universe_)};
rhizo.ui.component.Viewport.prototype.activate=function(a){a.viewport.draggable({helper:function(){return $("<div />").appendTo(a.viewport)},start:function(){var b=a.universe.position();a.universe.data("top0",b.top).data("left0",b.left)},drag:function(b,c){var d=c.position.top+a.universe.data("top0"),e=c.position.left+a.universe.data("left0");if(Math.abs(c.position.left)<=15)e=a.universe.data("left0");if(Math.abs(e)<=15)e=0;a.moveUniverse({top:d,left:e})},refreshPositions:false});$(a.viewport).mousewheel(function(b,
c,d){a.panUniverse(d,c,b.timeStamp)})};rhizo.ui.component.BottomBar=function(){};
rhizo.ui.component.BottomBar.prototype.render=function(a,b,c){c.addComponent("rhizo.ui.component.BottomBar",this);this.resizeLink_=$("<a/>",{"class":"rhizo-maximize-icon",href:"javascript:;",title:"Maximize"}).appendTo(a);this.components_=[{component:"rhizo.ui.component.Layout",title:"Display","class":""},{component:"rhizo.ui.component.SelectionManager",title:"Selection","class":"",callback:function(d,e){d.isSelectionModeOn()!=e&&d.toggleSelectionMode()}},{component:"rhizo.ui.component.Filters",title:"Filters",
"class":""},{component:"rhizo.ui.component.Legend",title:"Legend","class":""},{component:"rhizo.ui.component.Logo",title:"?","class":"rhizo-link-help"}];this.components_=jQuery.grep(this.components_,function(d){return c.getComponent(d.component)?true:false});for(b=0;b<this.components_.length;b++){this.components_[b].clickable=this.createLink_(this.components_[b].title,this.components_[b]["class"],a);this.components_[b].panel=c.getComponent(this.components_[b].component).getPanel()}};
rhizo.ui.component.BottomBar.prototype.createLink_=function(a,b,c){c=$("<div />",{"class":"rhizo-section-header"}).appendTo(c);$("<a/>",{href:"javascript:;",title:a,"class":b}).text(a).appendTo(c);return c};
rhizo.ui.component.BottomBar.prototype.activate=function(a,b){this.resizeLink_.click(function(){self.resizeTo(1E3,700);self.location.reload();return false});jQuery.each(this.components_,jQuery.proxy(function(c,d){d.clickable.click(jQuery.proxy(function(){jQuery.each(this.components_,function(e,f){if(f==d){$(f.panel).toggle();$(f.clickable).toggleClass("rhizo-section-open")}else{$(f.panel).css("display","none");$(f.clickable).removeClass("rhizo-section-open")}f.callback&&f.callback(b,$(f.clickable).hasClass("rhizo-section-open"))});
return false},this))},this))};rhizo.ui.component.BottomBar.prototype.toggleComponent=function(a,b){for(var c=0;c<this.components_.length;c++)if(this.components_[c].component==a){this.components_[c].clickable.hasClass("rhizo-section-open")!=b&&this.components_[c].clickable.click();break}};rhizo.ui.component.Console=function(){};
rhizo.ui.component.Console.prototype.render=function(a,b){b.addComponent("rhizo.ui.component.Console",this);this.toggleButton_=$("<div />",{"class":"rhizo-console-close"}).html("&#8659;");this.consoleHeader_=$("<div />",{"class":"rhizo-console-header"});this.consoleHeader_.append(this.toggleButton_).append("Log Console");this.consoleHeader_.appendTo(a);this.consoleContents_=$("<div />",{"class":"rhizo-console-contents"});this.consoleContents_.appendTo(a)};
rhizo.ui.component.Console.prototype.activate=function(){this.toggleButton_.click(jQuery.proxy(function(){this.consoleContents_.is(":visible")?this.consoleContents_.slideUp("slow",jQuery.proxy(function(){this.toggleButton_.html("&#8659;");this.consoleContents_.empty()},this)):this.consoleContents_.slideDown("slow",jQuery.proxy(function(){this.toggleButton_.html("&#8657;")},this))},this))};rhizo.ui.component.Console.prototype.getContents=function(){return this.consoleContents_};
rhizo.ui.component.Console.prototype.getHeader=function(){return this.consoleHeader_};rhizo.ui.component.RightBar=function(){};rhizo.ui.component.RightBar.prototype.render=function(a,b){b.addComponent("rhizo.ui.component.RightBar",this);this.toggle_=$("<div />",{"class":"rhizo-right-pop"}).html("&#x25c2;").appendTo(a);this.rightBar_=$("<div />",{"class":"rhizo-right"}).css("display","none").appendTo(a)};
rhizo.ui.component.RightBar.prototype.activate=function(a){this.toggle_.click(jQuery.proxy(function(){if(this.rightBar_.is(":visible")){this.toggle_.css("right",0).html("&#x25c2;");a.viewport.css("right",5);this.rightBar_.css("display","none")}else{a.viewport.css("right",135);this.toggle_.css("right",130).html("&#x25b8;");this.rightBar_.css("display","")}},this))};rhizo.ui.component.RightBar.prototype.getToggle=function(){return this.toggle_};rhizo.ui.component.RightBar.prototype.getPanel=function(){return this.rightBar_};
rhizo.ui.component.Layout=function(a){this.floating_=a};rhizo.ui.component.Layout.prototype.getPanel=function(){return this.layoutPanel_};
rhizo.ui.component.Layout.prototype.render=function(a,b,c){c.addComponent("rhizo.ui.component.Layout",this);this.floating_||$("<div />",{"class":"rhizo-section-header"}).text("Display").appendTo(a);this.layoutPanel_=$("<div />").appendTo(a);this.layoutOptions_=$("<div />",{"class":"rhizo-layout-extra-options"}).appendTo(this.layoutPanel_);this.floating_&&this.layoutPanel_.addClass("rhizo-floating-panel").css("display","none");this.layoutSelector_=$("<select />");this.detailsMap_={};a=b.layoutEngines();
for(var d in a){c=a[d];this.layoutSelector_.append($("<option value='"+d+"' "+(b.currentLayoutEngineName()==d?"selected":"")+">"+c+"</option>"));if(c.details){c=c.details();this.detailsMap_[d]=c;b.currentLayoutEngineName()!=d&&c.css("display","none");this.layoutOptions_.append(c)}}this.submit_=$("<button />").text("Update");this.layoutPanel_.prepend(this.submit_).prepend(this.layoutSelector_).prepend("Keep items ordered by: ")};
rhizo.ui.component.Layout.prototype.activate=function(a){var b=this.detailsMap_;this.layoutSelector_.change(function(){for(var c in b)c==$(this).val()?b[c].show("fast"):b[c].hide("fast")});this.submit_.click(jQuery.proxy(function(){a.layout(this.layoutSelector_.val(),{forcealign:true})},this))};rhizo.ui.component.SelectionManager=function(a){this.floating_=a};rhizo.ui.component.SelectionManager.prototype.getPanel=function(){return this.selectionPanel_};
rhizo.ui.component.SelectionManager.prototype.render=function(a,b,c){c.addComponent("rhizo.ui.component.SelectionManager",this);this.floating_||$("<div />",{"class":"rhizo-section-header"}).text("Selection").appendTo(a);this.selectionPanel_=$("<div />",{"class":"rhizo-selection"}).appendTo(a);this.floating_&&this.selectionPanel_.addClass("rhizo-floating-panel").css("display","none");this.selection_trigger_=$("<div />",{"class":"rhizo-selection-trigger",title:"Start selecting items"}).appendTo(c.viewport);
this.selectButton_=$("<button />").text("Work on selected items only");this.resetButton_=$("<button />",{disabled:"disabled"}).text("Reset");this.selectionPanel_.append(this.selectButton_).append(this.resetButton_)};rhizo.ui.component.SelectionManager.prototype.activate=function(a,b,c){this.activateSelectableViewport_(a,b,c);this.activateButtons_(a,c)};
rhizo.ui.component.SelectionManager.prototype.activateButtons_=function(a){this.selectButton_.click(jQuery.proxy(function(){var b=0;for(var c in a.allSelected())b++;if(b==0)a.logger().error("No items selected");else{b=a.allUnselected();var d=0;for(c in b){b[c].filter("__selection__");d++}a.alignFx();a.layout(null,{filter:true,forcealign:true});a.unselectAll();this.resetButton_.removeAttr("disabled").text("Reset ("+d+" filtered)")}},this));this.resetButton_.click(function(){a.resetAllFilter("__selection__");
a.alignFx();a.layout(null,{filter:true,forcealign:true});$(this).attr("disabled","disabled").text("Reset")})};rhizo.ui.component.SelectionManager.prototype.isOnEmptySpace_=function(a){return $(a.target).hasClass("rhizo-viewport")||$(a.target).hasClass("rhizo-universe")};
rhizo.ui.component.SelectionManager.prototype.activateSelectableViewport_=function(a,b,c){this.selection_trigger_.click(function(){a.gui().toggleSelectionMode()});b.viewport.selectable({disabled:true,selected:function(d,e){var f=$(e.selected).data("id");f&&a.select(f)},unselected:function(d,e){var f=$(e.unselected).data("id");f&&a.unselect(f)},filter:c.selectfilter,tolerance:"touch",distance:1});b.viewport.click(jQuery.proxy(function(d){this.isOnEmptySpace_(d)&&a.unselectAll()},this))};
rhizo.ui.component.SelectionManager.prototype.toggleSelectionTrigger=function(a){this.selection_trigger_.attr("title",a?"Stop selecting items":"Start selecting items")};rhizo.ui.component.Filters=function(a){this.floating_=a};rhizo.ui.component.Filters.prototype.getPanel=function(){return this.filterPanel_};
rhizo.ui.component.Filters.prototype.render=function(a,b,c){c.addComponent("rhizo.ui.component.Filters",this);this.floating_||$("<div />",{"class":"rhizo-section-header"}).text("Filters").appendTo(a);this.filterPanel_=$("<div />",{"class":"rhizo-filter-container"}).appendTo(a);this.hideLink_=this.prevFilter_=this.nextFilter_=null;if(this.floating_){this.filterPanel_.addClass("rhizo-floating-panel").css("display","none");this.nextFilter_=$("<div />",{"class":"rhizo-next-filter",title:"Next filter"}).text(">").appendTo(this.filterPanel_);
this.prevFilter_=$("<div />",{"class":"rhizo-prev-filter",title:"Previous filter"}).text("<").appendTo(this.filterPanel_);this.hideLink_=$("<a />",{href:"#","class":"rhizo-autocommit-link"}).text("Apply").appendTo(this.filterPanel_);b.isFilterAutocommit()&&this.hideLink_.css("display","none")}a=$("<div />",{"class":"rhizo-filter rhizo-autocommit-panel"}).appendTo(this.filterPanel_);this.autocommit_=$("<input />",{type:"checkbox",checked:b.isFilterAutocommit()}).appendTo(a);$("<span>Autocommit</span>").appendTo(a);
this.hideButton_=$("<button />",{disabled:b.isFilterAutocommit()}).text("Apply filters").appendTo(a);a=b.metaModel();for(key in a){c=a[key].kind.renderFilter(b,a[key],key);this.floating_&&c.css("display","none");this.filterPanel_.append(c)}};
rhizo.ui.component.Filters.prototype.activate=function(a,b){this.nextFilter_&&this.nextFilter_.click(function(){var c=$(".rhizo-filter:visible",b.container),d=c.next(".rhizo-filter:hidden").eq(0);if(d.length>0){c.css("display","none");d.css("display","")}});this.prevFilter_&&this.prevFilter_.click(function(){var c=$(".rhizo-filter:visible",b.container),d=c.prev(".rhizo-filter:hidden").eq(0);if(d.length>0){c.css("display","none");d.css("display","")}});this.autocommit_.click(jQuery.proxy(function(c){if(c=
$(c.target).is(":checked")){this.hideButton_.attr("disabled","disabled");this.hideLink_&&this.hideLink_.css("display","none")}else{this.hideButton_.removeAttr("disabled");this.hideLink_&&this.hideLink_.css("display","")}a.enableFilterAutocommit(c)},this));this.hideButton_.click(function(){a.commitFilter()});this.hideLink_&&this.hideLink_.click(function(){a.commitFilter()})};rhizo.ui.component.Legend=function(a){this.floating_=a};rhizo.ui.component.Legend.prototype.getPanel=function(){return this.legendPanel_};
rhizo.ui.component.Legend.prototype.render=function(a,b,c){c.addComponent("rhizo.ui.component.Legend",this);var d=null;if(b.renderer().getSizeRange)d=b.renderer().getSizeRange();c=null;if(b.renderer().getColorRange)c=b.renderer().getColorRange();this.floating_||$("<div />",{"class":"rhizo-section-header"}).text("Legend").appendTo(a);this.legendPanel_=$("<div />",{"class":"rhizo-legend-panel"}).appendTo(a);this.floating_&&this.legendPanel_.addClass("rhizo-floating-panel").css("display","none");if(d){a=
$("<div />",{"class":"rhizo-legend-size"});b=$("<span />",{"class":"rhizo-legend-size-min"}).html(d.label+" &nbsp; "+rhizo.ui.toHumanLabel(d.min)+":");d=$("<span />",{"class":"rhizo-legend-size-max"}).html(": "+rhizo.ui.toHumanLabel(d.max));a.append(b).append('<span class="ar-fon-0">A</span> -- <span class="ar-fon-5">A</span>').append(d).appendTo(this.legendPanel_)}if(c){a=$("<div />",{"class":"rhizo-legend-color"});b=$("<span />",{"class":"rhizo-legend-color-min"}).html(c.label+" &nbsp; "+rhizo.ui.toHumanLabel(c.min)+
":");d=$("<span />",{"class":"rhizo-legend-color-max"}).html(": "+rhizo.ui.toHumanLabel(c.max));a.append(b).append('<span class="ar-col-0 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-1 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-2 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-3 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-4 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-5 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;').append(d).appendTo(this.legendPanel_)}};
rhizo.ui.component.Legend.prototype.activate=function(){};rhizo.ui.component.Actions=function(){};rhizo.ui.component.Actions.prototype.render=function(a){a=$("<div />",{"class":"rhizo-actions"}).append($("<div />",{"class":"rhizo-section-header"}).text("Actions")).appendTo(a);for(var b=0;b<2;b++)$("<div />",{"class":"rhizo-action"}).text("Sample Action "+(b+1)).appendTo(a)};
rhizo.ui.component.Actions.prototype.activate=function(a,b){if($(".rhizo-action").length>0){$(".rhizo-action").draggable({helper:"clone"});b.universe.droppable({accept:".rhizo-action",drop:function(c,d){var e=b.universe.offset(),f=b.universe.width(),g=b.universe.height(),h=d.draggable.text(),i=d.offset.left-e.left;if(i+200>f)i=f-210;e=d.offset.top-e.top;if(e+200>g)e=g-210;var j=$("<div class='rhizo-droppable-action'>Drop your items here to perform:<br />"+h+"</div>").css({top:e,left:i});b.universe.append(j);
j.fadeIn();j.draggable();j.droppable({accept:".rhizo-model",drop:function(o,m){var l=m.draggable.data("id");if(a.isSelected(l)){var k=0,n=a.allSelected();for(l in n)k++;alert("Action applied on "+k+" elements");for(l in n)n[l].rendering.move(n[l].rendering.data("dropTop0"),n[l].rendering.data("dropLeft0"));a.unselectAll()}else{alert("Action applied on "+a.model(l));m.draggable.move(m.draggable.data("dropTop0"),m.draggable.data("dropLeft0"))}}});j.dblclick(function(){j.remove();return false})}})}};
rhizo.ui.component.BottomTemplate=function(a){this.project_=a;this.gui_=a.gui();this.components_={LOGO:new rhizo.ui.component.Logo(true),VIEWPORT:new rhizo.ui.component.Viewport,LAYOUT:new rhizo.ui.component.Layout(true),SELECTION_MANAGER:new rhizo.ui.component.SelectionManager(true),FILTERS:new rhizo.ui.component.Filters(true),LEGEND:new rhizo.ui.component.Legend(true),BOTTOMBAR:new rhizo.ui.component.BottomBar}};
rhizo.ui.component.BottomTemplate.prototype.renderChrome=function(a){this.gui_.container.addClass("rhizo-template-bottom");this.components_.VIEWPORT.render(this.gui_.container,this.gui_,a);this.progress_=new rhizo.ui.component.Progress(this.gui_.viewport);this.progress_.update(10,"Creating static UI...");this.bottomBar_=$("<div />",{"class":"rhizo-bottom-bar"}).appendTo(this.gui_.container);this.components_.LOGO.render(this.bottomBar_,this.gui_,a);this.progress_.update(25,"All static UI created.")};
rhizo.ui.component.BottomTemplate.prototype.activateChrome=function(a){this.progress_.update(26,"Activating static UI...");this.components_.VIEWPORT.activate(this.gui_,a);this.progress_.update(33,"Loading models...")};
rhizo.ui.component.BottomTemplate.prototype.renderDynamic=function(a){this.progress_.update(34,"Creating dynamic controls...");this.components_.LAYOUT.render(this.bottomBar_,this.project_,this.gui_,a);this.progress_.update(36,"Layout engine created.");this.components_.SELECTION_MANAGER.render(this.bottomBar_,this.project_,this.gui_,a);this.progress_.update(40,"Selection manager created.");this.components_.FILTERS.render(this.bottomBar_,this.project_,this.gui_,a);this.progress_.update(44,"Filters created.");
if(this.project_.renderer().getSizeRange||this.project_.renderer().getColorRange){this.components_.LEGEND.render(this.bottomBar_,this.project_,this.gui_,a);this.progress_.update(46,"Legend created.")}this.components_.BOTTOMBAR.render(this.bottomBar_,this.project_,this.gui_,a);this.progress_.update(48,"Toolbar created.")};
rhizo.ui.component.BottomTemplate.prototype.activateDynamic=function(a){this.progress_.update(51,"Activating dynamic controls...");this.components_.LAYOUT.activate(this.project_,this.gui_,a);this.components_.SELECTION_MANAGER.activate(this.project_,this.gui_,a);this.components_.FILTERS.activate(this.project_,this.gui_,a);this.components_.LEGEND.activate(this.project_,this.gui_,a);this.components_.BOTTOMBAR.activate(this.project_,this.gui_,a);this.progress_.update(66,"Rhizosphere controls are ready.")};
rhizo.ui.component.BottomTemplate.prototype.done=function(){this.progress_.update(100,"Rhizosphere ready!")};
rhizo.ui.component.StandardTemplate=function(a){this.project_=a;this.gui_=a.gui();this.components_={LOGO:new rhizo.ui.component.Logo(false),VIEWPORT:new rhizo.ui.component.Viewport,RIGHTBAR:new rhizo.ui.component.RightBar,CONSOLE:new rhizo.ui.component.Console,LAYOUT:new rhizo.ui.component.Layout(false),SELECTION_MANAGER:new rhizo.ui.component.SelectionManager(false),FILTERS:new rhizo.ui.component.Filters(false),LEGEND:new rhizo.ui.component.Legend(false),ACTIONS:new rhizo.ui.component.Actions}};
rhizo.ui.component.StandardTemplate.prototype.renderChrome=function(a){this.gui_.container.addClass("rhizo-template-default");this.components_.VIEWPORT.render(this.gui_.container,this.gui_,a);this.progress_=new rhizo.ui.component.Progress(this.gui_.viewport);this.leftBar_=$("<div/>",{"class":"rhizo-left"}).appendTo(this.gui_.container);this.components_.RIGHTBAR.render(this.gui_.container,this.gui_,a);this.progress_.update(10,"Creating static UI...");this.components_.LOGO.render(this.leftBar_,this.gui_,
a);this.components_.CONSOLE.render(this.components_.RIGHTBAR.getPanel(),this.gui_,a);this.progress_.update(25,"All static UI created.")};rhizo.ui.component.StandardTemplate.prototype.activateChrome=function(a){this.progress_.update(26,"Activating static UI...");this.components_.RIGHTBAR.activate(this.gui_,a);this.components_.CONSOLE.activate(this.gui_,a);this.components_.VIEWPORT.activate(this.gui_,a);this.progress_.update(33,"Loading models...")};
rhizo.ui.component.StandardTemplate.prototype.renderDynamic=function(a){this.progress_.update(34,"Creating dynamic controls...");this.components_.LAYOUT.render(this.leftBar_,this.project_,this.gui_,a);this.progress_.update(38,"Layout engine created.");this.components_.SELECTION_MANAGER.render(this.leftBar_,this.project_,this.gui_,a);this.progress_.update(42,"Selection manager created.");this.components_.FILTERS.render(this.leftBar_,this.project_,this.gui_,a);this.progress_.update(46,"Filters created.");
if(this.project_.renderer().getSizeRange||this.project_.renderer().getColorRange){this.components_.LEGEND.render(this.leftBar_,this.project_,this.gui_,a);this.progress_.update(48,"Legend created.")}this.components_.ACTIONS.render(this.components_.RIGHTBAR.getPanel(),this.project_,this.gui_,a);this.progress_.update(50,"Actions created")};
rhizo.ui.component.StandardTemplate.prototype.activateDynamic=function(a){this.progress_.update(51,"Activating dynamic controls...");this.components_.LAYOUT.activate(this.project_,this.gui_,a);this.components_.SELECTION_MANAGER.activate(this.project_,this.gui_,a);this.components_.FILTERS.activate(this.project_,this.gui_,a);this.components_.LEGEND.activate(this.project_,this.gui_,a);this.components_.ACTIONS.activate(this.project_,this.gui_,a);this.progress_.update(66,"Rhizosphere controls are ready.")};
rhizo.ui.component.StandardTemplate.prototype.done=function(){this.progress_.update(100,"Rhizosphere ready!")};namespace("rhizo.layout");namespace("rhizo.layout.treemap");rhizo.layout.treemap.TreeMapDirection={HOR:"h",VER:"v"};rhizo.layout.treemap.ModelBackupManager=function(){this.modelBackups_={};this.numBackups_=0};
rhizo.layout.treemap.ModelBackupManager.prototype.backup=function(a){if(!(a.id in this.modelBackups_)){this.modelBackups_[a.id]=new rhizo.layout.treemap.ModelBackup(a);this.numBackups_++;return true}return false};rhizo.layout.treemap.ModelBackupManager.prototype.removeBackup=function(a){if(a in this.modelBackups_){delete this.modelBackups_[a];this.numBackups_--}};
rhizo.layout.treemap.ModelBackupManager.prototype.restore=function(a,b){if(this.numBackups_>0){for(var c={},d=0;d<a.length;d++)c[a[d].id]=true;d={};for(var e in this.modelBackups_)e in c||(d[e]=true);this.restoreInternal_(d,true,true);b&&this.restoreInternal_(this.modelBackups_,false,true)}};rhizo.layout.treemap.ModelBackupManager.prototype.restoreAll=function(){this.restoreInternal_(this.modelBackups_,true,true);this.modelBackups_={};this.numBackups_=0};
rhizo.layout.treemap.ModelBackupManager.prototype.restoreInternal_=function(a,b,c){for(var d in a){this.modelBackups_[d].restore(b,c);if(b&&c){delete this.modelBackups_[d];this.numBackups_--}}};rhizo.layout.treemap.ModelBackup=function(a){this.model_=a;this.originalDimensions_=jQuery.extend({},a.getDimensions());this.originalBackground_=a.nakedCss("background-color")};
rhizo.layout.treemap.ModelBackup.prototype.restore=function(a,b){b&&this.model_.setNakedCss({backgroundColor:this.originalBackground_});if(a){this.model_.rescaleRendering(this.originalDimensions_.width,this.originalDimensions_.height);this.model_.rendering.css("z-index","")}};rhizo.layout.treemap.TreeMapNode=function(a,b){this.model_=a.superModel;this.area_=a.area*b;if(isNaN(this.area_)||this.area_<0)this.area_=0;this.left_=this.top_=0};rhizo.layout.treemap.TreeMapNode.prototype.area=function(){return this.area_};
rhizo.layout.treemap.TreeMapNode.prototype.position=function(){return{top:this.top_,left:this.left_}};rhizo.layout.treemap.TreeMapNode.prototype.model=function(){return this.model_};rhizo.layout.treemap.TreeMapNode.prototype.isHidden=function(){return this.model_.isFiltered("__treemap__")};rhizo.layout.treemap.TreeMapNode.prototype.hide=function(){this.model_.filter("__treemap__")};
rhizo.layout.treemap.TreeMapNode.prototype.move=function(a,b,c){this.top_=Math.round(a);this.left_=Math.round(b);this.model_.rendering.move(this.top_,this.left_);this.model_.rendering.css("z-index",50+c)};rhizo.layout.treemap.TreeMapNode.prototype.resize=function(a,b){return this.model_.rescaleRendering(a,b)};
rhizo.layout.treemap.TreeMapNode.prototype.colorWeighted=function(a){var b=parseFloat(this.model_.unwrap()[a.meta]);isNaN(b)||this.model_.setNakedCss({backgroundColor:this.getBackgroundColor_(b,a)})};rhizo.layout.treemap.TreeMapNode.prototype.color=function(a){this.model_.setNakedCss({backgroundColor:a})};rhizo.layout.treemap.TreeMapNode.prototype.assignColorRange=function(a){var b=parseFloat(this.model_.unwrap()[a.meta]);if(!isNaN(b)){a.min=Math.min(a.min,b);a.max=Math.max(a.max,b)}};
rhizo.layout.treemap.TreeMapNode.prototype.nestedBoundingRect=function(){var a=this.model_.getDimensions();return this.isHidden()||a.width<24||a.height<39?{width:0,height:0}:{width:a.width-4,height:a.height-19}};rhizo.layout.treemap.TreeMapNode.prototype.nestedAnchor=function(){return{x:this.left_+2,y:this.top_+17}};
rhizo.layout.treemap.TreeMapNode.prototype.getBackgroundColor_=function(a,b){for(var c=["r","g","b"],d={},e=0;e<c.length;e++){var f=c[e];d[f]=b.colorMin[f]+(b.colorMax[f]-b.colorMin[f])*(a-b.min)/(b.max-b.min)}return"rgb("+Math.round(d.r)+","+Math.round(d.g)+","+Math.round(d.b)+")"};rhizo.layout.treemap.TreeMapSlice=function(a,b,c){this.length_=a;this.direction_=b;this.anchorPoint_=c;this.nodes_=[];this.sliceArea_=0;this.minArea_=Number.MAX_VALUE};
rhizo.layout.treemap.TreeMapSlice.prototype.direction=function(){return this.direction_};rhizo.layout.treemap.TreeMapSlice.prototype.anchorPoint=function(){return this.anchorPoint_};rhizo.layout.treemap.TreeMapSlice.prototype.nodes=function(){return this.nodes_};rhizo.layout.treemap.TreeMapSlice.prototype.addNode=function(a){this.nodes_.push(a);this.sliceArea_+=a.area();this.minArea_=Math.min(this.minArea_,a.area())};
rhizo.layout.treemap.TreeMapSlice.prototype.span=function(a){return a?(this.sliceArea_+a.area())/this.length_:this.sliceArea_/this.length_};rhizo.layout.treemap.TreeMapSlice.prototype.aspectRatio=function(a){var b=this.span(a),c=null;c=a?Math.min(this.minArea_,a.area())/(1*b*b):this.minArea_/(1*b*b);if(c<1)c=1/c;return c};
rhizo.layout.treemap.TreeMapSlice.prototype.draw=function(a,b,c){b=b||{x:0,y:0};var d=0,e=this.anchorPoint_.y+b.y;b=this.anchorPoint_.x+b.x;for(var f=0;f<this.nodes_.length;f++){var g=this.nodes_[f];if(g.isHidden())d++;else{var h=Math.round(this.span()),i=g.area()/this.span();if(Math.round(i)==0||h==0){g.hide();d++}else{var j={};if(this.direction_==rhizo.layout.treemap.TreeMapDirection.HOR){j.width=Math.round(i);j.height=h}else{j.width=h;j.height=Math.round(i)}h=a.backup(g.model());if(g.resize(j.width,
j.height))g.move(e,b,c);else{g.hide();d++;h&&a.removeBackup(g.model().id)}}if(this.direction_==rhizo.layout.treemap.TreeMapDirection.HOR)b+=i;else e+=i}}return d};rhizo.layout.TreeMapLayout=function(a){this.project_=a;this.numericKeys_=[];this.parentKeySelector_=this.colorSelector_=this.areaSelector_=null;this.parentKeys_=[];this.prevColorMeta_="";this.backupManager_=new rhizo.layout.treemap.ModelBackupManager;this.globalNodesMap_={};this.numHiddenModels_=0};
rhizo.layout.TreeMapLayout.prototype.verifyMetaModel=function(a){for(var b in a){a[b].isParent&&this.parentKeys_.push(b);a[b].kind.isNumeric()&&this.numericKeys_.push(b)}return this.numericKeys_.length>0};
rhizo.layout.TreeMapLayout.prototype.layout=function(a,b,c,d,e){d=this.areaSelector_.val();var f=this.colorSelector_.val(),g=this.parentKeySelector_?this.parentKeySelector_.val():"";this.backupManager_.restore(b,this.prevColorMeta_!=""&&f=="");this.prevColorMeta_=f;rhizo.ui.expandable(this.project_.renderer(),this.project_.gui().allRenderingHints())&&this.revertExpandedModels_(b,e);var h;this.globalNodesMap_={};if(g.length>0)try{h=(new rhizo.layout.Treeifier(g)).buildTree(b,c,this.globalNodesMap_)}catch(i){if(i.name==
"TreeCycleException"){this.project_.logger().error(i);return false}else throw i;}else{h=new rhizo.layout.TreeNode;for(c=0;c<b.length;c++)h.addChild(new rhizo.layout.TreeNode(b[c]))}this.computeNestedAreas_(h,d);this.numHiddenModels_=this.layoutNestedMap_({width:a.width(),height:a.height()},h,{x:0,y:0},0);if(f.length>0){a={min:Number.MAX_VALUE,max:Number.MIN_VALUE,meta:f,colorMin:{r:237,g:76,b:95},colorMax:{r:122,g:255,b:115},colorGroup:"transparent"};this.computeColorRange_(h,a);this.colorTree_(h,
a)}return this.numHiddenModels_>0};rhizo.layout.TreeMapLayout.prototype.cleanup=function(a){a||this.backupManager_.restoreAll();if(this.numHiddenModels_>0){this.project_.resetAllFilter("__treemap__");this.numHiddenModels_=0;return true}return false};
rhizo.layout.TreeMapLayout.prototype.details=function(){var a=$("<div />");this.areaSelector_=rhizo.layout.metaModelKeySelector(this.project_,"rhizo-treemaplayout-area",function(b,c){return c.kind.isNumeric()});this.colorSelector_=rhizo.layout.metaModelKeySelector(this.project_,"rhizo-treemaplayout-color",function(b,c){return c.kind.isNumeric()});this.colorSelector_.append("<option value='' selected>-</option>");a.append("Area: ").append(this.areaSelector_).append(" Color:").append(this.colorSelector_);
if(this.parentKeys_.length>0){this.parentKeySelector_=rhizo.layout.metaModelKeySelector(this.project_,"rhizo-treemaplayout-parentKey",function(b,c){return!!c.isParent});this.parentKeySelector_.append("<option value='' selected>-</option>");a.append(" Parent: ").append(this.parentKeySelector_)}return a};rhizo.layout.TreeMapLayout.prototype.dependentModels=function(a){var b=[];if(a=this.globalNodesMap_[a]){a.deepChildsAsArray(b);for(a=b.length-1;a>=0;a--)b[a]=b[a].id}return b};
rhizo.layout.TreeMapLayout.prototype.toString=function(){return"TreeMap"};rhizo.layout.TreeMapLayout.prototype.layoutNestedMap_=function(a,b,c,d){var e=0;if(b.numChilds==0)return e;a=this.layoutFlatMap_(a,b);for(var f=0;f<a.length;f++){e+=a[f].draw(this.backupManager_,c,d);for(var g=0;g<a[f].nodes().length;g++){var h=a[f].nodes()[g],i=b.childs[h.model().id];i.treemapnode=h;e+=this.layoutNestedMap_(h.nestedBoundingRect(),i,h.nestedAnchor(),d+1)}}return e};
rhizo.layout.TreeMapLayout.prototype.sortByAreaDesc_=function(a,b){return b.area-a.area};
rhizo.layout.TreeMapLayout.prototype.layoutFlatMap_=function(a,b){var c=[];if(b.numChilds==0)return c;for(var d=b.childsAsArray(),e=0,f=0;f<d.length;f++)e+=d[f].area;var g;if(e>0)g=a.width*a.height*1/e;a.width<a.height?c.push(new rhizo.layout.treemap.TreeMapSlice(a.width,rhizo.layout.treemap.TreeMapDirection.HOR,{x:0,y:0})):c.push(new rhizo.layout.treemap.TreeMapSlice(a.height,rhizo.layout.treemap.TreeMapDirection.VER,{x:0,y:0}));e=c[0];f=0;d.sort(this.sortByAreaDesc_);var h=new rhizo.layout.treemap.TreeMapNode(d[f++],
g);h.area()<=0&&h.hide();for(e.addNode(h);f<d.length;){h=new rhizo.layout.treemap.TreeMapNode(d[f++],g);if(h.area()<=0)h.hide();else{var i=e.aspectRatio(h),j=e.aspectRatio();if(i>j){a=this.getRemainderBoundingRect_(a,e);i=e.direction()==rhizo.layout.treemap.TreeMapDirection.HOR?a.height:a.width;e=e.direction()==rhizo.layout.treemap.TreeMapDirection.HOR?new rhizo.layout.treemap.TreeMapSlice(i,rhizo.layout.treemap.TreeMapDirection.VER,{x:e.anchorPoint().x,y:e.anchorPoint().y+e.span()}):new rhizo.layout.treemap.TreeMapSlice(i,
rhizo.layout.treemap.TreeMapDirection.HOR,{x:e.anchorPoint().x+e.span(),y:e.anchorPoint().y});c.push(e)}}e.addNode(h)}return c};rhizo.layout.TreeMapLayout.prototype.getRemainderBoundingRect_=function(a,b){var c=b.span();return b.direction()==rhizo.layout.treemap.TreeMapDirection.HOR?{width:a.width,height:a.height-c}:{width:a.width-c,height:a.height}};
rhizo.layout.TreeMapLayout.prototype.computeNestedAreas_=function(a,b){if(a.numChilds==0){a.area=parseFloat(a.superModel.unwrap()[b]);if(isNaN(a.area)||a.area<0)a.area=0}else{var c=0;for(var d in a.childs)c+=this.computeNestedAreas_(a.childs[d],b);a.area=c}return a.area};
rhizo.layout.TreeMapLayout.prototype.computeColorRange_=function(a,b){if(!a.is_root&&a.treemapnode.isHidden())return false;if(a.numChilds>0){var c=false;for(var d in a.childs)c=this.computeColorRange_(a.childs[d],b)||c;c||a.treemapnode.assignColorRange(b)}else a.is_root||a.treemapnode.assignColorRange(b);return true};
rhizo.layout.TreeMapLayout.prototype.colorTree_=function(a,b){if(!a.is_root&&a.treemapnode.isHidden())return false;if(a.numChilds>0){var c=false;for(var d in a.childs)c=this.colorTree_(a.childs[d],b)||c;a.is_root||(c?a.treemapnode.color(b.colorGroup):a.treemapnode.colorWeighted(b))}else a.is_root||a.treemapnode.colorWeighted(b);return true};
rhizo.layout.TreeMapLayout.prototype.revertExpandedModels_=function(a){for(var b=a.length-1;b>=0;b--){var c=a[b];if(c.expanded){c.expanded=!c.expanded;rhizo.ui.reRender(c,this.project_.renderer(),this.project_.gui().allRenderingHints())}}};rhizo.layout.layouts.treemap=rhizo.layout.TreeMapLayout;namespace("rhizo.model.loader");rhizo.model.loader.loaders=[];$globalJSONPLoaderCount=0;$globalJSONPLoaderMap={};
rhizo.model.loader.JSONP=function(a){this.resource_=a;this.loaderCount_=$globalJSONPLoaderCount++;$globalJSONPLoaderMap[this.loaderCount_]=this};rhizo.model.loader.loaders.push(rhizo.model.loader.JSONP);rhizo.model.loader.JSONP.prototype.match=function(){return/\.js$/.test(this.resource_)};
rhizo.model.loader.JSONP.prototype.load=function(a){this.callback_=a;a=document.createElement("script");a.src=this.resource_+"?jsonp=$globalJSONPLoaderMap["+this.loaderCount_+"].loadDone";a.type="text/javascript";document.getElementsByTagName("head")[0].appendChild(a)};rhizo.model.loader.JSONP.prototype.loadDone=function(a){this.callback_(a.metamodel,a.renderer,a.models);$globalJSONPLoaderMap[this.loaderCount_]=null};rhizo.model.loader.GViz=function(a){this.resource_=a};rhizo.model.loader.loaders.push(rhizo.model.loader.GViz);
rhizo.model.loader.GViz.prototype.match=function(){return false};rhizo.model.loader.GViz.prototype.load=function(a,b,c){if(typeof google=="undefined"||typeof google.visualization=="undefined")c.error("Google Visualization APIs not available.");else{var d=this;(new google.visualization.Query(this.resource_)).send(function(e){d.handleQueryResponse_(e,a,b,c)})}};
rhizo.model.loader.GViz.prototype.handleQueryResponse_=function(a,b,c,d){if(a.isError())d.error("GViz load failed: "+a.getMessage());else{a=new rhizo.gviz.Initializer(a.getDataTable(),d,c);b(a.metamodel,a.renderer,a.models)}};rhizo.model.loader.GoogleSpreadsheets=function(a){rhizo.model.loader.GViz.call(this,a)};rhizo.inherits(rhizo.model.loader.GoogleSpreadsheets,rhizo.model.loader.GViz);rhizo.model.loader.loaders.push(rhizo.model.loader.GoogleSpreadsheets);
rhizo.model.loader.GoogleSpreadsheets.prototype.match=function(){return/spreadsheets\.google\.com/.test(this.resource_)};rhizo.model.loader.GoogleGadget=function(a){rhizo.model.loader.GViz.call(this,a)};rhizo.inherits(rhizo.model.loader.GoogleGadget,rhizo.model.loader.GViz);rhizo.model.loader.loaders.push(rhizo.model.loader.GoogleGadget);rhizo.model.loader.GoogleGadget.prototype.match=function(){return false};
rhizo.model.loader.GoogleGadget.prototype.load=function(a,b,c){if(typeof google=="undefined"||typeof google.visualization=="undefined")c.error("Google Visualization APIs not available.");else if(typeof _IG_Prefs=="undefined")c.error("Google Gadget APIs not available.");else{var d=new _IG_Prefs,e=this;(new google.visualization.GadgetHelper).createQueryFromPrefs(d).send(function(f){e.handleQueryResponse_(f,a,b,c)})}};
rhizo.model.loader.load=function(a,b,c,d){for(var e=rhizo.model.loader.loaders,f=0;f<e.length;f++){var g=new e[f](a);if(g.match()){g.load(b,c,d);return}}d.error("No loader available for the resource: "+a)};namespace("rhizo.ui.gui");
rhizo.ui.gui.GUI=function(a,b,c){this.platform_=b;this.device_=c;this.container=a;this.is_small_container_=false;this.initContainer_();this.universe=null;this.universeTargetPosition_={top:0,left:0};this.viewport=null;this.componentsMap_={};this.selectionModeOn_=this.noFx=false};rhizo.ui.gui.GUI.prototype.done=function(){/kb=(true|yes|1)/.test(document.location.href)&&this.activateOnscreenKeyboard()};
rhizo.ui.gui.GUI.prototype.initContainer_=function(){this.container.addClass("rhizo").addClass("rhizo-device-"+this.device_).addClass("rhizo-platform-"+this.platform_);this.is_small_container_=this.container.width()<600||this.container.height()<250};rhizo.ui.gui.GUI.prototype.setViewport=function(a){this.viewport=a};rhizo.ui.gui.GUI.prototype.setUniverse=function(a){this.universe=a};rhizo.ui.gui.GUI.prototype.addComponent=function(a,b){this.componentsMap_[a]=b};
rhizo.ui.gui.GUI.prototype.getComponent=function(a){return this.componentsMap_[a]};rhizo.ui.gui.GUI.prototype.isSmall=function(){return this.is_small_container_};rhizo.ui.gui.GUI.prototype.isMobile=function(){return this.platform_=="mobile"};rhizo.ui.gui.GUI.prototype.allRenderingHints=function(){return{small:this.isSmall(),mobile:this.isMobile()}};rhizo.ui.gui.GUI.prototype.isSelectionModeOn=function(){return this.selectionModeOn_};
rhizo.ui.gui.GUI.prototype.toggleSelectionMode=function(){var a=(this.selectionModeOn_=!this.selectionModeOn_)?"disable":"enable";this.viewport.selectable(this.selectionModeOn_?"enable":"disable").draggable(a).toggleClass("rhizo-selection-mode");(a=this.getComponent("rhizo.ui.component.BottomBar"))&&a.toggleComponent("rhizo.ui.component.SelectionManager",this.selectionModeOn_);(a=this.getComponent("rhizo.ui.component.SelectionManager"))&&a.toggleSelectionTrigger(this.selectionModeOn_)};
rhizo.ui.gui.GUI.prototype.disableFx=function(a){this.noFx=a};rhizo.ui.gui.GUI.prototype.moveUniverse=function(a){this.universeTargetPosition_={top:a.top,left:a.left};this.universe.stop().css(this.universeTargetPosition_)};rhizo.ui.gui.GUI.prototype.panUniverse=function(a,b){var c=Math.round(this.viewport.get(0).offsetHeight/10);this.universeTargetPosition_={top:a*c+this.universeTargetPosition_.top,left:b*c+this.universeTargetPosition_.left};this.universe.stop().animate(this.universeTargetPosition_)};
rhizo.ui.gui.GUI.prototype.activateOnscreenKeyboard=function(){rhizo.keyboard&&rhizo.keyboard.Keyboard&&new rhizo.keyboard.Keyboard(this.container)};namespace("rhizo.bootstrap");rhizo.bootstrap.Bootstrap=function(a,b){this.container_=a;this.options_={selectfilter:".rhizo-model:visible"};b&&$.extend(this.options_,b)};rhizo.bootstrap.Bootstrap.prototype.prepareAndDeploy=function(a){this.prepare();this.deploy(a)};
rhizo.bootstrap.Bootstrap.prototype.prepare=function(){this.gui_=this.initGui_();this.project_=new rhizo.Project(this.gui_,this.options_);this.template_=this.initTemplate_(this.gui_,this.project_);this.project_.chromeReady()};rhizo.bootstrap.Bootstrap.prototype.deploy=function(a){(a=a||this.tryInitResourceFromUrl_())&&rhizo.model.loader.load(a,jQuery.proxy(this.deployExplicit,this),this.options_,this.project_.logger())};
rhizo.bootstrap.Bootstrap.prototype.deployWithLoader=function(a){a.load(jQuery.proxy(this.deployExplicit,this),this.options_,this.project_.logger())};rhizo.bootstrap.Bootstrap.prototype.deployExplicit=function(a,b,c){this.project_.setMetaModel(a);this.project_.setRenderer(b);this.project_.metaReady();this.template_.renderDynamic(this.options_);this.template_.activateDynamic(this.options_);this.project_.deploy(c);this.gui_.done();this.template_.done()};
rhizo.bootstrap.Bootstrap.prototype.identifyPlatformAndDevice_=function(){if(this.options_.forcePlatform&&this.options_.forceDevice)return{platform:this.options_.forcePlatform,device:this.options_.forceDevice};if(navigator.userAgent.toLowerCase().indexOf("ipad")!=-1)return{platform:"mobile",device:"ipad"};return{platform:"default",device:"default"}};
rhizo.bootstrap.Bootstrap.prototype.identifyTemplate_=function(a){var b={bottom:rhizo.ui.component.BottomTemplate,"default":rhizo.ui.component.StandardTemplate};if(this.options_.forceTemplate&&this.options_.forceTemplate in b)if(this.options_.forceTemplate)return b[this.options_.forceTemplate];if(a.isMobile()||a.isSmall())return b.bottom;return b["default"]};
rhizo.bootstrap.Bootstrap.prototype.initGui_=function(){var a=this.identifyPlatformAndDevice_();a=new rhizo.ui.gui.GUI(this.container_,a.platform,a.device);this.options_.noAnims&&a.disableFx(true);rhizo.jquery.init(a,this.options_.noAnims);return a};rhizo.bootstrap.Bootstrap.prototype.initTemplate_=function(a){a=new (this.identifyTemplate_(a))(this.project_);a.renderChrome(this.options_);a.activateChrome(this.options_);return a};
rhizo.bootstrap.Bootstrap.prototype.tryInitResourceFromUrl_=function(){if(!this.options_.allowSourcesFromUrl){this.project_.logger().warn("Sources extraction from url is disabled");return null}var a=/(source|src)=([^&]+)/.exec(document.location.href);if(!a||!a[2]){this.project_.logger().error("Unable to identify datasource from location");return null}else return decodeURIComponent(a[2])};
