application: rhizospherejs
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: py/handlers/main.py

- url: /rhizo.html
  script: py/handlers/rhizo.py

- url: /multi.html
  script: py/handlers/rhizo.py

- url: /ig
  script: py/handlers/rhizo.py

- url: /sample/.*\.js
  script: py/handlers/sample.py

- url: /doc(/(.*\.html)?)?
  script: py/handlers/doc.py

- url: /broadcast/.*
  script: py/handlers/broadcast.py

# Static files. Exclude static/samples/js since it is served by the
# sample handler.

- url: /favicon.ico
  static_files: static/shared/img/rhizosphere.ico
  upload: static/shared/img/rhizosphere.ico

- url: /apple-touch-icon.png
  static_files: static/shared/img/rhizosphere_ipad_iphone.png
  upload: static/shared/img/rhizosphere_ipad_iphone.png

- url: /static/src/(.*?)/(.*)
  static_files: static/src/\1/\2
  upload: static/src/(.*?)/(.*)

- url: /static/lib/(.*?)/(.*)
  static_files: static/lib/\1/\2
  upload: static/lib/(.*?)/(.*)

- url: /static/shared/(.*?)/(.*)
  static_files: static/shared/\1/\2
  upload: static/shared/(.*?)/(.*)

- url: /static/welcome/(.*?)/(.*)
  static_files: static/welcome/\1/\2
  upload: static/welcome/(.*?)/(.*)

- url: /static/doc/(.*?)/(.*)
  static_files: static/doc/\1/\2
  upload: static/doc/(.*?)/(.*)

- url: /static/samples/img/(.*)
  static_files: static/samples/img/\1
  upload: static/samples/img/(.*)

- url: /static/samples/stylesheets/(.*)
  static_files: static/samples/stylesheets/\1
  upload: static/samples/stylesheets/(.*)
