application: rhizospherejs
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: py/handlers/main.py

- url: /rhizo.html
  script: py/handlers/rhizo.py

- url: /sample/.*
  script: py/handlers/sample.py

- url: /static
  static_dir: static
