function namespace(a){a=a.split(".");for(var b=window,c=0;c<a.length;c++){if(typeof b[a[c]]=="undefined")b[a[c]]={};b=b[a[c]]}}namespace("rhizo.util");rhizo.util.LOG_E_10=Math.log(10);rhizo.util.log10_=function(a){return Math.log(a)/rhizo.util.LOG_E_10};rhizo.util.orderOfMagnitude=function(a){if(a==0)return Number.NaN;return Math.floor(Math.round(rhizo.util.log10_(Math.abs(a))*100)/100)};namespace("rhizo.ui");
rhizo.ui.toHumanLabel=function(a){if(typeof a=="number"&&a!=0){var b=rhizo.util.orderOfMagnitude(a);if(b<0)return a.toFixed(-b);b=parseInt(b/3,10);var c=["","K","M","G","T","P","E","Z","Y"][b]||"";return(a/Math.pow(10,b*3)).toPrecision(3)+c}else return a};
rhizo.ui.performanceTuning=function(a){if(a){jQuery.fx.off=true;jQuery.fn.extend({move:function(b,c,d,e){$(this).css("top",b);$(this).css("left",c);d!=null&&$(this).css("bottom",d);e!=null&&$(this).css("right",e)}})}else jQuery.fn.extend({move:function(b,c,d,e){if(jQuery.fx.off){$(this).css("top",b);$(this).css("left",c);d!=null&&$(this).css("bottom",d);e!=null&&$(this).css("right",e)}else{b={top:b,left:c};if(d!=null)b.bottom=d;if(e!=null)b.right=e;$(this).animate(b,1E3)}}})};
rhizo.ui.expandable=function(a,b){return typeof a.expandable=="boolean"?a.expandable:typeof a.expandable=="function"?a.expandable(b):false};
rhizo.ui.initExpandable=function(a,b){if(rhizo.ui.expandable(a,b)){$(".rhizo-model").hover(function(){$(this).children(".rhizo-expand-model").css("display","")},function(){$(this).children(".rhizo-expand-model").css("display","none")});$(".rhizo-expand-model").click(function(){var c=$(this).attr("id").replace(/rhizo-expand-/,"");c=$p.model(c);c.expanded=!c.expanded;var d=a.render(c.unwrap(),c.expanded,b);c.rendering.css("z-index",c.expanded?60:50);c.rendering.children(":not(.rhizo-expand-model)").remove();
c.rendering.append(d)})}};namespace("rhizo.meta");rhizo.meta.StringKind=function(){};rhizo.meta.StringKind.prototype.renderFilter=function(a,b){var c=$("<input type='text' />");$(c).change(function(){$p.filter(b,$(this).val())});return $("<div class='rhizo-filter' />").append(a.label+": ").append($(c))};rhizo.meta.StringKind.prototype.survivesFilter=function(a,b){return a!=""&&b.toLowerCase().indexOf(a.toLowerCase())!=-1};
rhizo.meta.StringKind.prototype.cluster=function(a){return{key:a.toUpperCase().charAt(0),label:a.toUpperCase().charAt(0)}};rhizo.meta.NumberKind=function(){};rhizo.meta.NumberKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.NumberKind.prototype.survivesFilter=function(a,b){var c=parseInt(a,10);return isNaN(c)?true:c==b};rhizo.meta.NumberKind.prototype.compare=function(a,b){return parseInt(a,10)-parseInt(b,10)};
rhizo.meta.NumberKind.prototype.cluster=function(a){var b=parseInt(a,10);if(parseFloat(a)<=10)return{key:b,label:b.toString()};for(var c=0;b>=10;){b=parseInt(b/10);c++}c=Math.pow(10,c);b=parseInt(a/c,10)*c;a=parseInt(a/c+1,10)*c;return{key:b,label:b.toString()+" - "+a.toString()}};
rhizo.meta.DateKind=function(a){this.monthMap_=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];this.clusterby_=a||"y";if(this.clusterby_!="y"&&this.clusterby_!="m"&&this.clusterby_!="d")this.clusterby_="y"};
rhizo.meta.DateKind.prototype.renderFilter=function(a,b){var c=$("<select style='vertical-align:top' />");c.append("<option value='yyyy'>yyyy</option>");for(var d=a.minYear;d<=a.maxYear;d++)c.append("<option value='"+d+"'>"+d+"</option>");var e=$("<select style='vertical-align:top' />");e.append("<option value='mm'>mm</option>");for(d=0;d<this.monthMap_.length;d++)e.append("<option value='"+d+"'>"+this.monthMap_[d]+"</option>");var f=$("<select style='vertical-align:top' />");f.append("<option value='dd'>dd</option>");
for(d=1;d<=31;d++)f.append("<option value='"+d+"'>"+d+"</option>");$(c).add($(e)).add($(f)).change(function(){$p.filter(b,[$(c).val(),$(e).val(),$(f).val()])});return $("<div class='rhizo-filter' />").append(a.label+": ").append($(c)).append(" - ").append($(e)).append(" - ").append($(f))};
rhizo.meta.DateKind.prototype.survivesFilter=function(a,b){var c=parseInt(a[0],10),d=parseInt(a[1],10),e=parseInt(a[2],10);return(isNaN(c)||b.getFullYear()==c)&&(isNaN(d)||b.getMonth()==d)&&(isNaN(e)||b.getDate()==e)};
rhizo.meta.DateKind.prototype.cluster=function(a){return this.clusterby_=="y"?{key:a.getFullYear()+"-00-01",label:a.getFullYear()}:this.clusterby_=="m"?{key:a.getFullYear()+"-"+this.addZero_(a.getMonth())+"-01",label:a.getFullYear()+"-"+this.monthMap_[a.getMonth()]}:{key:a.getFullYear()+"-"+this.addZero_(a.getMonth())+"-"+this.addZero_(a.getDate()),label:a.getFullYear()+"-"+this.monthMap_[a.getMonth()]+"-"+a.getDate()}};
rhizo.meta.DateKind.prototype.addZero_=function(a){a=a.toString();if(a.length==1)a="0"+a;return a};rhizo.meta.RangeKind=function(){};
rhizo.meta.RangeKind.prototype.renderFilter=function(a,b){var c=$("<div id='rhizo-slider-"+b+"' />"),d=$("<strong>"+this.toHumanLabel_(a.min)+"</strong>"),e=$("<strong>"+this.toHumanLabel_(a.max)+"</strong>"),f=this.toFilterScale_(a.min),g=this.toFilterScale_(a.max);a.stepping&&this.toFilterScale_(a.stepping);var h=function(){var i=this;return function(m,j){var l=$("#rhizo-slider-"+b).slider("values",0),n=$("#rhizo-slider-"+b).slider("values",1);if(l==j.value){d.text(i.toHumanLabel_(i.toModelScale_(l))).addClass("rhizo-slider-moving");
e.removeClass("rhizo-slider-moving")}else{e.text(i.toHumanLabel_(i.toModelScale_(n))).addClass("rhizo-slider-moving");d.removeClass("rhizo-slider-moving")}}}.call(this),k=function(){var i=this;return function(){var m=Math.max($("#rhizo-slider-"+b).slider("values",0),f),j=Math.min($("#rhizo-slider-"+b).slider("values",1),g);d.text(i.toHumanLabel_(i.toModelScale_(m))).removeClass("rhizo-slider-moving");e.text(i.toHumanLabel_(i.toModelScale_(j))).removeClass("rhizo-slider-moving");$p.filter(b,{min:m,
max:j})}}.call(this);$(c).slider({stepping:a.stepping,steps:a.steps,range:true,min:f,max:g,slide:h,stop:k,orientation:"horizontal",values:[f,g]});return $("<div class='rhizo-filter' />").append(a.label+": ").append($(d)).append(" to ").append($(e)).append($(c))};rhizo.meta.RangeKind.prototype.survivesFilter=function(a,b){var c=this.toModelScale_(a.min),d=this.toModelScale_(a.max);return b>=c&&b<=d};rhizo.meta.RangeKind.prototype.compare=rhizo.meta.NumberKind.prototype.compare;
rhizo.meta.RangeKind.prototype.cluster=rhizo.meta.NumberKind.prototype.cluster;rhizo.meta.RangeKind.prototype.toModelScale_=function(a){return a};rhizo.meta.RangeKind.prototype.toFilterScale_=function(a){return a};rhizo.meta.RangeKind.prototype.toHumanLabel_=function(a){return a};rhizo.meta.BooleanKind=function(){};
rhizo.meta.BooleanKind.prototype.renderFilter=function(a,b){var c=$("<select />");c.append("<option value=''>-</option>");c.append("<option value='true'>Yes</option>");c.append("<option value='false'>No</option>");$(c).change(function(){$p.filter(b,$(this).val())});return $("<div class='rhizo-filter' />").append(a.label+": ").append($(c))};rhizo.meta.BooleanKind.prototype.survivesFilter=function(a,b){return a=="true"==b};rhizo.meta.BooleanKind.prototype.compare=function(a,b){return a?b?0:-1:b?1:0};
rhizo.meta.CategoryKind=function(){};rhizo.meta.CategoryKind.prototype.renderFilter=function(a,b){var c=$("<select "+(a.multiple?'multiple size="4" ':"")+" style='vertical-align:top' />");c.append("<option value=''>-</option>");a.categories.forEach(function(d){c.append("<option value='"+d+"'>"+d+"</option>")});$(c).change(function(){var d=[$(this).val()];if(a.multiple)d=$.grep($(this).val(),function(e){return e!=""});$p.filter(b,d)});return $("<div class='rhizo-filter' />").append(a.label+": ").append($(c))};
rhizo.meta.CategoryKind.prototype.survivesFilter=function(a,b){var c=false;a.forEach(function(d){if(b.indexOf(d)!=-1)c=true});return c};rhizo.meta.CategoryKind.prototype.cluster=function(a){return{key:a.length==0?"Nothing":a,label:a.length==0?"Nothing":a}};rhizo.meta.CategoryKind.prototype.compare=function(a,b){return a.length-b.length};
rhizo.meta.sortBy=function(a,b,c){return function(d,e){var f=d.unwrap(),g=e.unwrap(),h=c?-1:1;return b.compare?b.compare(f[a],g[a])*h:(f[a]<g[a]?-1:f[a]>g[a]?1:0)*h}};rhizo.meta.sortByKind=function(a,b){return function(c,d){var e=b?-1:1;return a.compare?a.compare(c,d)*e:(c<d?-1:c>d?1:0)*e}};rhizo.meta.Kind={STRING:new rhizo.meta.StringKind,NUMBER:new rhizo.meta.NumberKind,DATE:new rhizo.meta.DateKind,RANGE:new rhizo.meta.RangeKind,BOOLEAN:new rhizo.meta.BooleanKind,CATEGORY:new rhizo.meta.CategoryKind};
namespace("rhizo");rhizo.disableLogging=function(){rhizo.log=function(){}};
rhizo.log=function(a,b){var c=b||"info",d="#888";switch(c){case "error":d="#ff0000";break;case "warning":d="#ffff00";break}var e=new Date;e=e.getHours()+":"+e.getMinutes()+":"+e.getSeconds()+" ";c=$("<p class='rhizo-log-"+c+"'>"+e+a+"</p>");$("#rhizo-console-contents").prepend(c);b&&c.effect("highlight",{color:d},1E3);if(!$("#rhizo-console-contents").is(":visible")&&b)$("#rhizo-right").is(":visible")?$("#rhizo-console-header").effect("highlight",{color:d},1E3):$("#rhizo-right-pop").effect("highlight",
{color:d},1E3)};rhizo.error=function(a){rhizo.log(a,"error")};rhizo.warning=function(a){rhizo.log(a,"warning")};rhizo.meta.DecimalKind=function(a){this.precision_=a||2};rhizo.meta.DecimalKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.DecimalKind.prototype.survivesFilter=function(a,b){var c=parseFloat(a);return isNaN(c)?true:c.toFixed(this.precision_)==b.toFixed(this.precision_)};rhizo.meta.DecimalKind.prototype.compare=function(a,b){return parseFloat(a)-parseFloat(b)};
rhizo.meta.DecimalKind.prototype.cluster=function(a){a=parseFloat(a.toFixed(this.precision_),10);var b=rhizo.util.orderOfMagnitude(a);if(isNaN(b))return{key:0,label:(new Number(0)).toFixed(this.precision_)};a=Math.pow(10,b);b=Math.pow(10,b+1);return{key:a,label:rhizo.ui.toHumanLabel(a)+" - "+rhizo.ui.toHumanLabel(b)}};rhizo.meta.DecimalRangeKind=function(a){this.precision_=a||2;this.scale_=Math.pow(10,this.precision_)};rhizo.meta.DecimalRangeKind.prototype.renderFilter=rhizo.meta.RangeKind.prototype.renderFilter;
rhizo.meta.DecimalRangeKind.prototype.survivesFilter=rhizo.meta.RangeKind.prototype.survivesFilter;rhizo.meta.DecimalRangeKind.prototype.compare=rhizo.meta.DecimalKind.prototype.compare;rhizo.meta.DecimalRangeKind.prototype.cluster=rhizo.meta.DecimalKind.prototype.cluster;rhizo.meta.DecimalRangeKind.prototype.toModelScale_=function(a){return parseFloat((a/this.scale_).toFixed(this.precision_))};rhizo.meta.DecimalRangeKind.prototype.toFilterScale_=function(a){return parseInt(a*this.scale_,10)};
rhizo.meta.DecimalRangeKind.prototype.toHumanLabel_=rhizo.meta.RangeKind.prototype.toHumanLabel_;rhizo.meta.LogarithmRangeKind=function(a){this.precision_=a||2;this.scale_=Math.pow(10,this.precision_)};rhizo.meta.LogarithmRangeKind.prototype.renderFilter=rhizo.meta.DecimalRangeKind.prototype.renderFilter;rhizo.meta.LogarithmRangeKind.prototype.survivesFilter=rhizo.meta.DecimalRangeKind.prototype.survivesFilter;rhizo.meta.LogarithmRangeKind.prototype.compare=rhizo.meta.DecimalRangeKind.prototype.compare;
rhizo.meta.LogarithmRangeKind.prototype.cluster=rhizo.meta.DecimalRangeKind.prototype.cluster;rhizo.meta.LogarithmRangeKind.prototype.toModelScale_=function(a){return parseFloat(Math.pow(10,a/this.scale_).toFixed(this.precision_))};rhizo.meta.LogarithmRangeKind.prototype.toFilterScale_=function(a){return parseInt(rhizo.util.log10_(a)*this.scale_,10)};rhizo.meta.LogarithmRangeKind.prototype.toHumanLabel_=rhizo.meta.DecimalRangeKind.prototype.toHumanLabel_;rhizo.meta.StringArrayKind=function(){};
rhizo.meta.StringArrayKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.StringArrayKind.prototype.survivesFilter=function(a,b){if(a!="")for(var c=0;c<b.length;c++)if(b[c].toLowerCase().indexOf(a.toLowerCase())!=-1)return true;return false};rhizo.meta.StringArrayKind.prototype.cluster=function(){return{key:"undefined",label:"Clustering unsupported for this datatype."}};rhizo.meta.Kind.DECIMAL=new rhizo.meta.DecimalKind;rhizo.meta.Kind.DECIMALRANGE=new rhizo.meta.DecimalRangeKind;
rhizo.meta.Kind.LOGARITHMRANGE=new rhizo.meta.LogarithmRangeKind;rhizo.meta.Kind.STRINGARRAY=new rhizo.meta.StringArrayKind;namespace("rhizo.model");rhizo.model.SuperModel=function(a,b){this.model=a;this.id=a.id;this.selected=b||false;this.filters_={};this.rendering=null;this.expanded=false};rhizo.model.SuperModel.prototype.unwrap=function(){return this.model};rhizo.model.SuperModel.prototype.toString=function(){return this.model.toString()};
rhizo.model.SuperModel.prototype.isFiltered=function(a){if(a)return this.filters_[a]||false;else{a=0;for(key in this.filters_)a++;return a!=0}};rhizo.model.SuperModel.prototype.filter=function(a){this.filters_[a]=true};rhizo.model.SuperModel.prototype.resetFilter=function(a){delete this.filters_[a]};
rhizo.model.kickstart=function(a,b,c){var d=b.render(a.unwrap(),a.expanded,c),e=$('<div class="rhizo-model"></div>');e.append(d);if(rhizo.ui.expandable(b,c)){b=$('<div class="rhizo-expand-model" style="display:none" id="rhizo-expand-'+a.id+'"></div>');$(e).append(b)}a.rendering=e;$(e).attr("id",a.id);$(e).dblclick(function(){$p.isSelected(this.id)?$p.unselect(this.id):$p.select(this.id)});$(e).draggable({opacity:0.7,cursor:"pointer",zIndex:1E4,distance:3,start:function(f,g){$p.toggleSelection("disable");
$("#"+g.helper[0].id).data("dropTop0",parseInt($("#"+g.helper[0].id).css("top"),10));$("#"+g.helper[0].id).data("dropLeft0",parseInt($("#"+g.helper[0].id).css("left"),10));if($p.isSelected(g.helper[0].id))for(id in $p.allSelected()){$("#"+id).data("top0",parseInt($("#"+id).css("top"),10)-parseInt($(g.helper[0]).css("top"),10));$("#"+id).data("left0",parseInt($("#"+id).css("left"),10)-parseInt($(g.helper[0]).css("left"),10));$("#"+id).data("dropTop0",parseInt($("#"+id).css("top"),10));$("#"+id).data("dropLeft0",
parseInt($("#"+id).css("left"),10))}},drag:function(f,g){if($p.isSelected(g.helper[0].id))for(id in $p.allSelected())if(id!=g.helper[0].id){$("#"+id).css("top",$("#"+id).data("top0")+g.position.top);$("#"+id).css("left",$("#"+id).data("left0")+g.position.left)}},stop:function(f,g){$p.toggleSelection("enable");if($p.isSelected(g.helper[0].id))for(id in $p.allSelected()){$("#"+id).removeData("top0");$("#"+id).removeData("left0")}},refreshPositions:false});return e};namespace("rhizo.layout");
rhizo.layout.metaModelKeySelector=function(a){a=$("<select id='"+a+"' />");if($p&&$p.metaModel())for(key in $p.metaModel())a.append("<option value='"+key+"'>"+$p.metaModel()[key].label+"</option>");return a};rhizo.layout.NoLayout=function(){};rhizo.layout.NoLayout.prototype.layout=function(){};rhizo.layout.NoLayout.prototype.toString=function(){return"-"};rhizo.layout.FlowLayout=function(a,b){this.top=a||5;this.left=b||5};
rhizo.layout.FlowLayout.prototype.layout=function(a,b,c){a=$(a).width();var d=0,e=$("#rhizo-flowlayout-order").val(),f=$("#rhizo-flowlayout-desc:checked").length>0;if(e){rhizo.log("Sorting by "+e);b.sort(rhizo.meta.sortBy(e,c[e].kind,f))}c=0;for(e=b.length;c<e;c++){f=$(b[c].rendering);d=Math.max(d,f.height());if(this.left+f.width()>a){this.left=5;this.top+=d+5;d=f.height()}f.move(this.top,this.left);this.left+=f.width()+5}this.top+=d};
rhizo.layout.FlowLayout.prototype.cleanup=function(){this.top=this.left=5};rhizo.layout.FlowLayout.prototype.details=function(){return $("<div />").append("Ordered by: ").append(rhizo.layout.metaModelKeySelector("rhizo-flowlayout-order")).append(" desc?").append('<input type="checkbox" id="rhizo-flowlayout-desc" />')};rhizo.layout.FlowLayout.prototype.toString=function(){return"List"};rhizo.layout.ScrambleLayout=function(){};
rhizo.layout.ScrambleLayout.prototype.layout=function(a,b,c,d){if(!(d&&d.filter)){c=Math.round($(a).width()*0.3);d=Math.round($(a).height()*0.3);for(var e=0,f=b.length;e<f;e++){var g=$(b[e].rendering),h=Math.round($(a).height()/3+Math.random()*d*2-d),k=Math.round($(a).width()/3+Math.random()*c*2-c);g.move(h,k)}}};rhizo.layout.ScrambleLayout.prototype.toString=function(){return"Random"};rhizo.layout.BucketLayout=function(){this.internalFlowLayout_=new rhizo.layout.FlowLayout;this.bucketHeaders_=[]};
rhizo.layout.BucketLayout.prototype.layout=function(a,b,c,d){var e=$("#rhizo-bucketlayout-desc:checked").length>0,f=$("#rhizo-bucketlayout-bucket").val();if(c[f]){rhizo.log("Bucketing by "+f);var g,h;if(c[f].cluster){g=c[f].cluster;h=c[f]}else{g=c[f].kind.cluster;h=c[f].kind}for(var k={},i={},m=0,j=b.length;m<j;m++){var l=b[m].unwrap()[f],n=l;if(g){n=g.call(h,l);l=n.key;n=n.label}if(!k[l]){k[l]=[];i[l]=n}k[l].push(b[m])}b=[];for(l in k)b.push(l);b.sort(rhizo.meta.sortByKind(c[f].kind,e));b.forEach(function(o){this.renderBucketHeader_(a,
i[o]);this.internalFlowLayout_.layout(a,k[o],c,d);this.internalFlowLayout_.top+=10;this.internalFlowLayout_.left=5},this)}else rhizo.error("layoutBy attribute does not match any property")};rhizo.layout.BucketLayout.prototype.renderBucketHeader_=function(a,b){var c=$("<div class='rhizo-bucket-header'>"+b+"</div>");c.css("position","absolute").css("left",5).css("top",this.internalFlowLayout_.top);this.bucketHeaders_.push(c);$(a).append(c);this.internalFlowLayout_.top+=c.height()+5};
rhizo.layout.BucketLayout.prototype.details=function(){return $("<div />").append("Group by: ").append(rhizo.layout.metaModelKeySelector("rhizo-bucketlayout-bucket")).append(" desc?").append('<input type="checkbox" id="rhizo-bucketlayout-desc" />')};rhizo.layout.BucketLayout.prototype.cleanup=function(){this.internalFlowLayout_.cleanup();this.bucketHeaders_.forEach(function(a){$(a).remove()});this.bucketHeaders_=[]};rhizo.layout.BucketLayout.prototype.toString=function(){return"Buckets"};
rhizo.layout.layouts={no:new rhizo.layout.NoLayout,flow:new rhizo.layout.FlowLayout,scramble:new rhizo.layout.ScrambleLayout,bucket:new rhizo.layout.BucketLayout};namespace("rhizo.autorender");
rhizo.autorender.AR=function(a,b,c,d){this.metamodel_=a;this.metamodelFields_=0;for(var e in this.metamodel_)this.metamodelFields_++;this.fallbackToDefaults_=typeof c=="undefined"?true:c;this.locateFields_();a=0;if(this.sizeField_){this.sizeRange_=this.locateMinMax_(b,this.sizeField_);a++}if(this.colorField_){this.colorRange_=this.locateMinMax_(b,this.colorField_);a++}this.numfields_=typeof d=="undefined"?5:Math.max(d,a)};rhizo.autorender.AR.prototype.getSizeRange=function(){return this.sizeRange_};
rhizo.autorender.AR.prototype.getColorRange=function(){return this.colorRange_};rhizo.autorender.AR.prototype.locateFields_=function(){for(key in this.metamodel_){this.masterField_=this.masterField_||this.getArField_(key,"master","true");this.sizeField_=this.sizeField_||this.getArField_(key,"bind","size");this.colorField_=this.colorField_||this.getArField_(key,"bind","color")}this.locateDefaultFields_()};
rhizo.autorender.AR.prototype.getArField_=function(a,b,c){if(this.metamodel_[a].ar)if((b=this.metamodel_[a].ar[b])&&b.toString().indexOf(c)!=-1)return a;return null};
rhizo.autorender.AR.prototype.locateDefaultFields_=function(){for(key in this.metamodel_){if(!this.masterField_)this.masterField_=key;if(!this.fallbackToDefaults_)break;if(!this.sizeField_&&(this.metamodel_[key].kind==rhizo.meta.Kind.NUMBER||this.metamodel_[key].kind==rhizo.meta.Kind.RANGE))this.sizeField_=key;else if(this.sizeField_)if(!this.colorField_&&(this.metamodel_[key].kind==rhizo.meta.Kind.NUMBER||this.metamodel_[key].kind==rhizo.meta.Kind.RANGE))this.colorField_=key}};
rhizo.autorender.AR.prototype.locateMinMax_=function(a,b){if(this.metamodel_[b].kind==rhizo.meta.Kind.RANGE)return{min:this.metamodel_[b].min,max:this.metamodel_[b].max,label:this.metamodel_[b].label};else{var c=Number.POSITIVE_INFINITY,d=Number.NEGATIVE_INFINITY;a.forEach(function(e){c=Math.min(c,e[b]);d=Math.max(d,e[b])});return{min:c,max:d,label:this.metamodel_[b].label}}};
rhizo.autorender.AR.prototype.getClass_=function(a,b,c,d){a=parseInt((a-b.min)/(b.max-b.min)*5,10);return"ar-"+d+"-"+a.toString()+(c?"m":"")};rhizo.autorender.AR.prototype.getFontClass_=function(a,b,c){return this.getClass_(a,b,c,"fon")};rhizo.autorender.AR.prototype.getColorClass_=function(a,b,c){return this.getClass_(a,b,c,"col")};
rhizo.autorender.AR.prototype.renderSingleModelKey_=function(a,b){var c=[];c.push('<p><span class="dim">');c.push(this.metamodel_[a].label);c.push("</span>: ");c.push(b);c.push("</p>");return c.join("")};rhizo.autorender.AR.prototype.expandable=function(a){return this.metamodelFields_>(a&&a.miniLayout?1:this.numfields_+1)};
rhizo.autorender.AR.prototype.render=function(a,b,c){c=c&&c.miniLayout;var d="ar-col-0"+(c?"m":"");if(this.colorField_)d=this.getColorClass_(a[this.colorField_],this.colorRange_,c);var e="ar-fon-0"+(c?"m":"");if(this.sizeField_)e=this.getFontClass_(a[this.sizeField_],this.sizeRange_,c);if(c&&!b)return $("<div class='"+d+"'><span class='"+e+"'>"+a[this.masterField_]+"</span></div>");else{html=[];html.push("<div class='"+d+"'>");html.push("<span class='"+e+"'>"+a[this.masterField_]+"</span>");c=0;if(this.sizeField_){html.push(this.renderSingleModelKey_(this.sizeField_,
a[this.sizeField_]));c++}if(this.colorField_&&this.colorField_!=this.sizeField_){html.push(this.renderSingleModelKey_(this.colorField_,a[this.colorField_]));c++}for(key in this.metamodel_){if(c>=this.numfields_&&!b)break;if(key!=this.sizeField_&&key!=this.colorField_&&key!=this.masterField_){c++;html.push(this.renderSingleModelKey_(key,a[key]))}}html.push("</div>");return $(html.join(""))}};namespace("rhizo");$p=null;
rhizo.Project=function(a){this.models_=[];this.modelsMap_={};this.selectionMap_={};this.layoutName_="flow";this.layouEngine_=null;this.options_=a||{};$p=this};rhizo.Project.prototype.deploy=function(a){a&&this.addModels_(a)&&this.finalizeUI_();rhizo.log("*** Ready!")};
rhizo.Project.prototype.addModels_=function(a){this.models_=jQuery.map(a,function(b){return new rhizo.model.SuperModel(b)});if(!this.checkModels_())return false;this.buildModelsMap_();this.models_.forEach(this.initializeModel_,this);return true};rhizo.Project.prototype.finalizeUI_=function(){rhizo.ui.initExpandable(this.renderer_,this.options_);jQuery.fx.off=true;this.layout(this.layoutName_);this.alignVisibility(true)};rhizo.Project.prototype.model=function(a){return this.modelsMap_[a]};
rhizo.Project.prototype.metaModel=function(){return this.metaModel_};rhizo.Project.prototype.setMetaModel=function(a){this.metaModel_=a};rhizo.Project.prototype.renderer=function(){return this.renderer_};rhizo.Project.prototype.setRenderer=function(a){this.renderer_=a};rhizo.Project.prototype.resetAllFilter=function(a){this.models_.forEach(function(b){b.resetFilter(a)})};
rhizo.Project.prototype.select=function(a){var b=this.model(a);this.selectionMap_[a]=b;b.selected=true;$("#"+a).addClass("ui-selected");rhizo.log("Selected "+b)};rhizo.Project.prototype.unselect=function(a){var b=this.model(a);this.selectionMap_[a]=null;delete this.selectionMap_[a];b.selected=false;$("#"+a).removeClass("ui-selected");rhizo.log("Unselected "+b)};rhizo.Project.prototype.unselectAll=function(){for(id in this.selectionMap_)this.unselect(id)};rhizo.Project.prototype.isSelected=function(a){return this.selectionMap_[a]};
rhizo.Project.prototype.allSelected=function(){return this.selectionMap_};rhizo.Project.prototype.allUnselected=function(){return $.grep(this.models_,function(a){return!$p.selectionMap_[a.id]})};rhizo.Project.prototype.toggleSelection=function(a){$("#rhizo-viewport").selectable(a)};rhizo.Project.prototype.checkModels_=function(){rhizo.log("Checking models...");var a=true;this.models_.forEach(function(b){if(!b.id){a=false;rhizo.error("Verify your models: missing ids.")}});return a};
rhizo.Project.prototype.buildModelsMap_=function(){rhizo.log("Building models map...");this.models_.forEach(function(a){this.modelsMap_[a.id]=a},this)};rhizo.Project.prototype.initializeModel_=function(a){a=rhizo.model.kickstart(a,this.renderer_,this.options_);$(a).css("position","absolute").css("top",0).css("left",0).css("display","none");$("#rhizo-universe").append(a)};
rhizo.Project.prototype.layout=function(a,b){var c=a?a:this.layoutName_,d=rhizo.layout.layouts[c];if(d){rhizo.log("laying out...");this.layoutEngine_&&this.layoutEngine_.cleanup&&this.layoutEngine_.cleanup();this.layoutName_=c;this.layoutEngine_=d;$("#rhizo-universe").move(0,0,0,0);c=jQuery.grep(this.models_,function(e){return!e.isFiltered()});d.layout("#rhizo-universe",c,this.metaModel_,b)}else rhizo.error("Invalid layout engine:"+c)};
rhizo.Project.prototype.filter=function(a,b){this.metaModel_[a]||rhizo.error("Invalid filtering key: "+a);b!=""?this.models_.forEach(function(c){this.metaModel_[a].kind.survivesFilter(b,c.unwrap()[a])?c.resetFilter(a):c.filter(a)},this):this.models_.forEach(function(c){c.resetFilter(a)});this.alignVisibility();this.layout(null,{filter:true})};
rhizo.Project.prototype.alignVisibility=function(a){var b=0;this.models_.forEach(function(c){b+=c.isFiltered()?0:1;c.isFiltered()&&$("#"+c.id).fadeOut()});if(!a)jQuery.fx.off=this.options_.noAnims||b>200;this.models_.forEach(function(c){c.isFiltered()||$("#"+c.id).fadeIn()});if(a)jQuery.fx.off=this.options_.noAnims||b>200};rhizo.layout.TreeLayout=function(){};
rhizo.layout.TreeLayout.prototype.layout=function(a,b,c){var d=$("#rhizo-treelayout-direction").val()=="ver";this.treePainter_=new rhizo.layout.TreePainter(d);d=$("#rhizo-treelayout-parentKey").val();if(c[d]){rhizo.log("Creating tree by "+d);try{var e=this.buildTree_(b,d);b={left:0,top:0};c=0;for(var f in e){var g=this.treePainter_.toAbsoluteCoords_(this.treePainter_.calculateBoundingRect_(e[f]));if(b.left+g.w>$(a).width()){b.left=0;b.top+=c+(c>0?5:0)}this.treePainter_.draw_(a,e[f],this.treePainter_.toRelativeCoords_(b));
b.left+=g.w;c=Math.max(c,g.h)}}catch(h){if(h.name=="TreeCycleException")rhizo.error(h);else throw h;}}else rhizo.error("parentKey attribute does not match any property")};
rhizo.layout.TreeLayout.prototype.buildTree_=function(a,b){for(var c={},d=0,e=a.length;d<e;d++)c[a[d].id]=new rhizo.layout.TreeNode(a[d]);var f={};d=0;for(e=a.length;d<e;d++)if(!c[a[d].unwrap().id].validated)for(var g={},h=a[d].unwrap();;){if(g[h.id])throw new rhizo.layout.TreeCycleException("Tree is invalid: cycle detected");g[h.id]=h;c[h.id].validated=true;var k=this.findFirstVisibleParent_($p.model(h[b]),b);if(k){var i=k.unwrap();c[i.id].addChild(c[h.id]);h=k.unwrap()}else{f[h.id]=c[h.id];break}}return f};
rhizo.layout.TreeLayout.prototype.findFirstVisibleParent_=function(a,b){if(!a)return null;for(var c={};a.isFiltered();){if(c[a.id])throw new rhizo.layout.TreeCycleException("Tree is invalid: hidden cycle detected");c[a.id]=a;a=$p.model(a.unwrap()[b]);if(!a)return null}return a};rhizo.layout.TreeLayout.prototype.details=function(){var a=$("<select id='rhizo-treelayout-direction' />");a.append("<option value='hor'>Horizontally</option>");a.append("<option value='ver'>Vertically</option>");return $("<div />").append(a).append(" arrange by: ").append(rhizo.layout.metaModelKeySelector("rhizo-treelayout-parentKey"))};
rhizo.layout.TreeLayout.prototype.toString=function(){return"Tree"};rhizo.layout.TreeLayout.prototype.cleanup=function(){this.treePainter_&&this.treePainter_.cleanup_()};rhizo.layout.TreePainter=function(a){this.connectors_=[];if(this.vertical_=a){this.gdName_="top";this.odName_="left";this.gdLength_="height";this.odLength_="width"}else{this.gdName_="left";this.odName_="top";this.gdLength_="width";this.odLength_="height"}};
rhizo.layout.TreePainter.prototype.gd_=function(a){return this.vertical_?a.height():a.width()};rhizo.layout.TreePainter.prototype.od_=function(a){return this.vertical_?a.width():a.height()};rhizo.layout.TreePainter.prototype.toAbsoluteCoords_=function(a){return this.vertical_?{w:a.od,h:a.gd}:{w:a.gd,h:a.od}};rhizo.layout.TreePainter.prototype.toRelativeCoords_=function(a){return this.vertical_?{gd:a.top,od:a.left}:{gd:a.left,od:a.top}};
rhizo.layout.TreePainter.prototype.packedCenter_=function(a,b){return{gd:a.gd+5+this.gd_(b)/2,od:a.od+this.od_(b)/2}};rhizo.layout.TreePainter.prototype.evenCenter_=function(a,b,c){return{gd:a.gd+c.gd/2,od:a.od+5+this.od_(b)/2}};
rhizo.layout.TreePainter.prototype.calculateBoundingRect_=function(a){var b={gd:0,od:0};for(var c in a.childs){var d=this.calculateBoundingRect_(a.childs[c]);b.gd+=d.gd+5;b.od=Math.max(b.od,d.od)}c=a.superModel.rendering;a.boundingRect={od:this.od_(c)+b.od+25,gd:Math.max(this.gd_(c),b.gd)+5};return a.boundingRect};
rhizo.layout.TreePainter.prototype.draw_=function(a,b,c,d,e){var f=$(b.superModel.rendering);if(this.vertical_){f.move(c.gd+5,c.od);d!=null&&this.drawConnector_(a,this.packedCenter_(c,f),this.packedCenter_(d,e.superModel.rendering))}else{f.move(c.od+5,c.gd+(b.boundingRect.gd-this.gd_(f))/2);d!=null&&this.drawConnector_(a,this.evenCenter_(c,f,b.boundingRect),this.evenCenter_(d,e.superModel.rendering,e.boundingRect))}d=c.gd;for(var g in b.childs){e=b.childs[g];var h={od:c.od+this.od_(f)+20,gd:d};this.draw_(a,
e,h,c,b);d+=e.boundingRect.gd+5}};
rhizo.layout.TreePainter.prototype.drawConnector_=function(a,b,c){var d=$("<div class='rhizo-tree-connector' />");d.css("position","absolute").css(this.gdName_,Math.min(b.gd,c.gd)).css(this.odName_,c.od).css(this.odLength_,2).css(this.gdLength_,Math.abs(c.gd-b.gd));var e=$("<div class='rhizo-tree-connector' />");e.css("position","absolute").css(this.gdName_,b.gd).css(this.odName_,c.od).css(this.gdLength_,2).css(this.odLength_,Math.abs(c.od-b.od));this.connectors_.push(d);this.connectors_.push(e);
$(a).append(d);$(a).append(e)};rhizo.layout.TreePainter.prototype.cleanup_=function(){this.connectors_.forEach(function(a){$(a).remove()});this.connectors_=[]};rhizo.layout.TreeNode=function(a,b){this.superModel=a;this.id=a.id;this.childs=b||{};this.validated=false};rhizo.layout.TreeNode.prototype.addChild=function(a){this.childs[a.id]||(this.childs[a.id]=a)};rhizo.layout.TreeCycleException=function(a){this.message=a;this.name="TreeCycleException"};
rhizo.layout.TreeCycleException.prototype.toString=function(){return this.name+": "+this.message};rhizo.layout.layouts.tree=new rhizo.layout.TreeLayout;namespace("rhizo.ui.component");rhizo.ui.component.Progress=function(a){a=$('<div id="rhizo-progressbar-panel"></div>').appendTo(a);this.pbar_=$('<div id="rhizo-progressbar"></div>').appendTo(a).progressbar({value:1});$('<div id="rhizo-progressbar-text">Loading...</div>').appendTo(a)};
rhizo.ui.component.Progress.prototype.update=function(a,b){this.pbar_.progressbar("value",a);b&&$("#rhizo-progressbar-text").text(b);a>=100&&this.destroy_()};rhizo.ui.component.Progress.prototype.destroy_=function(){$("#rhizo-progressbar-panel").is(":visible")?setTimeout(function(){$("#rhizo-progressbar-panel").fadeOut(500,function(){$(this).remove()})},1E3):$("#rhizo-progressbar-panel").remove()};rhizo.ui.component.Logo=function(){};rhizo.ui.component.Logo.prototype.render=function(a){$('<div id="rhizo-header"><h1>Rhizosphere</h1><p>by <a href="mailto:battlehorse@gmail.com">Riccardo Govoni</a> (c) 2009<br /><a href="http://sites.google.com/site/rhizosphereui/" target="_blank">Project info</a>&nbsp;<a href="http://sites.google.com/site/rhizosphereui/Home/documentation" target="_blank" style="font-weight:bold; text-decoration: underline">I Need Help!</a></p></div>').appendTo(a)};
rhizo.ui.component.Viewport=function(){};
rhizo.ui.component.Viewport.prototype.render=function(a,b){var c=b||{};$('<div id="rhizo-viewport"><div id="rhizo-universe"></div><div id="rhizo-scroll-trigger" title="Click to pan around" ></div></div><div id="rhizo-scroll-overlay" style="display: none"><div><button id="rhizo-scroll-done">Done</button></div></div>').appendTo(a);if(c.miniLayout){$("#rhizo-viewport").addClass("rhizo-miniRender");$("#rhizo-scroll-overlay").addClass("rhizo-miniRender")}else $("#rhizo-viewport").css("left",300).css("right",
5)};rhizo.ui.component.Viewport.prototype.activate=function(a){this.activatePanning_();this.activateSelectionSupport_(a)};
rhizo.ui.component.Viewport.prototype.activatePanning_=function(){var a={top:$("#rhizo-viewport").offset().top+$("#rhizo-universe").offset().top,left:$("#rhizo-viewport").offset().left+$("#rhizo-universe").offset().left};$("#rhizo-scroll-trigger").click(function(){$(this).hide();var b=$("#rhizo-viewport");$("#rhizo-scroll-overlay").css("left",b.css("left")).css("top",b.css("top")).css("width",b.width()).css("height",b.height()).css("z-index",99).css("display","");$("#rhizo-scroll-overlay").draggable({helper:function(){return $("<div />")},
start:function(){var c=$("#rhizo-universe").offset();$("#rhizo-universe").data("top0",c.top).data("left0",c.left)},drag:function(c,d){var e=$("#rhizo-universe");e.offset();var f=d.position.top+e.data("top0")-a.top;e=d.position.left+e.data("left0")-a.left;$("#rhizo-universe").css("top",f).css("bottom",-f).css("left",e).css("right",-e)},refreshPositions:false})});$("#rhizo-scroll-done").click(function(){$("#rhizo-scroll-overlay").css("z-index",-1).css("display","none");$("#rhizo-scroll-trigger").show()})};
rhizo.ui.component.Viewport.prototype.isOnEmptySpace=function(a){return a.target.id=="rhizo-viewport"||a.target.id=="rhizo-universe"};
rhizo.ui.component.Viewport.prototype.activateSelectionSupport_=function(a){$("#rhizo-viewport").selectable({selected:function(c,d){d.selected.id&&$p.select(d.selected.id)},unselected:function(c,d){d.unselected.id&&$p.unselect(d.unselected.id)},filter:a.selectfilter,tolerance:"touch",distance:1});var b=this;$("#rhizo-viewport").click(function(c){b.isOnEmptySpace(c)&&$p.unselectAll()})};rhizo.ui.component.MiniToolbar=function(){};rhizo.ui.component.MiniToolbar.prototype.render=function(a){$('<span><a href="" onclick="return false" id="rhizo-link-help" title="Help" >?</a><a href="" onclick="self.resizeTo(1000,700);self.reload();" title="Maximize" class="rhizo-maximize-icon"></a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-link-display" >Display</a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-link-selection" >Selection</a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-link-filters" >Filters</a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-legend" style="display: none">Legend</a></span>').appendTo(a)};
rhizo.ui.component.MiniToolbar.prototype.activate=function(){var a=[{panel:"#rhizo-update-layout",link:"#rhizo-link-display"},{panel:"#rhizo-selection",link:"#rhizo-link-selection"},{panel:"#rhizo-filter-container",link:"#rhizo-link-filters"},{panel:"#rhizo-help",link:"#rhizo-link-help"},{panel:"#rhizo-legend-panel",link:"#rhizo-legend"}];a.forEach(function(b){$(b.link).click(function(){a.forEach(function(c){if(c.panel==b.panel){$(c.panel).toggle();$(c.link).toggleClass("rhizo-filter-open")}else{$(c.panel).css("display",
"none");$(c.link).removeClass("rhizo-filter-open")}});return false})})};rhizo.ui.component.Console=function(){};rhizo.ui.component.Console.prototype.render=function(a){$('<div id="rhizo-console-header"><div id="rhizo-console-close">&#8659;</div>Log Console</div><div id="rhizo-console-contents" style="clear: right; display: none"></div>').appendTo(a)};
rhizo.ui.component.Console.prototype.activate=function(){$("#rhizo-console-close").click(function(){$("#rhizo-console-contents").is(":visible")?$("#rhizo-console-contents").slideUp("slow",function(){$("#rhizo-console-close").html("&#8659;");$("#rhizo-console-contents").empty()}):$("#rhizo-console-contents").slideDown("slow",function(){$("#rhizo-console-close").html("&#8657;")})})};rhizo.ui.component.Layout=function(){};
rhizo.ui.component.Layout.prototype.render=function(a,b){var c=b||{};c.miniLayout||$('<div class="rhizo-filters-header">Display</div>').appendTo(a);$('<div id="rhizo-update-layout"><div id="rhizo-layout-extra-options"></div></div>').appendTo(a);c.miniLayout&&$("#rhizo-update-layout").addClass("rhizo-floating-panel").css("display","none");this.select_=$("<select id='rhizo-layout' />");this.detailsMap_={};if(rhizo.layout&&rhizo.layout.layouts)for(layout in rhizo.layout.layouts){c=rhizo.layout.layouts[layout];
this.select_.append($("<option value='"+layout+"'>"+c+"</option>"));if(c.details){c=c.details();this.detailsMap_[layout]=c;$("#rhizo-layout-extra-options").append(c.css("display","none"))}}this.submit_=$("<button>Update</button>");$("#rhizo-update-layout").prepend(this.submit_).prepend(this.select_).prepend("Keep items ordered by: ")};
rhizo.ui.component.Layout.prototype.activate=function(){var a=this.detailsMap_;this.select_.change(function(){for(layout in a)layout==$(this).val()?a[layout].show("fast"):a[layout].hide("fast")});this.submit_.click(function(){$p.layout($("#rhizo-layout").val())})};rhizo.ui.component.SelectionManager=function(){};
rhizo.ui.component.SelectionManager.prototype.render=function(a,b){var c=b||{};c.miniLayout||$('<div class="rhizo-filters-header">Selection</div>').appendTo(a);$('<div id="rhizo-selection"></div>').appendTo(a);c.miniLayout&&$("#rhizo-selection").addClass("rhizo-floating-panel").css("display","none");this.button_=$('<button id="rhizo-selected-items-only">Work on selected items only</button>');this.resetButton_=$('<button id="rhizo-selected-reset" disabled="disabled">Reset</button>');$("#rhizo-selection").append(this.button_).append(this.resetButton_)};
rhizo.ui.component.SelectionManager.prototype.activate=function(){this.button_.click(function(){var a=0;for(id in $p.allSelected())a++;if(a==0)rhizo.error("No items selected");else{a=$p.allUnselected();var b=0;for(id in a){a[id].filter("__selection__");b++}$p.alignVisibility();$p.layout(null,{filter:true});$p.unselectAll();$("#rhizo-selected-reset").removeAttr("disabled").text("Reset ("+b+" filtered)")}});this.resetButton_.click(function(){$p.resetAllFilter("__selection__");$p.alignVisibility();$p.layout(null,
{filter:true});$(this).attr("disabled","disabled").text("Reset")})};rhizo.ui.component.Filters=function(){};
rhizo.ui.component.Filters.prototype.render=function(a,b){var c=b||{};c.miniLayout||$('<div class="rhizo-filters-header">Filters</div>').appendTo(a);$('<div id="rhizo-filter-container"></div>').appendTo(a);if(c.miniLayout){$("#rhizo-filter-container").addClass("rhizo-floating-panel").css("display","none");$('<span id="rhizo-next-filter" title="Next filter"></span>').appendTo($("#rhizo-filter-container"));$('<span id="rhizo-prev-filter" title="Previous filter"></span>').appendTo($("#rhizo-filter-container"))}var d=
true,e=$p.metaModel();for(key in e){var f=e[key].kind.renderFilter(e[key],key);if(c.miniLayout)if(d)d=false;else f.css("display","none");$("#rhizo-filter-container").append(f)}};
rhizo.ui.component.Filters.prototype.activate=function(){$("#rhizo-next-filter").click(function(){var a=$(".rhizo-filter:visible"),b=a.next(".rhizo-filter:hidden").eq(0);if(b.length>0){a.css("display","none");b.css("display","")}});$("#rhizo-prev-filter").click(function(){var a=$(".rhizo-filter:visible"),b=a.prev(".rhizo-filter:hidden").eq(0);if(b.length>0){a.css("display","none");b.css("display","")}})};rhizo.ui.component.Legend=function(){};
rhizo.ui.component.Legend.prototype.render=function(a,b){var c=b||{},d=null;if($p.renderer().getSizeRange)d=$p.renderer().getSizeRange();var e=null;if($p.renderer().getColorRange)e=$p.renderer().getColorRange();if(d||e){$('<div id="rhizo-legend-panel"></div>').appendTo(a);if(c.miniLayout){$("#rhizo-legend-panel").addClass("rhizo-floating-panel").css("display","none");$("#rhizo-legend").show()}else $('<div class="rhizo-filters-header">Legend</div>').appendTo($("#rhizo-legend-panel"))}if(d){$('<div id="rhizo-legend-size" style="margin-bottom: 5px"><span id="rhizo-legend-size-min" ></span><span class="ar-fon-0">A</span> -- <span class="ar-fon-5">A</span><span id="rhizo-legend-size-max" ></span></div>').appendTo($("#rhizo-legend-panel"));
$("#rhizo-legend-size-min").html(d.label+" &nbsp; "+rhizo.ui.toHumanLabel(d.min)+":");$("#rhizo-legend-size-max").html(": "+rhizo.ui.toHumanLabel(d.max))}if(e){$('<div id="rhizo-legend-color" style="margin-bottom: 5px"><span id="rhizo-legend-color-min"></span><span class="ar-col-0 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-1 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-2 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-3 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-4 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-5 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span id="rhizo-legend-color-max"></span></div>').appendTo($("#rhizo-legend-panel"));
$("#rhizo-legend-color-min").html(e.label+" &nbsp; "+rhizo.ui.toHumanLabel(e.min)+":");$("#rhizo-legend-color-max").html(": "+rhizo.ui.toHumanLabel(e.max))}};rhizo.ui.component.Legend.prototype.activate=function(){};rhizo.ui.component.Actions=function(){};rhizo.ui.component.Actions.prototype.render=function(a){$('<div id="rhizo-actions"><h1>Actions</h1><div class="rhizo-action" id="rhizo-action-2">Sample Action 1</div><div class="rhizo-action" id="rhizo-action-1">Sample Action 2</div></div>').appendTo(a)};
rhizo.ui.component.Actions.prototype.activate=function(){if($(".rhizo-action").length>0){$(".rhizo-action").draggable({helper:"clone"});$("#rhizo-universe").droppable({accept:".rhizo-action",drop:function(a,b){var c=$("#rhizo-universe").offset(),d=$("#rhizo-universe").width(),e=$("#rhizo-universe").height(),f=b.draggable.text(),g=b.absolutePosition.left-c.left;if(g+200>d)g=d-210;c=b.absolutePosition.top-c.top;if(c+200>e)c=e-210;var h=$("<div class='rhizo-droppable-action'>Drop your items here to perform:<br />"+
f+"</div>").css("position","absolute").css("top",c).css("left",g).css("display","none");$("#rhizo-universe").append(h);h.fadeIn();h.draggable({start:function(){$p.toggleSelection("disable")},stop:function(){$p.toggleSelection("enable")}});h.droppable({accept:".rhizo-model",drop:function(k,i){if($p.isSelected(i.draggable[0].id)){var m=0;for(j in $p.allSelected())m++;alert("Action applied on "+m+" elements");for(j in $p.allSelected())$("#"+j).move($("#"+j).data("dropTop0"),$("#"+j).data("dropLeft0"));
$p.unselectAll()}else{var j=i.draggable[0].id;alert("Action applied on "+$p.model(j));$("#"+j).move($("#"+j).data("dropTop0"),$("#"+j).data("dropLeft0"))}}});h.dblclick(function(){h.remove();return false})}})}};
rhizo.ui.component.MiniTemplate=function(){this.components_={LOGO:new rhizo.ui.component.Logo,VIEWPORT:new rhizo.ui.component.Viewport,LAYOUT:new rhizo.ui.component.Layout,SELECTION_MANAGER:new rhizo.ui.component.SelectionManager,FILTERS:new rhizo.ui.component.Filters,LEGEND:new rhizo.ui.component.Legend,MINITOOLBAR:new rhizo.ui.component.MiniToolbar}};
rhizo.ui.component.MiniTemplate.prototype.renderChrome=function(a,b){rhizo.disableLogging();this.components_.VIEWPORT.render(a,b);this.progress_=new rhizo.ui.component.Progress($("#rhizo-viewport"));this.bottomBar_=$('<div id="rhizo-bottom-bar"></div>').appendTo(a);this.progress_.update(10,"Creating static UI...");this.components_.MINITOOLBAR.render(this.bottomBar_,b);this.components_.LOGO.render($('<div id="rhizo-help" class="rhizo-floating-panel" style="display:none"></div>').appendTo(this.bottomBar_),
b);this.progress_.update(25,"All static UI created.")};rhizo.ui.component.MiniTemplate.prototype.activateChrome=function(a){this.progress_.update(26,"Activating static UI...");this.components_.VIEWPORT.activate(a);this.components_.MINITOOLBAR.activate(a);this.progress_.update(33,"Loading models...")};
rhizo.ui.component.MiniTemplate.prototype.renderDynamic=function(a,b){this.progress_.update(34,"Creating dynamic controls...");this.components_.LAYOUT.render(this.bottomBar_,b);this.progress_.update(38,"Layout engine created.");this.components_.SELECTION_MANAGER.render(this.bottomBar_,b);this.progress_.update(42,"Selection manager created.");this.components_.FILTERS.render(this.bottomBar_,b);this.progress_.update(46,"Filters created.");this.components_.LEGEND.render(this.bottomBar_,b);this.progress_.update(48,
"Legend created.")};rhizo.ui.component.MiniTemplate.prototype.activateDynamic=function(a){this.progress_.update(51,"Activating dynamic controls...");this.components_.LAYOUT.activate(a);this.components_.SELECTION_MANAGER.activate(a);this.components_.FILTERS.activate(a);this.components_.LEGEND.activate(a);this.progress_.update(66,"Rhizosphere controls are ready.")};rhizo.ui.component.MiniTemplate.prototype.done=function(){this.progress_.update(100,"Rhizosphere ready!")};
rhizo.ui.component.StandardTemplate=function(){this.components_={LOGO:new rhizo.ui.component.Logo,VIEWPORT:new rhizo.ui.component.Viewport,CONSOLE:new rhizo.ui.component.Console,LAYOUT:new rhizo.ui.component.Layout,SELECTION_MANAGER:new rhizo.ui.component.SelectionManager,FILTERS:new rhizo.ui.component.Filters,LEGEND:new rhizo.ui.component.Legend,ACTIONS:new rhizo.ui.component.Actions}};
rhizo.ui.component.StandardTemplate.prototype.renderChrome=function(a,b){this.components_.VIEWPORT.render(a,b);this.progress_=new rhizo.ui.component.Progress($("#rhizo-viewport"));this.leftBar_=$('<div id="rhizo-left"></div>').appendTo(a);$('<div id="rhizo-right-pop"></div>').appendTo(a);this.rightBar_=$('<div id="rhizo-right" style="display:none"></div>').appendTo(a);this.progress_.update(10,"Creating static UI...");this.components_.LOGO.render(this.leftBar_,b);this.components_.CONSOLE.render(this.rightBar_,
b);this.progress_.update(25,"All static UI created.")};
rhizo.ui.component.StandardTemplate.prototype.activateChrome=function(a){this.progress_.update(26,"Activating static UI...");$("#rhizo-right-pop").click(function(){if($("#rhizo-right").is(":visible")){$(this).css("right",0);$("#rhizo-viewport").css("right",5);$("#rhizo-right").css("display","none")}else{$("#rhizo-viewport").css("right",135);$(this).css("right",130);$("#rhizo-right").css("display","")}});this.components_.CONSOLE.activate(a);this.components_.VIEWPORT.activate(a);this.progress_.update(33,
"Loading models...")};
rhizo.ui.component.StandardTemplate.prototype.renderDynamic=function(a,b){this.progress_.update(34,"Creating dynamic controls...");this.components_.LAYOUT.render(this.leftBar_,b);this.progress_.update(38,"Layout engine created.");this.components_.SELECTION_MANAGER.render(this.leftBar_,b);this.progress_.update(42,"Selection manager created.");this.components_.FILTERS.render(this.leftBar_,b);this.progress_.update(46,"Filters created.");this.components_.LEGEND.render(this.leftBar_,b);this.progress_.update(48,
"Legend created.");this.components_.ACTIONS.render(this.rightBar_,b);this.progress_.update(50,"Actions created")};rhizo.ui.component.StandardTemplate.prototype.activateDynamic=function(a){this.progress_.update(51,"Activating dynamic controls...");this.components_.LAYOUT.activate(a);this.components_.SELECTION_MANAGER.activate(a);this.components_.FILTERS.activate(a);this.components_.LEGEND.activate(a);this.components_.ACTIONS.activate(a);this.progress_.update(66,"Rhizosphere controls are ready.")};
rhizo.ui.component.StandardTemplate.prototype.done=function(){this.progress_.update(100,"Rhizosphere ready!")};namespace("rhizo.gviz");rhizo.gviz.Initializer=function(a,b,c){this.dt_=a;this.options_=b||{};this.customRenderer_=c;this.init_()};rhizo.gviz.Initializer.prototype.init_=function(){this.metamodel=this.buildMetaModel_();this.models=this.loadModels_(this.metamodel);this.renderer=this.customRenderer_?this.customRenderer_:this.createDefaultRenderer_(this.metamodel,this.models)};
rhizo.gviz.Initializer.prototype.buildMetaModel_=function(){for(var a={},b=0,c=this.dt_.getNumberOfColumns();b<c;b++){var d=this.dt_.getColumnId(b);a[d]={};a[d].label=this.dt_.getColumnLabel(b);if(a[d].label=="")a[d].label="Column "+d;var e=this.dt_.getColumnType(b);if(e=="number"){e=this.dt_.getColumnRange(b).min;var f=this.dt_.getColumnRange(b).max;if(e==f)a[d].kind=rhizo.meta.Kind.NUMBER;else{a[d].kind=rhizo.meta.Kind.RANGE;a[d].min=e;a[d].max=f}}else if(e=="boolean")a[d].kind=rhizo.meta.Kind.BOOLEAN;
else{e!="string"&&rhizo.warning("Column "+a[d].label+" will be treated as String. Unsupported type: "+e);if(a[d].label.indexOf("CAT")!=-1){a[d].kind=rhizo.meta.Kind.CATEGORY;a[d].label=a[d].label.replace("CAT","").replace(/^\s+|\s+$/g,"");a[d].categories=this.parseCategories_(b);if(a[d].label.indexOf("MUL")!=-1){a[d].label=a[d].label.replace("MUL","").replace(/^\s+|\s+$/g,"");a[d].multiple=true}}else a[d].kind=rhizo.meta.Kind.STRING}this.buildAutoRenderInfo_(a[d],d)}return a};
rhizo.gviz.Initializer.prototype.parseSingleCategory_=function(a){var b={};a=a.split(",");a=$.grep(a,function(c){return c!=""});a=a.forEach(function(c){b[c.replace(/^\s+|\s+$/g,"")]=true});a=[];for(category in b)a.push(category);return a};rhizo.gviz.Initializer.prototype.parseCategories_=function(a){for(var b={},c=0,d=this.dt_.getNumberOfRows();c<d;c++)this.parseSingleCategory_(this.dt_.getValue(c,a)).forEach(function(e){b[e]=true});a=[];for(category in b)a.push(category);return a.sort()};
rhizo.gviz.Initializer.prototype.buildAutoRenderInfo_=function(a,b){var c={},d=false;if(this.options_.arMaster&&this.matchAutoRenderOption_(this.options_.arMaster,a.label,b))d=c.master=true;if(this.options_.arSize&&this.matchAutoRenderOption_(this.options_.arSize,a.label,b)){c.bind=(c.bind?c.bind:"")+"size ";d=true}if(this.options_.arColor&&this.matchAutoRenderOption_(this.options_.arColor,a.label,b)){c.bind=(c.bind?c.bind:"")+"color ";d=true}if(d)a.ar=c};
rhizo.gviz.Initializer.prototype.matchAutoRenderOption_=function(a,b,c){return/^[a-zA-Z]$/.test(a)?a.toLowerCase()==(new String(c)).toLowerCase():b.toLowerCase()==a.toLowerCase()?true:b.replace("CAT","").replace("MUL","").toLowerCase()==a.toLowerCase()};
rhizo.gviz.Initializer.prototype.loadModels_=function(a){for(var b=[],c=0,d=this.dt_.getNumberOfRows();c<d;c++){for(var e={},f=0,g=this.dt_.getNumberOfColumns();f<g;f++){e.id="gviz-"+c;var h=this.dt_.getValue(c,f);if(a[this.dt_.getColumnId(f)].kind==rhizo.meta.Kind.CATEGORY)e[this.dt_.getColumnId(f)]=this.parseSingleCategory_(h);else e[this.dt_.getColumnId(f)]=h}b.push(e)}return b};
rhizo.gviz.Initializer.prototype.createDefaultRenderer_=function(a,b){return new rhizo.autorender.AR(a,b,this.options_.arDefaults,this.options_.arNumFields)};rhizo.gviz.DebugRenderer=function(a){this.dt_=a};rhizo.gviz.DebugRenderer.prototype.render=function(a){for(var b=$("<div />"),c=0,d=this.dt_.getNumberOfColumns();c<d;c++)b.append("<p>"+a[this.dt_.getColumnId(c)]+"</p>");return b};namespace("rhizo.model.loader");rhizo.model.loader.loaders=[];rhizo.model.loader.JS=function(){};rhizo.model.loader.loaders.push(new rhizo.model.loader.JS);
rhizo.model.loader.JS.prototype.setGlobalOptions=function(a){this.globalOptions_=a};rhizo.model.loader.JS.prototype.match=function(a){return/\.js$/.test(a)};rhizo.model.loader.JS.prototype.load=function(a){var b=document.createElement("script");b.src=a;b.type="text/javascript";document.getElementsByTagName("head")[0].appendChild(b)};rhizo.model.loader.GoogleSpreadsheet=function(){};rhizo.model.loader.loaders.push(new rhizo.model.loader.GoogleSpreadsheet);
rhizo.model.loader.GoogleSpreadsheet.prototype.setGlobalOptions=function(a){this.globalOptions_=a};rhizo.model.loader.GoogleSpreadsheet.prototype.match=function(a){return/spreadsheets\.google\.com/.test(a)};rhizo.model.loader.GoogleSpreadsheet.prototype.load=function(a){if(google.visualization){var b=this;(new google.visualization.Query(a)).send(function(c){b.handleQueryResponse_(c)})}else rhizo.error("Google Visualization APIs not available.")};
rhizo.model.loader.GoogleSpreadsheet.prototype.handleQueryResponse_=function(a){if(a.isError())alert("GViz load failed: "+a.getMessage());else{a=new rhizo.gviz.Initializer(a.getDataTable(),this.globalOptions_);rhizo.bootstrap.setRenderer(a.renderer);rhizo.bootstrap.setMetaModel(a.metamodel);rhizo.bootstrap.deploy(a.models)}};rhizo.model.loader.GoogleGadget=function(){};rhizo.model.loader.loaders.push(new rhizo.model.loader.GoogleGadget);
rhizo.model.loader.GoogleGadget.prototype.setGlobalOptions=function(a){this.globalOptions_=a};rhizo.model.loader.GoogleGadget.RESOURCE="__google_gadget";rhizo.model.loader.GoogleGadget.prototype.match=function(a){return RegExp(rhizo.model.loader.GoogleGadget.RESOURCE).test(a)};rhizo.model.loader.GoogleGadget.prototype.load=function(){if(google.visualization)if(typeof _IG_Prefs=="undefined")rhizo.error("Google Gadget APIs not available.");else{var a=new _IG_Prefs,b=this;(new google.visualization.GadgetHelper).createQueryFromPrefs(a).send(function(c){b.handleQueryResponse_(c)})}else rhizo.error("Google Visualization APIs not available.")};
rhizo.model.loader.GoogleGadget.prototype.handleQueryResponse_=rhizo.model.loader.GoogleSpreadsheet.prototype.handleQueryResponse_;rhizo.model.loader.load=function(a,b){for(var c=rhizo.model.loader.loaders,d=0;d<c.length;d++){c[d].setGlobalOptions(b);if(c[d].match(a)){c[d].load(a);return}}alert("No loader available for the resource: "+a)};namespace("rhizo.bootstrap");rhizo.bootstrap.go=function(a,b,c){new rhizo.bootstrap.Bootstrap(a,b);$globalBootstrapper_.go(c)};rhizo.bootstrap.setMetaModel=function(a){$globalBootstrapper_.setMetaModel(a)};
rhizo.bootstrap.setRenderer=function(a){$globalBootstrapper_.setRenderer(a)};rhizo.bootstrap.deploy=function(a){$globalBootstrapper_.deploy(a)};$globalBootstrapper_=null;rhizo.bootstrap.Bootstrap=function(a,b){this.container_=a;this.options_={selectfilter:".rhizo-model:visible"};b&&$.extend(this.options_,b);if(this.options_.autoSize)this.options_.miniLayout=$(document).width()>=600&&$(document).height()>=250?false:true;$globalBootstrapper_=this};
rhizo.bootstrap.Bootstrap.prototype.go=function(a){this.template_=this.options_.miniLayout?new rhizo.ui.component.MiniTemplate:new rhizo.ui.component.StandardTemplate;this.template_.renderChrome(this.container_,this.options_);this.template_.activateChrome(this.options_);rhizo.ui.performanceTuning(this.options_.noAnims);this.project_=new rhizo.Project(this.options_);a=a;if(!a){var b=/source=(.*)$/.exec(document.location.href);if(!b||!b[1])rhizo.error("Unable to identify datasource from location");
else a=unescape(b[1])}a&&rhizo.model.loader.load(a,this.options_)};rhizo.bootstrap.Bootstrap.prototype.setMetaModel=function(a){this.project_.setMetaModel(a)};rhizo.bootstrap.Bootstrap.prototype.setRenderer=function(a){this.project_.setRenderer(a)};rhizo.bootstrap.Bootstrap.prototype.deploy=function(a){this.template_.renderDynamic(this.container_,this.options_);this.template_.activateDynamic(this.options_);this.project_.deploy(a);this.template_.done()};
