var a;function namespace(b){b=b.split(".");for(var c=window,d=0;d<b.length;d++){if(typeof c[b[d]]=="undefined")c[b[d]]={};c=c[b[d]]}}namespace("rhizo.util");rhizo.util.LOG_E_10=Math.log(10);rhizo.util.log10_=function(b){return Math.log(b)/rhizo.util.LOG_E_10};rhizo.util.orderOfMagnitude=function(b){if(b==0)return Number.NaN;return Math.floor(Math.round(rhizo.util.log10_(Math.abs(b))*100)/100)};namespace("rhizo.ui");
rhizo.ui.toHumanLabel=function(b){if(typeof b=="number"&&b!=0){var c=["","K","M","G","T","P","E","Z","Y"],d=rhizo.util.orderOfMagnitude(b);if(d<0)return b.toFixed(-d);d=parseInt(d/3,10);c=c[d]||"";return(b/Math.pow(10,d*3)).toPrecision(3)+c}else return b};
rhizo.ui.performanceTuning=function(b){if(b){jQuery.fx.off=true;jQuery.fn.extend({move:function(c,d,e,f){$(this).css("top",c);$(this).css("left",d);e!=null&&$(this).css("bottom",e);f!=null&&$(this).css("right",f)}})}else jQuery.fn.extend({move:function(c,d,e,f){if(jQuery.fx.off){$(this).css("top",c);$(this).css("left",d);e!=null&&$(this).css("bottom",e);f!=null&&$(this).css("right",f)}else{c={top:c,left:d};if(e!=null)c.bottom=e;if(f!=null)c.right=f;$(this).animate(c,1E3)}}})};
rhizo.ui.expandable=function(b,c){return typeof b.expandable=="boolean"?b.expandable:typeof b.expandable=="function"?b.expandable(c):false};
rhizo.ui.initExpandable=function(b,c){if(rhizo.ui.expandable(b,c)){$(".rhizo-model").hover(function(){$(this).children(".rhizo-expand-model").css("display","")},function(){$(this).children(".rhizo-expand-model").css("display","none")});$(".rhizo-expand-model").click(function(){var d=$(this).attr("id").replace(/rhizo-expand-/,"");d=$p.model(d);d.expanded=!d.expanded;var e=b.render(d.unwrap(),d.expanded,c);d.rendering.css("z-index",d.expanded?60:50);d.rendering.children(":not(.rhizo-expand-model)").remove();
d.rendering.append(e)})}};namespace("rhizo.meta");rhizo.meta.StringKind=function(){};rhizo.meta.StringKind.prototype.renderFilter=function(b,c){var d=$("<input type='text' />");$(d).change(function(){$p.filter(c,$(this).val())});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d))};rhizo.meta.StringKind.prototype.survivesFilter=function(b,c){return b!=""&&c.toLowerCase().indexOf(b.toLowerCase())!=-1};
rhizo.meta.StringKind.prototype.cluster=function(b){return{key:b.toUpperCase().charAt(0),label:b.toUpperCase().charAt(0)}};rhizo.meta.NumberKind=function(){};rhizo.meta.NumberKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.NumberKind.prototype.survivesFilter=function(b,c){b=parseInt(b,10);return isNaN(b)?true:b==c};rhizo.meta.NumberKind.prototype.compare=function(b,c){return parseInt(b,10)-parseInt(c,10)};
rhizo.meta.NumberKind.prototype.cluster=function(b){var c=parseInt(b,10);if(parseFloat(b)<=10)return{key:c,label:c.toString()};for(var d=0;c>=10;){c=parseInt(c/10);d++}d=Math.pow(10,d);c=parseInt(b/d,10)*d;b=parseInt(b/d+1,10)*d;return{key:c,label:c.toString()+" - "+b.toString()}};
rhizo.meta.DateKind=function(b){this.monthMap_=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];this.clusterby_=b||"y";if(this.clusterby_!="y"&&this.clusterby_!="m"&&this.clusterby_!="d")this.clusterby_="y"};
rhizo.meta.DateKind.prototype.renderFilter=function(b,c){var d=$("<select style='vertical-align:top' />");d.append("<option value='yyyy'>yyyy</option>");for(var e=b.minYear;e<=b.maxYear;e++)d.append("<option value='"+e+"'>"+e+"</option>");var f=$("<select style='vertical-align:top' />");f.append("<option value='mm'>mm</option>");for(e=0;e<this.monthMap_.length;e++)f.append("<option value='"+e+"'>"+this.monthMap_[e]+"</option>");var g=$("<select style='vertical-align:top' />");g.append("<option value='dd'>dd</option>");
for(e=1;e<=31;e++)g.append("<option value='"+e+"'>"+e+"</option>");$(d).add($(f)).add($(g)).change(function(){$p.filter(c,[$(d).val(),$(f).val(),$(g).val()])});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d)).append(" - ").append($(f)).append(" - ").append($(g))};
rhizo.meta.DateKind.prototype.survivesFilter=function(b,c){var d=parseInt(b[0],10),e=parseInt(b[1],10);b=parseInt(b[2],10);return c=(isNaN(d)||c.getFullYear()==d)&&(isNaN(e)||c.getMonth()==e)&&(isNaN(b)||c.getDate()==b)};
rhizo.meta.DateKind.prototype.cluster=function(b){return this.clusterby_=="y"?{key:b.getFullYear()+"-00-01",label:b.getFullYear()}:this.clusterby_=="m"?{key:b.getFullYear()+"-"+this.addZero_(b.getMonth())+"-01",label:b.getFullYear()+"-"+this.monthMap_[b.getMonth()]}:{key:b.getFullYear()+"-"+this.addZero_(b.getMonth())+"-"+this.addZero_(b.getDate()),label:b.getFullYear()+"-"+this.monthMap_[b.getMonth()]+"-"+b.getDate()}};
rhizo.meta.DateKind.prototype.addZero_=function(b){b=b.toString();if(b.length==1)b="0"+b;return b};rhizo.meta.RangeKind=function(){};a=rhizo.meta.RangeKind.prototype;
a.renderFilter=function(b,c){var d=$("<div id='rhizo-slider-"+c+"' />"),e=$("<strong>"+this.toHumanLabel_(b.min)+"</strong>"),f=$("<strong>"+this.toHumanLabel_(b.max)+"</strong>"),g=this.toFilterScale_(b.min),h=this.toFilterScale_(b.max),i;if(b.stepping)i=this.toFilterScale_(b.stepping);i=function(){var j=this;return function(l,n){l=$("#rhizo-slider-"+c).slider("values",0);var m=$("#rhizo-slider-"+c).slider("values",1);if(l==n.value){e.text(j.toHumanLabel_(j.toModelScale_(l))).addClass("rhizo-slider-moving");
f.removeClass("rhizo-slider-moving")}else{f.text(j.toHumanLabel_(j.toModelScale_(m))).addClass("rhizo-slider-moving");e.removeClass("rhizo-slider-moving")}}}.call(this);var k=function(){var j=this;return function(){var l=Math.max($("#rhizo-slider-"+c).slider("values",0),g),n=Math.min($("#rhizo-slider-"+c).slider("values",1),h);e.text(j.toHumanLabel_(j.toModelScale_(l))).removeClass("rhizo-slider-moving");f.text(j.toHumanLabel_(j.toModelScale_(n))).removeClass("rhizo-slider-moving");$p.filter(c,{min:l,
max:n})}}.call(this);$(d).slider({stepping:b.stepping,steps:b.steps,range:true,min:g,max:h,slide:i,stop:k,orientation:"horizontal",values:[g,h]});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(e)).append(" to ").append($(f)).append($(d))};a.survivesFilter=function(b,c){var d=this.toModelScale_(b.min);b=this.toModelScale_(b.max);return c>=d&&c<=b};a.compare=rhizo.meta.NumberKind.prototype.compare;a.cluster=rhizo.meta.NumberKind.prototype.cluster;a.toModelScale_=function(b){return b};
a.toFilterScale_=function(b){return b};a.toHumanLabel_=function(b){return b};rhizo.meta.BooleanKind=function(){};rhizo.meta.BooleanKind.prototype.renderFilter=function(b,c){var d=$("<select />");d.append("<option value=''>-</option>");d.append("<option value='true'>Yes</option>");d.append("<option value='false'>No</option>");$(d).change(function(){$p.filter(c,$(this).val())});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d))};
rhizo.meta.BooleanKind.prototype.survivesFilter=function(b,c){b=b=="true";return b==c};rhizo.meta.BooleanKind.prototype.compare=function(b,c){return b?c?0:-1:c?1:0};rhizo.meta.CategoryKind=function(){};
rhizo.meta.CategoryKind.prototype.renderFilter=function(b,c){var d=$("<select "+(b.multiple?'multiple size="4" ':"")+" style='vertical-align:top' />");d.append("<option value=''>-</option>");b.categories.forEach(function(e){d.append("<option value='"+e+"'>"+e+"</option>")});$(d).change(function(){var e=[$(this).val()];if(b.multiple)e=$.grep($(this).val(),function(f){return f!=""});$p.filter(c,e)});return $("<div class='rhizo-filter' />").append(b.label+": ").append($(d))};
rhizo.meta.CategoryKind.prototype.survivesFilter=function(b,c){var d=false;b.forEach(function(e){if(c.indexOf(e)!=-1)d=true});return d};rhizo.meta.CategoryKind.prototype.cluster=function(b){return{key:b.length==0?"Nothing":b,label:b.length==0?"Nothing":b}};rhizo.meta.CategoryKind.prototype.compare=function(b,c){return b.length-c.length};
rhizo.meta.sortBy=function(b,c,d){return function(e,f){e=e.unwrap();f=f.unwrap();var g=d?-1:1;return c.compare?c.compare(e[b],f[b])*g:(e[b]<f[b]?-1:e[b]>f[b]?1:0)*g}};rhizo.meta.sortByKind=function(b,c){return function(d,e){var f=c?-1:1;return b.compare?b.compare(d,e)*f:(d<e?-1:d>e?1:0)*f}};rhizo.meta.Kind={STRING:new rhizo.meta.StringKind,NUMBER:new rhizo.meta.NumberKind,DATE:new rhizo.meta.DateKind,RANGE:new rhizo.meta.RangeKind,BOOLEAN:new rhizo.meta.BooleanKind,CATEGORY:new rhizo.meta.CategoryKind};
namespace("rhizo");rhizo.disableLogging=function(){rhizo.log=function(){}};
rhizo.log=function(b,c){var d=c||"info",e="#888";switch(d){case "error":e="#ff0000";break;case "warning":e="#ffff00";break}var f=new Date;f=f.getHours()+":"+f.getMinutes()+":"+f.getSeconds()+" ";b=$("<p class='rhizo-log-"+d+"'>"+f+b+"</p>");$("#rhizo-console-contents").prepend(b);c&&b.effect("highlight",{color:e},1E3);if(!$("#rhizo-console-contents").is(":visible")&&c)$("#rhizo-right").is(":visible")?$("#rhizo-console-header").effect("highlight",{color:e},1E3):$("#rhizo-right-pop").effect("highlight",
{color:e},1E3)};rhizo.error=function(b){rhizo.log(b,"error")};rhizo.warning=function(b){rhizo.log(b,"warning")};rhizo.meta.DecimalKind=function(b){this.precision_=b||2};rhizo.meta.DecimalKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.DecimalKind.prototype.survivesFilter=function(b,c){b=parseFloat(b);return isNaN(b)?true:b.toFixed(this.precision_)==c.toFixed(this.precision_)};rhizo.meta.DecimalKind.prototype.compare=function(b,c){return parseFloat(b)-parseFloat(c)};
rhizo.meta.DecimalKind.prototype.cluster=function(b){b=parseFloat(b.toFixed(this.precision_),10);var c=rhizo.util.orderOfMagnitude(b);if(isNaN(c))return{key:0,label:(new Number(0)).toFixed(this.precision_)};b=Math.pow(10,c);c=Math.pow(10,c+1);return{key:b,label:rhizo.ui.toHumanLabel(b)+" - "+rhizo.ui.toHumanLabel(c)}};rhizo.meta.DecimalRangeKind=function(b){this.precision_=b||2;this.scale_=Math.pow(10,this.precision_)};a=rhizo.meta.DecimalRangeKind.prototype;a.renderFilter=rhizo.meta.RangeKind.prototype.renderFilter;
a.survivesFilter=rhizo.meta.RangeKind.prototype.survivesFilter;a.compare=rhizo.meta.DecimalKind.prototype.compare;a.cluster=rhizo.meta.DecimalKind.prototype.cluster;a.toModelScale_=function(b){return parseFloat((b/this.scale_).toFixed(this.precision_))};a.toFilterScale_=function(b){return parseInt(b*this.scale_,10)};a.toHumanLabel_=rhizo.meta.RangeKind.prototype.toHumanLabel_;rhizo.meta.LogarithmRangeKind=function(b){this.precision_=b||2;this.scale_=Math.pow(10,this.precision_)};a=rhizo.meta.LogarithmRangeKind.prototype;
a.renderFilter=rhizo.meta.DecimalRangeKind.prototype.renderFilter;a.survivesFilter=rhizo.meta.DecimalRangeKind.prototype.survivesFilter;a.compare=rhizo.meta.DecimalRangeKind.prototype.compare;a.cluster=rhizo.meta.DecimalRangeKind.prototype.cluster;a.toModelScale_=function(b){return parseFloat(Math.pow(10,b/this.scale_).toFixed(this.precision_))};a.toFilterScale_=function(b){return parseInt(rhizo.util.log10_(b)*this.scale_,10)};a.toHumanLabel_=rhizo.meta.DecimalRangeKind.prototype.toHumanLabel_;
rhizo.meta.StringArrayKind=function(){};rhizo.meta.StringArrayKind.prototype.renderFilter=rhizo.meta.StringKind.prototype.renderFilter;rhizo.meta.StringArrayKind.prototype.survivesFilter=function(b,c){if(b!="")for(var d=0;d<c.length;d++)if(c[d].toLowerCase().indexOf(b.toLowerCase())!=-1)return true;return false};rhizo.meta.StringArrayKind.prototype.cluster=function(){return{key:"undefined",label:"Clustering unsupported for this datatype."}};rhizo.meta.Kind.DECIMAL=new rhizo.meta.DecimalKind;
rhizo.meta.Kind.DECIMALRANGE=new rhizo.meta.DecimalRangeKind;rhizo.meta.Kind.LOGARITHMRANGE=new rhizo.meta.LogarithmRangeKind;rhizo.meta.Kind.STRINGARRAY=new rhizo.meta.StringArrayKind;namespace("rhizo.model");rhizo.model.SuperModel=function(b,c){this.model=b;this.id=b.id;this.selected=c||false;this.filters_={};this.rendering=null;this.expanded=false};a=rhizo.model.SuperModel.prototype;a.unwrap=function(){return this.model};a.toString=function(){return this.model.toString()};
a.isFiltered=function(b){if(b)return this.filters_[b]||false;else{b=0;for(key in this.filters_)b++;return b!=0}};a.filter=function(b){this.filters_[b]=true};a.resetFilter=function(b){delete this.filters_[b]};
rhizo.model.kickstart=function(b,c,d){var e=c.render(b.unwrap(),b.expanded,d),f=$('<div class="rhizo-model"></div>');f.append(e);if(rhizo.ui.expandable(c,d)){c=$('<div class="rhizo-expand-model" style="display:none" id="rhizo-expand-'+b.id+'"></div>');$(f).append(c)}b.rendering=f;$(f).attr("id",b.id);$(f).dblclick(function(){$p.isSelected(this.id)?$p.unselect(this.id):$p.select(this.id)});$(f).draggable({opacity:0.7,cursor:"pointer",zIndex:1E4,distance:3,start:function(g,h){$p.toggleSelection("disable");
$("#"+h.helper[0].id).data("dropTop0",parseInt($("#"+h.helper[0].id).css("top"),10));$("#"+h.helper[0].id).data("dropLeft0",parseInt($("#"+h.helper[0].id).css("left"),10));if($p.isSelected(h.helper[0].id))for(id in $p.allSelected()){$("#"+id).data("top0",parseInt($("#"+id).css("top"),10)-parseInt($(h.helper[0]).css("top"),10));$("#"+id).data("left0",parseInt($("#"+id).css("left"),10)-parseInt($(h.helper[0]).css("left"),10));$("#"+id).data("dropTop0",parseInt($("#"+id).css("top"),10));$("#"+id).data("dropLeft0",
parseInt($("#"+id).css("left"),10))}},drag:function(g,h){if($p.isSelected(h.helper[0].id))for(id in $p.allSelected())if(id!=h.helper[0].id){$("#"+id).css("top",$("#"+id).data("top0")+h.position.top);$("#"+id).css("left",$("#"+id).data("left0")+h.position.left)}},stop:function(g,h){$p.toggleSelection("enable");if($p.isSelected(h.helper[0].id))for(id in $p.allSelected()){$("#"+id).removeData("top0");$("#"+id).removeData("left0")}},refreshPositions:false});return f};namespace("rhizo.layout");
rhizo.layout.metaModelKeySelector=function(b){b=$("<select id='"+b+"' />");if($p&&$p.metaModel())for(key in $p.metaModel())b.append("<option value='"+key+"'>"+$p.metaModel()[key].label+"</option>");return b};rhizo.layout.NoLayout=function(){};rhizo.layout.NoLayout.prototype.layout=function(){};rhizo.layout.NoLayout.prototype.toString=function(){return"-"};rhizo.layout.FlowLayout=function(b,c){this.top=b||5;this.left=c||5};
rhizo.layout.FlowLayout.prototype.layout=function(b,c,d){b=$(b).width();var e=0,f=$("#rhizo-flowlayout-order").val(),g=$("#rhizo-flowlayout-desc:checked").length>0;if(f){rhizo.log("Sorting by "+f);c.sort(rhizo.meta.sortBy(f,d[f].kind,g))}d=0;for(f=c.length;d<f;d++){g=$(c[d].rendering);e=Math.max(e,g.height());if(this.left+g.width()>b){this.left=5;this.top+=e+5;e=g.height()}g.move(this.top,this.left);this.left+=g.width()+5}this.top+=e};
rhizo.layout.FlowLayout.prototype.cleanup=function(){this.top=this.left=5};rhizo.layout.FlowLayout.prototype.details=function(){return $("<div />").append("Ordered by: ").append(rhizo.layout.metaModelKeySelector("rhizo-flowlayout-order")).append(" desc?").append('<input type="checkbox" id="rhizo-flowlayout-desc" />')};rhizo.layout.FlowLayout.prototype.toString=function(){return"List"};rhizo.layout.ScrambleLayout=function(){};
rhizo.layout.ScrambleLayout.prototype.layout=function(b,c,d,e){if(!(e&&e.filter)){d=Math.round($(b).width()*0.3);e=Math.round($(b).height()*0.3);for(var f=0,g=c.length;f<g;f++){var h=$(c[f].rendering),i=Math.round($(b).height()/3+Math.random()*e*2-e),k=Math.round($(b).width()/3+Math.random()*d*2-d);h.move(i,k)}}};rhizo.layout.ScrambleLayout.prototype.toString=function(){return"Random"};rhizo.layout.BucketLayout=function(){this.internalFlowLayout_=new rhizo.layout.FlowLayout;this.bucketHeaders_=[]};
a=rhizo.layout.BucketLayout.prototype;
a.layout=function(b,c,d,e){var f=$("#rhizo-bucketlayout-desc:checked").length>0,g=$("#rhizo-bucketlayout-bucket").val();if(d[g]){rhizo.log("Bucketing by "+g);var h,i;if(d[g].cluster){h=d[g].cluster;i=d[g]}else{h=d[g].kind.cluster;i=d[g].kind}for(var k={},j={},l=0,n=c.length;l<n;l++){var m=c[l].unwrap()[g],o=m;if(h){o=h.call(i,m);m=o.key;o=o.label}if(!k[m]){k[m]=[];j[m]=o}k[m].push(c[l])}c=[];for(m in k)c.push(m);c.sort(rhizo.meta.sortByKind(d[g].kind,f));c.forEach(function(p){this.renderBucketHeader_(b,j[p]);
this.internalFlowLayout_.layout(b,k[p],d,e);this.internalFlowLayout_.top+=10;this.internalFlowLayout_.left=5},this)}else rhizo.error("layoutBy attribute does not match any property")};a.renderBucketHeader_=function(b,c){c=$("<div class='rhizo-bucket-header'>"+c+"</div>");c.css("position","absolute").css("left",5).css("top",this.internalFlowLayout_.top);this.bucketHeaders_.push(c);$(b).append(c);this.internalFlowLayout_.top+=c.height()+5};a.details=function(){return $("<div />").append("Group by: ").append(rhizo.layout.metaModelKeySelector("rhizo-bucketlayout-bucket")).append(" desc?").append('<input type="checkbox" id="rhizo-bucketlayout-desc" />')};
a.cleanup=function(){this.internalFlowLayout_.cleanup();this.bucketHeaders_.forEach(function(b){$(b).remove()});this.bucketHeaders_=[]};a.toString=function(){return"Buckets"};rhizo.layout.layouts={no:new rhizo.layout.NoLayout,flow:new rhizo.layout.FlowLayout,scramble:new rhizo.layout.ScrambleLayout,bucket:new rhizo.layout.BucketLayout};namespace("rhizo.autorender");
rhizo.autorender.AR=function(b,c,d,e){this.metamodel_=b;this.metamodelFields_=0;for(var f in this.metamodel_)this.metamodelFields_++;this.fallbackToDefaults_=typeof d=="undefined"?true:d;this.locateFields_();b=0;if(this.sizeField_){this.sizeRange_=this.locateMinMax_(c,this.sizeField_);b++}if(this.colorField_){this.colorRange_=this.locateMinMax_(c,this.colorField_);b++}this.numfields_=typeof e=="undefined"?5:Math.max(e,b)};a=rhizo.autorender.AR.prototype;a.getSizeRange=function(){return this.sizeRange_};
a.getColorRange=function(){return this.colorRange_};a.locateFields_=function(){for(key in this.metamodel_){this.masterField_=this.masterField_||this.getArField_(key,"master","true");this.sizeField_=this.sizeField_||this.getArField_(key,"bind","size");this.colorField_=this.colorField_||this.getArField_(key,"bind","color")}this.locateDefaultFields_()};a.getArField_=function(b,c,d){if(this.metamodel_[b].ar)if((c=this.metamodel_[b].ar[c])&&c.toString().indexOf(d)!=-1)return b;return null};
a.locateDefaultFields_=function(){for(key in this.metamodel_){if(!this.masterField_)this.masterField_=key;if(!this.fallbackToDefaults_)break;if(!this.sizeField_&&(this.metamodel_[key].kind==rhizo.meta.Kind.NUMBER||this.metamodel_[key].kind==rhizo.meta.Kind.RANGE))this.sizeField_=key;else if(this.sizeField_)if(!this.colorField_&&(this.metamodel_[key].kind==rhizo.meta.Kind.NUMBER||this.metamodel_[key].kind==rhizo.meta.Kind.RANGE))this.colorField_=key}};
a.locateMinMax_=function(b,c){if(this.metamodel_[c].kind==rhizo.meta.Kind.RANGE)return{min:this.metamodel_[c].min,max:this.metamodel_[c].max,label:this.metamodel_[c].label};else{var d=Number.POSITIVE_INFINITY,e=Number.NEGATIVE_INFINITY;b.forEach(function(f){d=Math.min(d,f[c]);e=Math.max(e,f[c])});return{min:d,max:e,label:this.metamodel_[c].label}}};a.getClass_=function(b,c,d,e){b=parseInt((b-c.min)/(c.max-c.min)*5,10);return"ar-"+e+"-"+b.toString()+(d?"m":"")};
a.getFontClass_=function(b,c,d){return this.getClass_(b,c,d,"fon")};a.getColorClass_=function(b,c,d){return this.getClass_(b,c,d,"col")};a.renderSingleModelKey_=function(b,c){var d=[];d.push('<p><span class="dim">');d.push(this.metamodel_[b].label);d.push("</span>: ");d.push(c);d.push("</p>");return d.join("")};a.expandable=function(b){b=(b=b&&b.miniLayout)?1:this.numfields_+1;return this.metamodelFields_>b};
a.render=function(b,c,d){d=d&&d.miniLayout;var e="ar-col-0"+(d?"m":"");if(this.colorField_)e=this.getColorClass_(b[this.colorField_],this.colorRange_,d);var f="ar-fon-0"+(d?"m":"");if(this.sizeField_)f=this.getFontClass_(b[this.sizeField_],this.sizeRange_,d);if(d&&!c)return $("<div class='"+e+"'><span class='"+f+"'>"+b[this.masterField_]+"</span></div>");else{html=[];html.push("<div class='"+e+"'>");html.push("<span class='"+f+"'>"+b[this.masterField_]+"</span>");d=0;if(this.sizeField_){html.push(this.renderSingleModelKey_(this.sizeField_,
b[this.sizeField_]));d++}if(this.colorField_&&this.colorField_!=this.sizeField_){html.push(this.renderSingleModelKey_(this.colorField_,b[this.colorField_]));d++}for(key in this.metamodel_){if(d>=this.numfields_&&!c)break;if(key!=this.sizeField_&&key!=this.colorField_&&key!=this.masterField_){d++;html.push(this.renderSingleModelKey_(key,b[key]))}}html.push("</div>");return $(html.join(""))}};namespace("rhizo");$p=null;
rhizo.Project=function(b){this.models_=[];this.modelsMap_={};this.selectionMap_={};this.layoutName_="flow";this.layouEngine_=null;this.options_=b||{};$p=this};a=rhizo.Project.prototype;a.deploy=function(b){b&&this.addModels_(b)&&this.finalizeUI_();rhizo.log("*** Ready!")};a.addModels_=function(b){this.models_=jQuery.map(b,function(c){return new rhizo.model.SuperModel(c)});if(!this.checkModels_())return false;this.buildModelsMap_();this.models_.forEach(this.initializeModel_,this);return true};
a.finalizeUI_=function(){rhizo.ui.initExpandable(this.renderer_,this.options_);jQuery.fx.off=true;this.layout(this.layoutName_);this.alignVisibility(true)};a.model=function(b){return this.modelsMap_[b]};a.metaModel=function(){return this.metaModel_};a.setMetaModel=function(b){this.metaModel_=b};a.renderer=function(){return this.renderer_};a.setRenderer=function(b){this.renderer_=b};a.resetAllFilter=function(b){this.models_.forEach(function(c){c.resetFilter(b)})};
a.select=function(b){var c=this.model(b);this.selectionMap_[b]=c;c.selected=true;$("#"+b).addClass("ui-selected");rhizo.log("Selected "+c)};a.unselect=function(b){var c=this.model(b);this.selectionMap_[b]=null;delete this.selectionMap_[b];c.selected=false;$("#"+b).removeClass("ui-selected");rhizo.log("Unselected "+c)};a.unselectAll=function(){for(id in this.selectionMap_)this.unselect(id)};a.isSelected=function(b){return this.selectionMap_[b]};a.allSelected=function(){return this.selectionMap_};
a.allUnselected=function(){return $.grep(this.models_,function(b){return!$p.selectionMap_[b.id]})};a.toggleSelection=function(b){$("#rhizo-viewport").selectable(b)};a.checkModels_=function(){rhizo.log("Checking models...");var b=true;this.models_.forEach(function(c){if(!c.id){b=false;rhizo.error("Verify your models: missing ids.")}});return b};a.buildModelsMap_=function(){rhizo.log("Building models map...");this.models_.forEach(function(b){this.modelsMap_[b.id]=b},this)};
a.initializeModel_=function(b){b=rhizo.model.kickstart(b,this.renderer_,this.options_);$(b).css("position","absolute").css("top",0).css("left",0).css("display","none");$("#rhizo-universe").append(b)};
a.layout=function(b,c){var d=b?b:this.layoutName_;if(b=rhizo.layout.layouts[d]){rhizo.log("layouting...");this.layoutEngine_&&this.layoutEngine_.cleanup&&this.layoutEngine_.cleanup();this.layoutName_=d;this.layoutEngine_=b;$("#rhizo-universe").move(0,0,0,0);d=jQuery.grep(this.models_,function(e){return!e.isFiltered()});b.layout("#rhizo-universe",d,this.metaModel_,c)}else rhizo.error("Invalid layout engine:"+d)};
a.filter=function(b,c){this.metaModel_[b]||rhizo.error("Invalid filtering key: "+b);c!=""?this.models_.forEach(function(d){this.metaModel_[b].kind.survivesFilter(c,d.unwrap()[b])?d.resetFilter(b):d.filter(b)},this):this.models_.forEach(function(d){d.resetFilter(b)});this.alignVisibility();this.layout(null,{filter:true})};
a.alignVisibility=function(b){var c=0;this.models_.forEach(function(d){c+=d.isFiltered()?0:1;d.isFiltered()&&$("#"+d.id).fadeOut()});if(!b)jQuery.fx.off=this.options_.noAnims||c>200;this.models_.forEach(function(d){d.isFiltered()||$("#"+d.id).fadeIn()});if(b)jQuery.fx.off=this.options_.noAnims||c>200};rhizo.layout.TreeLayout=function(){};a=rhizo.layout.TreeLayout.prototype;
a.layout=function(b,c,d){var e=$("#rhizo-treelayout-direction").val()=="ver";this.treePainter_=new rhizo.layout.TreePainter(e);e=$("#rhizo-treelayout-parentKey").val();if(d[e]){rhizo.log("Creating tree by "+e);try{var f=this.buildTree_(c,e);c={left:0,top:0};d=0;for(var g in f){var h=this.treePainter_.calculateBoundingRect_(f[g]),i=this.treePainter_.toAbsoluteCoords_(h);if(c.left+i.w>$(b).width()){c.left=0;c.top+=d+(d>0?5:0)}this.treePainter_.draw_(b,f[g],this.treePainter_.toRelativeCoords_(c));c.left+=
i.w;d=Math.max(d,i.h)}}catch(k){if(k.name=="TreeCycleException")rhizo.error(k);else throw k;}}else rhizo.error("parentKey attribute does not match any property")};
a.buildTree_=function(b,c){for(var d={},e=0,f=b.length;e<f;e++)d[b[e].id]=new rhizo.layout.TreeNode(b[e]);var g={};e=0;for(f=b.length;e<f;e++)if(!d[b[e].unwrap().id].validated)for(var h={},i=b[e].unwrap();1;){if(h[i.id])throw new rhizo.layout.TreeCycleException("Tree is invalid: cycle detected");h[i.id]=i;d[i.id].validated=true;var k=this.findFirstVisibleParent_($p.model(i[c]),c);if(k){var j=k.unwrap();d[j.id].addChild(d[i.id]);i=k.unwrap()}else{g[i.id]=d[i.id];break}}return g};
a.findFirstVisibleParent_=function(b,c){if(!b)return null;for(var d={};b.isFiltered();){if(d[b.id])throw new rhizo.layout.TreeCycleException("Tree is invalid: hidden cycle detected");d[b.id]=b;b=$p.model(b.unwrap()[c]);if(!b)return null}return b};a.details=function(){var b=$("<select id='rhizo-treelayout-direction' />");b.append("<option value='hor'>Horizontally</option>");b.append("<option value='ver'>Vertically</option>");return $("<div />").append(b).append(" arrange by: ").append(rhizo.layout.metaModelKeySelector("rhizo-treelayout-parentKey"))};
a.toString=function(){return"Tree"};a.cleanup=function(){this.treePainter_&&this.treePainter_.cleanup_()};rhizo.layout.TreePainter=function(b){this.connectors_=[];if(this.vertical_=b){this.gdName_="top";this.odName_="left";this.gdLength_="height";this.odLength_="width"}else{this.gdName_="left";this.odName_="top";this.gdLength_="width";this.odLength_="height"}};a=rhizo.layout.TreePainter.prototype;a.gd_=function(b){return this.vertical_?b.height():b.width()};
a.od_=function(b){return this.vertical_?b.width():b.height()};a.toAbsoluteCoords_=function(b){return this.vertical_?{w:b.od,h:b.gd}:{w:b.gd,h:b.od}};a.toRelativeCoords_=function(b){return this.vertical_?{gd:b.top,od:b.left}:{gd:b.left,od:b.top}};a.packedCenter_=function(b,c){return{gd:b.gd+5+this.gd_(c)/2,od:b.od+this.od_(c)/2}};a.evenCenter_=function(b,c,d){return{gd:b.gd+d.gd/2,od:b.od+5+this.od_(c)/2}};
a.calculateBoundingRect_=function(b){var c={gd:0,od:0};for(var d in b.childs){var e=this.calculateBoundingRect_(b.childs[d]);c.gd+=e.gd+5;c.od=Math.max(c.od,e.od)}d=b.superModel.rendering;b.boundingRect={od:this.od_(d)+c.od+25,gd:Math.max(this.gd_(d),c.gd)+5};return b.boundingRect};
a.draw_=function(b,c,d,e,f){var g=$(c.superModel.rendering);if(this.vertical_){g.move(d.gd+5,d.od);e!=null&&this.drawConnector_(b,this.packedCenter_(d,g),this.packedCenter_(e,f.superModel.rendering))}else{g.move(d.od+5,d.gd+(c.boundingRect.gd-this.gd_(g))/2);e!=null&&this.drawConnector_(b,this.evenCenter_(d,g,c.boundingRect),this.evenCenter_(e,f.superModel.rendering,f.boundingRect))}e=d.gd;for(var h in c.childs){f=c.childs[h];var i={od:d.od+this.od_(g)+20,gd:e};this.draw_(b,f,i,d,c);e+=f.boundingRect.gd+
5}};a.drawConnector_=function(b,c,d){var e=$("<div class='rhizo-tree-connector' />");e.css("position","absolute").css(this.gdName_,Math.min(c.gd,d.gd)).css(this.odName_,d.od).css(this.odLength_,2).css(this.gdLength_,Math.abs(d.gd-c.gd));var f=$("<div class='rhizo-tree-connector' />");f.css("position","absolute").css(this.gdName_,c.gd).css(this.odName_,d.od).css(this.gdLength_,2).css(this.odLength_,Math.abs(d.od-c.od));this.connectors_.push(e);this.connectors_.push(f);$(b).append(e);$(b).append(f)};
a.cleanup_=function(){this.connectors_.forEach(function(b){$(b).remove()});this.connectors_=[]};rhizo.layout.TreeNode=function(b,c){this.superModel=b;this.id=b.id;this.childs=c||{};this.validated=false};rhizo.layout.TreeNode.prototype.addChild=function(b){this.childs[b.id]||(this.childs[b.id]=b)};rhizo.layout.TreeCycleException=function(b){this.message=b;this.name="TreeCycleException"};rhizo.layout.TreeCycleException.prototype.toString=function(){return this.name+": "+this.message};
rhizo.layout.layouts.tree=new rhizo.layout.TreeLayout;namespace("rhizo.ui.component");rhizo.ui.component.Progress=function(b){b=$('<div id="rhizo-progressbar-panel"></div>').appendTo(b);var c=$('<div id="rhizo-progressbar"></div>').appendTo(b);this.pbar_=c.progressbar({value:1});$('<div id="rhizo-progressbar-text">Loading...</div>').appendTo(b)};rhizo.ui.component.Progress.prototype.update=function(b,c){this.pbar_.progressbar("value",b);c&&$("#rhizo-progressbar-text").text(c);b>=100&&this.destroy_()};
rhizo.ui.component.Progress.prototype.destroy_=function(){$("#rhizo-progressbar-panel").is(":visible")?setTimeout(function(){$("#rhizo-progressbar-panel").fadeOut(500,function(){$(this).remove()})},1E3):$("#rhizo-progressbar-panel").remove()};rhizo.ui.component.Logo=function(){};rhizo.ui.component.Logo.prototype.render=function(b){$('<div id="rhizo-header"><h1>Rhizosphere</h1><p>by <a href="mailto:battlehorse@gmail.com">Riccardo Govoni</a> (c) 2009<br /><a href="http://sites.google.com/site/rhizosphereui/" target="_blank">Project info</a>&nbsp;<a href="http://sites.google.com/site/rhizosphereui/Home/documentation" target="_blank" style="font-weight:bold; text-decoration: underline">I Need Help!</a></p></div>').appendTo(b)};
rhizo.ui.component.Viewport=function(){};a=rhizo.ui.component.Viewport.prototype;
a.render=function(b,c){c=c||{};$('<div id="rhizo-viewport"><div id="rhizo-universe"></div><div id="rhizo-scroll-trigger" title="Click to pan around" ></div></div><div id="rhizo-scroll-overlay" style="display: none"><div><button id="rhizo-scroll-done">Done</button></div></div>').appendTo(b);if(c.miniLayout){$("#rhizo-viewport").addClass("rhizo-miniRender");$("#rhizo-scroll-overlay").addClass("rhizo-miniRender")}else $("#rhizo-viewport").css("left",300).css("right",5)};
a.activate=function(b){this.activatePanning_();this.activateSelectionSupport_(b)};
a.activatePanning_=function(){var b={top:$("#rhizo-viewport").offset().top+$("#rhizo-universe").offset().top,left:$("#rhizo-viewport").offset().left+$("#rhizo-universe").offset().left};$("#rhizo-scroll-trigger").click(function(){$(this).hide();var c=$("#rhizo-viewport");$("#rhizo-scroll-overlay").css("left",c.css("left")).css("top",c.css("top")).css("width",c.width()).css("height",c.height()).css("z-index",99).css("display","");$("#rhizo-scroll-overlay").draggable({helper:function(){return $("<div />")},
start:function(){var d=$("#rhizo-universe").offset();$("#rhizo-universe").data("top0",d.top).data("left0",d.left)},drag:function(d,e){var f=$("#rhizo-universe");f.offset();d=e.position.top+f.data("top0")-b.top;e=e.position.left+f.data("left0")-b.left;$("#rhizo-universe").css("top",d).css("bottom",-d).css("left",e).css("right",-e)},refreshPositions:false})});$("#rhizo-scroll-done").click(function(){$("#rhizo-scroll-overlay").css("z-index",-1).css("display","none");$("#rhizo-scroll-trigger").show()})};
a.isOnEmptySpace=function(b){return b.target.id=="rhizo-viewport"||b.target.id=="rhizo-universe"};a.activateSelectionSupport_=function(b){$("#rhizo-viewport").selectable({selected:function(d,e){e.selected.id&&$p.select(e.selected.id)},unselected:function(d,e){e.unselected.id&&$p.unselect(e.unselected.id)},filter:b.selectfilter,tolerance:"touch",distance:1});var c=this;$("#rhizo-viewport").click(function(d){c.isOnEmptySpace(d)&&$p.unselectAll()})};rhizo.ui.component.MiniToolbar=function(){};
rhizo.ui.component.MiniToolbar.prototype.render=function(b){$('<span><a href="" onclick="return false" id="rhizo-link-help" title="Help" >?</a><a href="" onclick="self.resizeTo(1000,700);self.reload();" title="Maximize" class="rhizo-maximize-icon"></a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-link-display" >Display</a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-link-selection" >Selection</a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-link-filters" >Filters</a></span><span class="rhizo-filters-header"><a href="" onclick="return false;" id="rhizo-legend" style="display: none">Legend</a></span>').appendTo(b)};
rhizo.ui.component.MiniToolbar.prototype.activate=function(){var b=[{panel:"#rhizo-update-layout",link:"#rhizo-link-display"},{panel:"#rhizo-selection",link:"#rhizo-link-selection"},{panel:"#rhizo-filter-container",link:"#rhizo-link-filters"},{panel:"#rhizo-help",link:"#rhizo-link-help"},{panel:"#rhizo-legend-panel",link:"#rhizo-legend"}];b.forEach(function(c){$(c.link).click(function(){b.forEach(function(d){if(d.panel==c.panel){$(d.panel).toggle();$(d.link).toggleClass("rhizo-filter-open")}else{$(d.panel).css("display",
"none");$(d.link).removeClass("rhizo-filter-open")}});return false})})};rhizo.ui.component.Console=function(){};rhizo.ui.component.Console.prototype.render=function(b){$('<div id="rhizo-console-header"><div id="rhizo-console-close">&#8659;</div>Log Console</div><div id="rhizo-console-contents" style="clear: right; display: none"></div>').appendTo(b)};
rhizo.ui.component.Console.prototype.activate=function(){$("#rhizo-console-close").click(function(){$("#rhizo-console-contents").is(":visible")?$("#rhizo-console-contents").slideUp("slow",function(){$("#rhizo-console-close").html("&#8659;");$("#rhizo-console-contents").empty()}):$("#rhizo-console-contents").slideDown("slow",function(){$("#rhizo-console-close").html("&#8657;")})})};rhizo.ui.component.Layout=function(){};
rhizo.ui.component.Layout.prototype.render=function(b,c){c=c||{};c.miniLayout||$('<div class="rhizo-filters-header">Display</div>').appendTo(b);$('<div id="rhizo-update-layout"><div id="rhizo-layout-extra-options"></div></div>').appendTo(b);c.miniLayout&&$("#rhizo-update-layout").addClass("rhizo-floating-panel").css("display","none");this.select_=$("<select id='rhizo-layout' />");this.detailsMap_={};if(rhizo.layout&&rhizo.layout.layouts)for(layout in rhizo.layout.layouts){b=rhizo.layout.layouts[layout];
this.select_.append($("<option value='"+layout+"'>"+b+"</option>"));if(b.details){b=b.details();this.detailsMap_[layout]=b;$("#rhizo-layout-extra-options").append(b.css("display","none"))}}this.submit_=$("<button>Update</button>");$("#rhizo-update-layout").prepend(this.submit_).prepend(this.select_).prepend("Keep items ordered by: ")};
rhizo.ui.component.Layout.prototype.activate=function(){var b=this.detailsMap_;this.select_.change(function(){for(layout in b)layout==$(this).val()?b[layout].show("fast"):b[layout].hide("fast")});this.submit_.click(function(){$p.layout($("#rhizo-layout").val())})};rhizo.ui.component.SelectionManager=function(){};
rhizo.ui.component.SelectionManager.prototype.render=function(b,c){c=c||{};c.miniLayout||$('<div class="rhizo-filters-header">Selection</div>').appendTo(b);$('<div id="rhizo-selection"></div>').appendTo(b);c.miniLayout&&$("#rhizo-selection").addClass("rhizo-floating-panel").css("display","none");this.button_=$('<button id="rhizo-selected-items-only">Work on selected items only</button>');this.resetButton_=$('<button id="rhizo-selected-reset" disabled="disabled">Reset</button>');$("#rhizo-selection").append(this.button_).append(this.resetButton_)};
rhizo.ui.component.SelectionManager.prototype.activate=function(){this.button_.click(function(){var b=0;for(id in $p.allSelected())b++;if(b==0)rhizo.error("No items selected");else{b=$p.allUnselected();var c=0;for(id in b){b[id].filter("__selection__");c++}$p.alignVisibility();$p.layout(null,{filter:true});$p.unselectAll();$("#rhizo-selected-reset").removeAttr("disabled").text("Reset ("+c+" filtered)")}});this.resetButton_.click(function(){$p.resetAllFilter("__selection__");$p.alignVisibility();$p.layout(null,
{filter:true});$(this).attr("disabled","disabled").text("Reset")})};rhizo.ui.component.Filters=function(){};
rhizo.ui.component.Filters.prototype.render=function(b,c){c=c||{};c.miniLayout||$('<div class="rhizo-filters-header">Filters</div>').appendTo(b);$('<div id="rhizo-filter-container"></div>').appendTo(b);if(c.miniLayout){$("#rhizo-filter-container").addClass("rhizo-floating-panel").css("display","none");$('<span id="rhizo-next-filter" title="Next filter"></span>').appendTo($("#rhizo-filter-container"));$('<span id="rhizo-prev-filter" title="Previous filter"></span>').appendTo($("#rhizo-filter-container"))}b=
true;var d=$p.metaModel();for(key in d){var e=d[key].kind.renderFilter(d[key],key);if(c.miniLayout)if(b)b=false;else e.css("display","none");$("#rhizo-filter-container").append(e)}};
rhizo.ui.component.Filters.prototype.activate=function(){$("#rhizo-next-filter").click(function(){var b=$(".rhizo-filter:visible"),c=b.next(".rhizo-filter:hidden").eq(0);if(c.length>0){b.css("display","none");c.css("display","")}});$("#rhizo-prev-filter").click(function(){var b=$(".rhizo-filter:visible"),c=b.prev(".rhizo-filter:hidden").eq(0);if(c.length>0){b.css("display","none");c.css("display","")}})};rhizo.ui.component.Legend=function(){};
rhizo.ui.component.Legend.prototype.render=function(b,c){c=c||{};var d=null;if($p.renderer().getSizeRange)d=$p.renderer().getSizeRange();var e=null;if($p.renderer().getColorRange)e=$p.renderer().getColorRange();if(d||e){$('<div id="rhizo-legend-panel"></div>').appendTo(b);if(c.miniLayout){$("#rhizo-legend-panel").addClass("rhizo-floating-panel").css("display","none");$("#rhizo-legend").show()}else $('<div class="rhizo-filters-header">Legend</div>').appendTo($("#rhizo-legend-panel"))}if(d){$('<div id="rhizo-legend-size" style="margin-bottom: 5px"><span id="rhizo-legend-size-min" ></span><span class="ar-fon-0">A</span> -- <span class="ar-fon-5">A</span><span id="rhizo-legend-size-max" ></span></div>').appendTo($("#rhizo-legend-panel"));
$("#rhizo-legend-size-min").html(d.label+" &nbsp; "+rhizo.ui.toHumanLabel(d.min)+":");$("#rhizo-legend-size-max").html(": "+rhizo.ui.toHumanLabel(d.max))}if(e){$('<div id="rhizo-legend-color" style="margin-bottom: 5px"><span id="rhizo-legend-color-min"></span><span class="ar-col-0 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-1 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-2 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-3 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-4 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span class="ar-col-5 ar-col-legend">&nbsp; &nbsp;</span>&nbsp;<span id="rhizo-legend-color-max"></span></div>').appendTo($("#rhizo-legend-panel"));
$("#rhizo-legend-color-min").html(e.label+" &nbsp; "+rhizo.ui.toHumanLabel(e.min)+":");$("#rhizo-legend-color-max").html(": "+rhizo.ui.toHumanLabel(e.max))}};rhizo.ui.component.Legend.prototype.activate=function(){};rhizo.ui.component.Actions=function(){};rhizo.ui.component.Actions.prototype.render=function(b){$('<div id="rhizo-actions"><h1>Actions</h1><div class="rhizo-action" id="rhizo-action-2">Sample Action 1</div><div class="rhizo-action" id="rhizo-action-1">Sample Action 2</div></div>').appendTo(b)};
rhizo.ui.component.Actions.prototype.activate=function(){if($(".rhizo-action").length>0){$(".rhizo-action").draggable({helper:"clone"});$("#rhizo-universe").droppable({accept:".rhizo-action",drop:function(b,c){var d=$("#rhizo-universe").offset(),e=$("#rhizo-universe").width();b=$("#rhizo-universe").height();var f=c.draggable.text(),g=c.absolutePosition.left-d.left;if(g+200>e)g=e-210;c=c.absolutePosition.top-d.top;if(c+200>b)c=b-210;var h=$("<div class='rhizo-droppable-action'>Drop your items here to perform:<br />"+
f+"</div>").css("position","absolute").css("top",c).css("left",g).css("display","none");$("#rhizo-universe").append(h);h.fadeIn();h.draggable({start:function(){$p.toggleSelection("disable")},stop:function(){$p.toggleSelection("enable")}});h.droppable({accept:".rhizo-model",drop:function(i,k){if($p.isSelected(k.draggable[0].id)){i=0;for(j in $p.allSelected())i++;alert("Action applied on "+i+" elements");for(j in $p.allSelected())$("#"+j).move($("#"+j).data("dropTop0"),$("#"+j).data("dropLeft0"));$p.unselectAll()}else{var j=
k.draggable[0].id;alert("Action applied on "+$p.model(j));$("#"+j).move($("#"+j).data("dropTop0"),$("#"+j).data("dropLeft0"))}}});h.dblclick(function(){h.remove();return false})}})}};rhizo.ui.component.MiniTemplate=function(){this.components_={LOGO:new rhizo.ui.component.Logo,VIEWPORT:new rhizo.ui.component.Viewport,LAYOUT:new rhizo.ui.component.Layout,SELECTION_MANAGER:new rhizo.ui.component.SelectionManager,FILTERS:new rhizo.ui.component.Filters,LEGEND:new rhizo.ui.component.Legend,MINITOOLBAR:new rhizo.ui.component.MiniToolbar}};
a=rhizo.ui.component.MiniTemplate.prototype;
a.renderChrome=function(b,c){rhizo.disableLogging();this.components_.VIEWPORT.render(b,c);this.progress_=new rhizo.ui.component.Progress($("#rhizo-viewport"));this.bottomBar_=$('<div id="rhizo-bottom-bar"></div>').appendTo(b);this.progress_.update(10,"Creating static UI...");this.components_.MINITOOLBAR.render(this.bottomBar_,c);b=$('<div id="rhizo-help" class="rhizo-floating-panel" style="display:none"></div>').appendTo(this.bottomBar_);this.components_.LOGO.render(b,c);this.progress_.update(25,
"All static UI created.")};a.activateChrome=function(b){this.progress_.update(26,"Activating static UI...");this.components_.VIEWPORT.activate(b);this.components_.MINITOOLBAR.activate(b);this.progress_.update(33,"Loading models...")};
a.renderDynamic=function(b,c){this.progress_.update(34,"Creating dynamic controls...");this.components_.LAYOUT.render(this.bottomBar_,c);this.progress_.update(38,"Layout engine created.");this.components_.SELECTION_MANAGER.render(this.bottomBar_,c);this.progress_.update(42,"Selection manager created.");this.components_.FILTERS.render(this.bottomBar_,c);this.progress_.update(46,"Filters created.");this.components_.LEGEND.render(this.bottomBar_,c);this.progress_.update(48,"Legend created.")};
a.activateDynamic=function(b){this.progress_.update(51,"Activating dynamic controls...");this.components_.LAYOUT.activate(b);this.components_.SELECTION_MANAGER.activate(b);this.components_.FILTERS.activate(b);this.components_.LEGEND.activate(b);this.progress_.update(66,"Rhizosphere controls are ready.")};a.done=function(){this.progress_.update(100,"Rhizosphere ready!")};
rhizo.ui.component.StandardTemplate=function(){this.components_={LOGO:new rhizo.ui.component.Logo,VIEWPORT:new rhizo.ui.component.Viewport,CONSOLE:new rhizo.ui.component.Console,LAYOUT:new rhizo.ui.component.Layout,SELECTION_MANAGER:new rhizo.ui.component.SelectionManager,FILTERS:new rhizo.ui.component.Filters,LEGEND:new rhizo.ui.component.Legend,ACTIONS:new rhizo.ui.component.Actions}};a=rhizo.ui.component.StandardTemplate.prototype;
a.renderChrome=function(b,c){this.components_.VIEWPORT.render(b,c);this.progress_=new rhizo.ui.component.Progress($("#rhizo-viewport"));this.leftBar_=$('<div id="rhizo-left"></div>').appendTo(b);$('<div id="rhizo-right-pop"></div>').appendTo(b);this.rightBar_=$('<div id="rhizo-right" style="display:none"></div>').appendTo(b);this.progress_.update(10,"Creating static UI...");this.components_.LOGO.render(this.leftBar_,c);this.components_.CONSOLE.render(this.rightBar_,c);this.progress_.update(25,"All static UI created.")};
a.activateChrome=function(b){this.progress_.update(26,"Activating static UI...");$("#rhizo-right-pop").click(function(){if($("#rhizo-right").is(":visible")){$(this).css("right",0);$("#rhizo-viewport").css("right",5);$("#rhizo-right").css("display","none")}else{$("#rhizo-viewport").css("right",135);$(this).css("right",130);$("#rhizo-right").css("display","")}});this.components_.CONSOLE.activate(b);this.components_.VIEWPORT.activate(b);this.progress_.update(33,"Loading models...")};
a.renderDynamic=function(b,c){this.progress_.update(34,"Creating dynamic controls...");this.components_.LAYOUT.render(this.leftBar_,c);this.progress_.update(38,"Layout engine created.");this.components_.SELECTION_MANAGER.render(this.leftBar_,c);this.progress_.update(42,"Selection manager created.");this.components_.FILTERS.render(this.leftBar_,c);this.progress_.update(46,"Filters created.");this.components_.LEGEND.render(this.leftBar_,c);this.progress_.update(48,"Legend created.");this.components_.ACTIONS.render(this.rightBar_,
c);this.progress_.update(50,"Actions created")};a.activateDynamic=function(b){this.progress_.update(51,"Activating dynamic controls...");this.components_.LAYOUT.activate(b);this.components_.SELECTION_MANAGER.activate(b);this.components_.FILTERS.activate(b);this.components_.LEGEND.activate(b);this.components_.ACTIONS.activate(b);this.progress_.update(66,"Rhizosphere controls are ready.")};a.done=function(){this.progress_.update(100,"Rhizosphere ready!")};namespace("rhizo.gviz");
rhizo.gviz.Initializer=function(b,c,d){this.dt_=b;this.options_=c||{};this.customRenderer_=d;this.init_()};a=rhizo.gviz.Initializer.prototype;a.init_=function(){this.metamodel=this.buildMetaModel_();this.models=this.loadModels_(this.metamodel);this.renderer=this.customRenderer_?this.customRenderer_:this.createDefaultRenderer_(this.metamodel,this.models)};
a.buildMetaModel_=function(){for(var b={},c=0,d=this.dt_.getNumberOfColumns();c<d;c++){var e=this.dt_.getColumnId(c);b[e]={};b[e].label=this.dt_.getColumnLabel(c);if(b[e].label=="")b[e].label="Column "+e;var f=this.dt_.getColumnType(c);if(f=="number"){f=this.dt_.getColumnRange(c).min;var g=this.dt_.getColumnRange(c).max;if(f==g)b[e].kind=rhizo.meta.Kind.NUMBER;else{b[e].kind=rhizo.meta.Kind.RANGE;b[e].min=f;b[e].max=g}}else if(f=="boolean")b[e].kind=rhizo.meta.Kind.BOOLEAN;else{f!="string"&&rhizo.warning("Column "+
b[e].label+" will be treated as String. Unsupported type: "+f);if(b[e].label.indexOf("CAT")!=-1){b[e].kind=rhizo.meta.Kind.CATEGORY;b[e].label=b[e].label.replace("CAT","").replace(/^\s+|\s+$/g,"");b[e].categories=this.parseCategories_(c);if(b[e].label.indexOf("MUL")!=-1){b[e].label=b[e].label.replace("MUL","").replace(/^\s+|\s+$/g,"");b[e].multiple=true}}else b[e].kind=rhizo.meta.Kind.STRING}this.buildAutoRenderInfo_(b[e],e)}return b};
a.parseSingleCategory_=function(b){var c={};b=b.split(",");b=$.grep(b,function(d){return d!=""});b=b.forEach(function(d){c[d.replace(/^\s+|\s+$/g,"")]=true});b=[];for(category in c)b.push(category);return b};a.parseCategories_=function(b){for(var c={},d=0,e=this.dt_.getNumberOfRows();d<e;d++){var f=this.parseSingleCategory_(this.dt_.getValue(d,b));f.forEach(function(g){c[g]=true})}b=[];for(category in c)b.push(category);return b.sort()};
a.buildAutoRenderInfo_=function(b,c){var d={},e=false;if(this.options_.arMaster&&this.matchAutoRenderOption_(this.options_.arMaster,b.label,c))e=d.master=true;if(this.options_.arSize&&this.matchAutoRenderOption_(this.options_.arSize,b.label,c)){d.bind=(d.bind?d.bind:"")+"size ";e=true}if(this.options_.arColor&&this.matchAutoRenderOption_(this.options_.arColor,b.label,c)){d.bind=(d.bind?d.bind:"")+"color ";e=true}if(e)b.ar=d};
a.matchAutoRenderOption_=function(b,c,d){var e=/^[a-zA-Z]$/;return e.test(b)?b.toLowerCase()==(new String(d)).toLowerCase():c.toLowerCase()==b.toLowerCase()?true:c.replace("CAT","").replace("MUL","").toLowerCase()==b.toLowerCase()};
a.loadModels_=function(b){for(var c=[],d=0,e=this.dt_.getNumberOfRows();d<e;d++){for(var f={},g=0,h=this.dt_.getNumberOfColumns();g<h;g++){f.id="gviz-"+d;var i=this.dt_.getValue(d,g);if(b[this.dt_.getColumnId(g)].kind==rhizo.meta.Kind.CATEGORY)f[this.dt_.getColumnId(g)]=this.parseSingleCategory_(i);else f[this.dt_.getColumnId(g)]=i}c.push(f)}return c};a.createDefaultRenderer_=function(b,c){return new rhizo.autorender.AR(b,c,this.options_.arDefaults,this.options_.arNumFields)};
rhizo.gviz.DebugRenderer=function(b){this.dt_=b};rhizo.gviz.DebugRenderer.prototype.render=function(b){for(var c=$("<div />"),d=0,e=this.dt_.getNumberOfColumns();d<e;d++)c.append("<p>"+b[this.dt_.getColumnId(d)]+"</p>");return c};namespace("rhizo.model.loader");rhizo.model.loader.loaders=[];rhizo.model.loader.JS=function(){};rhizo.model.loader.loaders.push(new rhizo.model.loader.JS);rhizo.model.loader.JS.prototype.setGlobalOptions=function(b){this.globalOptions_=b};
rhizo.model.loader.JS.prototype.match=function(b){return/\.js$/.test(b)};rhizo.model.loader.JS.prototype.load=function(b){var c=document.createElement("script");c.src=b;c.type="text/javascript";document.getElementsByTagName("head")[0].appendChild(c)};rhizo.model.loader.GoogleSpreadsheet=function(){};rhizo.model.loader.loaders.push(new rhizo.model.loader.GoogleSpreadsheet);rhizo.model.loader.GoogleSpreadsheet.prototype.setGlobalOptions=function(b){this.globalOptions_=b};
rhizo.model.loader.GoogleSpreadsheet.prototype.match=function(b){return/spreadsheets\.google\.com/.test(b)};rhizo.model.loader.GoogleSpreadsheet.prototype.load=function(b){if(google.visualization){b=new google.visualization.Query(b);var c=this,d=function(e){c.handleQueryResponse_(e)};b.send(d)}else rhizo.error("Google Visualization APIs not available.")};
rhizo.model.loader.GoogleSpreadsheet.prototype.handleQueryResponse_=function(b){if(b.isError())alert("GViz load failed: "+b.getMessage());else{b=new rhizo.gviz.Initializer(b.getDataTable(),this.globalOptions_);rhizo.bootstrap.setRenderer(b.renderer);rhizo.bootstrap.setMetaModel(b.metamodel);rhizo.bootstrap.deploy(b.models)}};rhizo.model.loader.GoogleGadget=function(){};rhizo.model.loader.loaders.push(new rhizo.model.loader.GoogleGadget);
rhizo.model.loader.GoogleGadget.prototype.setGlobalOptions=function(b){this.globalOptions_=b};rhizo.model.loader.GoogleGadget.RESOURCE="__google_gadget";rhizo.model.loader.GoogleGadget.prototype.match=function(b){var c=new RegExp(rhizo.model.loader.GoogleGadget.RESOURCE);return c.test(b)};
rhizo.model.loader.GoogleGadget.prototype.load=function(){if(google.visualization)if(typeof _IG_Prefs=="undefined")rhizo.error("Google Gadget APIs not available.");else{var b=new _IG_Prefs,c=new google.visualization.GadgetHelper;b=c.createQueryFromPrefs(b);var d=this;c=function(e){d.handleQueryResponse_(e)};b.send(c)}else rhizo.error("Google Visualization APIs not available.")};rhizo.model.loader.GoogleGadget.prototype.handleQueryResponse_=rhizo.model.loader.GoogleSpreadsheet.prototype.handleQueryResponse_;
rhizo.model.loader.load=function(b,c){for(var d=rhizo.model.loader.loaders,e=0;e<d.length;e++){d[e].setGlobalOptions(c);if(d[e].match(b)){d[e].load(b);return}}alert("No loader available for the resource: "+b)};namespace("rhizo.bootstrap");rhizo.bootstrap.go=function(b,c,d){new rhizo.bootstrap.Bootstrap(b,c);$globalBootstrapper_.go(d)};rhizo.bootstrap.setMetaModel=function(b){$globalBootstrapper_.setMetaModel(b)};rhizo.bootstrap.setRenderer=function(b){$globalBootstrapper_.setRenderer(b)};
rhizo.bootstrap.deploy=function(b){$globalBootstrapper_.deploy(b)};$globalBootstrapper_=null;rhizo.bootstrap.Bootstrap=function(b,c){this.container_=b;this.options_={selectfilter:".rhizo-model:visible"};c&&$.extend(this.options_,c);if(this.options_.autoSize)this.options_.miniLayout=$(document).width()>=600&&$(document).height()>=250?false:true;$globalBootstrapper_=this};
rhizo.bootstrap.Bootstrap.prototype.go=function(b){this.template_=this.options_.miniLayout?new rhizo.ui.component.MiniTemplate:new rhizo.ui.component.StandardTemplate;this.template_.renderChrome(this.container_,this.options_);this.template_.activateChrome(this.options_);rhizo.ui.performanceTuning(this.options_.noAnims);this.project_=new rhizo.Project(this.options_);b=b;if(!b){var c=/source=(.*)$/;c=c.exec(document.location.href);if(!c||!c[1])rhizo.error("Unable to identify datasource from location");
else b=unescape(c[1])}b&&rhizo.model.loader.load(b,this.options_)};rhizo.bootstrap.Bootstrap.prototype.setMetaModel=function(b){this.project_.setMetaModel(b)};rhizo.bootstrap.Bootstrap.prototype.setRenderer=function(b){this.project_.setRenderer(b)};rhizo.bootstrap.Bootstrap.prototype.deploy=function(b){this.template_.renderDynamic(this.container_,this.options_);this.template_.activateDynamic(this.options_);this.project_.deploy(b);this.template_.done()};
